### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#1]
@jonscottfilm could you send over the user stories.

**Comment by jonscottfilm** [comment]
Jono reply

**Comment by jonscottfilm** [comment]
Before I continue, is this not detailed enough? I will go on to add fields to each story.

https://docs.google.com/spreadsheets/d/1IOhZkTbSk8GEqrpZIMXrvwTXF4o5e1lpwRBRCPim9w0/edit?usp=sharing

**Comment by jackcarlisle** [comment]
@jonscottfilm this is a perfect amount of detail, thank you!

**Comment by jonscottfilm** [comment]
Do you want me to create each user story as individual issues in Github?




Jonathan Scott | m: +44 (0)7771 628 714 <+44%207771%20628714> | e:
jonscottfilm@gmail.com

**Comment by jackcarlisle** [comment]
@jonscottfilm yeah that would be great! User stories follow the format below: 

>As a... (user type)
I want to... (be able to do some sort of functionality)
So that... (I can reach a desired outcome)

Here's an example for the first one on the list:

>As a personal user,
I want to be able to create an account,
So that I can login to the application

**Comment by jonscottfilm** [comment]
Understood

**Comment by jackcarlisle** [comment]
@jonscottfilm me and @JMurphyWeb are going to make a start on them

**Comment by jonscottfilm** [comment]
ok, sorry

**Comment by JMurphyWeb** [comment]
@jonscottfilm I am closing this issue now as it I am satisfied that it has been resolved. 

user stories and other issues that you open, should only be closed by you, when you are satisfied.  Closing an issue should contain a brief comment of some sort explaining why it is being closed.
