### ISSUE TITLE
Log in bug

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#105]
If a user isn't logged in and they navigate to the application they are redirected and given a flash "you must be logged in to view that page". We need to remove this.

- [x] remove unnecessary flash

**Comment by jonscottfilm** [comment]
I have been getting these errors. So long as I have followed the correct procedure throwing the error.. Logged out. Click on email link (in this case, offer updated link). Error still appearing:

![image](https://cloud.githubusercontent.com/assets/28431542/26317287/e119a4ac-3f0e-11e7-8d95-539a1e3fcffd.png)

**Comment by jackcarlisle** [comment]
Is this not expected seeing as you logged out? The link in the email takes you to a page that requires you to be logged in. Would you like us to log the user in once they click the link if they aren't logged in already?

**Comment by jonscottfilm** [comment]
Oh, sorry - am I misreading your initial issue? (**really sorry** if I'm creating havoc on here, guys! Just getting involved :)) 

It sounded like you we asking me to Test that the Flash had been removed. I am still getting it. But yes, it would seem logical _to_ get the flash.

'If a user isn't logged in and they navigate to the application they are redirected and given a flash "you must be logged in to view that page". We need to remove this.

 remove unnecessary flash'

**Comment by jackcarlisle** [comment]
Yeah we still want the flash to be displayed if it's the right time to show it, not get rid of it altogether but just in that instance. Sorry if that was a bit unclear!

**Comment by jonscottfilm** [comment]
Gotya. Thanks.

**Comment by jonscottfilm** [comment]
Closed.
