### ISSUE TITLE
Contractor - Accept/Reject Offer

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#11]
As a contractor,
I want to be able to accept or reject an offer made to me,
So that I can inform the project manager of my decision

**Comment by JMurphyWeb** [comment]
This story should be covered in dashboard view issue #19

**Comment by jonscottfilm** [comment]
Reject offer hits internal server error.

![image](https://cloud.githubusercontent.com/assets/28431542/26737461/2353cd96-47c2-11e7-9397-0e3ac8fa8957.png)

Reload page gives:
![image](https://cloud.githubusercontent.com/assets/28431542/26737494/439cd1ce-47c2-11e7-8c42-f77936c35e3e.png)

**Comment by JMurphyWeb** [comment]
Tested this locally and on Heroku and it is now working fine:
![screen shot 2017-06-05 at 10 47 21](https://cloud.githubusercontent.com/assets/12638261/26779220/7bd9c224-49dc-11e7-8dc4-f85594c2bca2.png)

**Comment by jonscottfilm** [comment]
Working!
