### ISSUE TITLE
Department and Job title dropdowns

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#112]
We need to restrict the job titles available to be selected once the department has been selected. This will prevent the wrong contracts being selected if a PM inputs the wrong job title by accident.

- [x] reformat the data of departments and job titles
- [x] change the dropdowns so that they include only the job titles that relate to that department.

**Comment by jonscottfilm** [comment]
Amazing. Simple things will please UX.

**Minor snafu.** If PM forgets to enter job title, hits send offer, on returning to the dropdown field where the error is, it doesn't see the department list of job titles... Can kick it by changing department back and forth.

![image](https://cloud.githubusercontent.com/assets/28431542/26359954/ba2fe75a-3fce-11e7-96bd-06a3a15e1cb4.png)

**Comment by jonscottfilm** [comment]
Of course, I suppose this falls under the 'edit offer' scope which you did say you were yet to implement the change on, so. :) (Jono cools his jets)

**Comment by jackcarlisle** [comment]
@jonscottfilm I'm looking into this now
