### ISSUE TITLE
Full Name as part of offer

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#114]
We agreed to not have First Name & Last Name as part of the offer, and it not appear until entered into Start Pack by contractor. That is current working method.

My only issue with that (and it's exposure is minor) is, although target email is the unique identifier, there is no qualifying fields without the full name also being present. 

_If_ the offer reaches it's intended recipient correctly, then Joe Bloggs knows it's his email, he's expecting the offer for Grip & all deal info as discussed.

_Should_ the offer be emailed to a 3rd party, e.g an agent (our current method, for which 'target email' works), is they _could_ have multiple grips on their books, and confusion could occur, because there is no other unique identifier to differentiate between Grip 1, and Grip 2 who might have different start dates, and possibly rates.

_Also_ a back and forth 'amended offer' between contractor and PM, could result in confusion for the PM, when he's handling multiple offers, and he can only identify by email.

It also means the email offer, and amended offer, and any notification prior to completing Start Pack, is not personally addressed to the contractor - which I think is a nice, and effective way, of engaging the use in the app.

Sure this is a 'nice to have', Priority 4. I've created a new issue:

**Comment by jonscottfilm** [comment]
As & when we do this, consider combination of aka names and real.

**Comment by jackcarlisle** [comment]
@jonscottfilm is this just a case of adding the recipient name to the offer creation?

**Comment by jonscottfilm** [comment]
Yes. And if we keep it editable, then the user can correct any typos... Hmm, how does that work for _existing_ karma users...?

**Comment by jackcarlisle** [comment]
I think we could, for now, just have a simple implementation of the name in the offer creation (*typos allowed*) with no real connection to the recipient but just another identifier. We can then build from this and make it smarter down the line

**Comment by jonscottfilm** [comment]
Great, agreed.
