### ISSUE TITLE
Get help menu

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#119]
MVP, this will just be contact details. 

Users must not feel abandoned. Easy to find way to contact us.

Clickable 'email us'
Clickable 'call us'
Guess we could create a Whatsapp chat link, or similar?

Long-term this will be live chat, FAQ's, forums.

**Comment by JMurphyWeb** [comment]
@jonscottfilm I think a contact us link is a great idea to get in for testing.

We already have email link in the footer, although the mailto link is wrong: hello@impossible.com

Fixing that now.

**Comment by JMurphyWeb** [comment]
will soon be updated to engine.onboard@gmail.com

**Comment by jackcarlisle** [comment]
@jonscottfilm do we want to have a "Contact us" section? Or is it good enough for now to have the email address within the footer?

**Comment by jonscottfilm** [comment]
Yeah. The most simple UX way of implementing a 'Contact us' in the footer, which has email, instant messaging, phone.

**Comment by jackcarlisle** [comment]
@jonscottfilm So a separate view with options for contacting us? Or include these options within the footer? (*sorry just making absolutely clear*)

**Comment by jonscottfilm** [comment]
Sorry, my bad. A separate view seems unnecessary for now, but can you do a drop-down in the footer to offer the alt methods of communication?

**Comment by jackcarlisle** [comment]
A dropdown might be a bit strange in terms of UX. We could simply add more contact options to the footer in plain sight?

**Comment by jonscottfilm** [comment]
Agreed. Resolution: 

'Terms    Privacy     help@teamengine.co.uk'

(@jonscottfilm would like link to initiate an instant messaging chat, as more immediate / helpful / easier response.)

**Comment by jackcarlisle** [comment]
@jonscottfilm could you please open an issue for the instant messaging chat? We'll then time estimate it and then you can prioritise

**Comment by jonscottfilm** [comment]
Sure. If it means a lot of work, then forget it - we'll just survive with email. I was thinking, literally, a Hangout session link, or WhatsApp.
