### ISSUE TITLE
Make offer to contractor

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#12]
As a project manager, I can send an offer to an email address.

Additional fields:
email address
rate of pay (per day)
start date
duration (weeks)
additional notes
job department
job title

Questions:
- did we decide that the project manager would decide the department and job type in this initial offer?
- We took the following user stories from the spread sheet and think they are both covered by this story. What do you think?
> a user can create a custom offer for a person to work on a project
> a user can send an offer to a person to work on a project

**Comment by jonscottfilm** [comment]
they are similar stories, but my thinking was the difference is between **create** & **send**, i.e. if a PM starts a job offer, can he save it as draft?, and send at a later time?

**Comment by JMurphyWeb** [comment]
I replied in the doc, but best to keep it in the issue.

From what I can see, an offer doesn't consist of too much information, so wouldn't justify the need to save an offer as a draft.  I may be overlooking something though so let me know your thoughts.

**Comment by jackcarlisle** [comment]
@jonscottfilm regarding this comment https://github.com/karmaradio/karma/issues/12#issuecomment-299874573 

I think initially the job offers will be relatively small and so functionality for drafts might be slightly surplus to requirements at this stage.

**Comment by JMurphyWeb** [comment]
Regarding the job title/department. I agree, the info that gets added at this stage by the PM is not editable by the contractor. 

Can we work off the assumption that department and job title will be agreed verbally prior the PM creating the offer on the application?

**Comment by jonscottfilm** [comment]
dept/job title agreed in principal, yes - but will we get a lot of rejections when the job title is wanted to be changed....?

true, right now, the offer fields are not many... 

this was the initial pre-deal offer form on MI5: (might have to step through it, in the meantime I'll try to extract fields) https://docs.google.com/forms/d/e/1FAIpQLSc_Bu8vCb2P3VaHT0FfQNRbGZwWmR1s6kZVtXs178uIB9Ol3g/viewform

**Comment by jonscottfilm** [comment]
this can be streamlined somewhat, because all the number fields can be calculated within the user start form, being determined by the rate per week (or day) within this offer form.

**Comment by jonscottfilm** [comment]
I make it 28 (yellow) essential fields, in the Mi5 form. 
https://docs.google.com/spreadsheets/d/106M9tdqplKXc78fGcE6Iz8fLJNamA6AiM2qXp3avkLc/edit?usp=sharing

I'd need to think about if/how that could be reduced.

**Comment by JMurphyWeb** [comment]
Ok thanks for that. Think we need to get this defined asap. As mentioned, there more fields in here than we anticipated.

**Comment by jackcarlisle** [comment]
@jonscottfilm what does it mean if a field is salmon pink?

**Comment by jonscottfilm** [comment]
yes - it appears that way to me too, although they are in the list of 167 fields spreadsheet, it just wasn't defined for this user story. 
I agree it needs to be defined asap - and I'm sure we can reduce it. Thing is, these are the fields of 'the deal' which are to be defined by the project manager, to the contractor - so if they're defined at the offer stage, they carry throughout, and if not, they will need completing at the contractor start form stage, and they may not know the answers...

Ignore salmon pink. Those were fields I calculated.

I need to be offline/limited access between 4.30 - 6.30, I'm afraid. Should we speak before then?
I'm slightly bewildered by github, don't want to miss anything - need to turn off email notifications I think!

**Comment by JMurphyWeb** [comment]
Sounds good - speak at 4 on the same hangouts link from todays standup (in calendar)?

Any reason that we need given name, family name and gender given that info will be entered by the contractor when they sign up to application?

**Comment by jonscottfilm** [comment]
ok

**Comment by jonscottfilm** [comment]
Can we make it 4.10

No, no need. Some of these fields are due to this form going via studio
first, and limitations of Google forms.


Jonathan Scott | m: +44 (0)7771 628 714 | e: jonscottfilm@gmail.com

**Comment by jackcarlisle** [comment]
@jonscottfilm yeah that's no problem, 4.10 it is

**Comment by JMurphyWeb** [comment]
@jonscottfilm test

**Comment by jonscottfilm** [comment]
OK, Becca and I just been through this at length - and narrowed it down to 23 fields... As engine is used and develops, it will grow, with the project user need for custom fields.

Is the increase in the fields anticipated for this offer an issue for you, or does it just mean a slightly bigger build?

In terms of what subsequently appears in the user 'my projects' stub history, that could be reduced more than currently listed. In order for a job history to be useful, one will want to refer to all pertinent data (project name, dates, rates), legible but small in 3 lines of multiple columns. I've marked those fields on the spreadsheet too. In time, when that stub is expandable, that data can be in full, hidden.

Re-formatted vertically. I should have just used the master field list! :)
https://docs.google.com/spreadsheets/d/106M9tdqplKXc78fGcE6Iz8fLJNamA6AiM2qXp3avkLc/edit?usp=sharing

**Comment by jonscottfilm** [comment]
as & when you get to this, do we now need to consider the ability to save draft offers, being they are quite large now?

**Comment by jackcarlisle** [comment]
@jonscottfilm We'll take a look into the possibility of saving drafts. This might push us slightly beyond scope but it's something that we can research.

Also would you be able to give us the list of fields that you want to have associated with the user compared to those that are given during project + offer creation? i.e. the fields that are generic to all users and those that will change on a project to project basis?

**Comment by jonscottfilm** [comment]
@jackcarlisle appreciate drafts might be a challenge, but fear a PM will need it with this much data per offer.

this is the link to ALL personal fields: https://docs.google.com/spreadsheets/d/1hYBorZdr_83qKcNFbFHYhZuRsycqImhXgi_3MkpN2xs/edit?usp=sharing

Or I can paste them in here?

**Comment by jonscottfilm** [comment]
how many fields are gonna scare you off?!

we _could_ reduce it, but if there's not much impact/harm, better to keep everything in, and capture as much as possible, no?

**Comment by jonscottfilm** [comment]
**Profile Data Fields:**

OK. I need to clean up some of the calculation references, but this is in good shape.

Filter by column: 'Required for what Process?
https://docs.google.com/spreadsheets/d/1HhF6nln1EDXwbMTjJ4zS6Pf2AP73V-3DsMhZXP3-gEU/edit?usp=sharing

**Comment by jonscottfilm** [comment]
Profile Data Fields incorporates and thereby replaces this 'project fields' spreadsheet 
(**OLD** https://docs.google.com/spreadsheets/d/106M9tdqplKXc78fGcE6Iz8fLJNamA6AiM2qXp3avkLc/edit?usp=sharing)

**Comment by jonscottfilm** [comment]
**Contractor Job Titles and Departments**
First, extensive, pass at this. There will always be more variations wanted by projects.
https://docs.google.com/spreadsheets/d/1Mt1oQQtYGhLJx1dL_ZT936GDX8lOQybN2fbnm8CZnPo/edit?usp=sharing

(this might want to live elsewhere in other issue #...)

**Comment by JMurphyWeb** [comment]
@jonscottfilm I feel like this is worthy of a new issue with label 'epic'. Above links can be included and any discussion we have on them can go in there.

As you have seen, we can link issues using the #(issue number) 🎉

**Comment by jonscottfilm** [comment]
Gotya.

**Comment by JMurphyWeb** [comment]
Anything to do with money, store in float (pounds) or int (pence)

>mix phoenix.gen.html Offer offers 
user_email:references:users -> ensure it references user email not id 
project_id:references:project 
department:string 
job_title:string 
contract_type:string 
start_date:date 
daily_or_weekly:string 
working_week:float -> can be 5, 5.5, 6
currency:string 
overtime_rate_per_hour:integer  
other_deal_provisions:text 
box_rental_description:text 
box_rental_fee_per_week:integer 
box_rental_cap:integer
box_rental_start_date:string -> date, shoot period only, 20 weeks -> seems like duration as opposed to  start date 
equipment_rental_description:string -> string or text ?
equipment_rental_fee_per_week:float
equipment_rental_cap:float
equipment_rental_start_date:string -> date, shoot period only, 20 weeks -> seems like duration as opposed to  start date 
vehicle_allowance_per_week:float 
fee_per_day_inc_holiday:float 
fee_per_day_exc_holiday:float 
fee_per_week_inc_holiday:float 
fee_per_week_exc_holiday:float 
holiday_pay_per_day:float 
holiday_pay_per_week:float 
sixth_day_fee:float -> can be 1, 1.5, 2
seventh_day_fee:float -> can be 1, 1.5, 2
additional_note:text
accepted:bool -> default null
active:bool -> not sure if we want this?

**Comment by jackcarlisle** [comment]
@JMurphyWeb might run into problems (not sure if we will) if we try to reference a user that isn't in the database yet (pre-signup). We can perform a check in the controller to check whether or not they are registered and then act accordingly. We could simply have a `target_email` that we send a notification to either prompting them to sign up, or check their offers if they've already registered.

**Comment by JMurphyWeb** [comment]
yeah that is a good point. So are you suggesting target_email and user_id?

**Comment by jackcarlisle** [comment]
Yeah I think that might be better for the case when we don't know if they're registered. We'll need to assign the `user_id` to the offer once they do register. We might need to have a bit of a discussion around this

**Comment by JMurphyWeb** [comment]
I think so too. I'm going to have a quick think about it then skype you?

Also I wonder if we should have an accepted and a contractor_details_verifiied field

accepted -> contractor accepts the offer
contractor_details_verifiied -> PM has reviewed the info given by contractor and 'okayed' it

**Comment by jackcarlisle** [comment]
Ok perfect. 

Yeah good call on those fields

**Comment by JMurphyWeb** [comment]
I've updated it:

>target_email:string
user_id:references:users -> can be null if target_email doesnt exist in db

**Comment by JMurphyWeb** [comment]
final gen:

> mix phoenix.gen.html Offer offers 
target_email:string
user_id:references:users 
project_id:references:projects
department:string 
job_title:string 
contract_type:string 
start_date:date 
daily_or_weekly:string 
working_week:float 
currency:string 
overtime_rate_per_hour:integer  
other_deal_provisions:text 
box_rental_description:text 
box_rental_fee_per_week:integer 
box_rental_cap:integer
box_rental_start_date:string 
equipment_rental_description:string 
equipment_rental_fee_per_week:integer
equipment_rental_cap:integer
equipment_rental_start_date:string 
vehicle_allowance_per_week:integer
fee_per_day_inc_holiday:integer
fee_per_day_exc_holiday:integer
fee_per_week_inc_holiday:integer
fee_per_week_exc_holiday:integer
holiday_pay_per_day:integer
holiday_pay_per_week:integer
sixth_day_fee:integer 
seventh_day_fee:integer 
additional_notes:text
accepted:bool 
active:bool 
contractor_details_verified:bool

**Comment by JMurphyWeb** [comment]
@jonscottfilm In the make offer stage, which of the following are required fields for the project manager to fill in. **Please feel free to edit this comment, remove any fields that are not REQUIRED**:

target_email:string
user_id:references:users
project_id:references:projects
department:string
job_title:string
start_date:date
daily_or_weekly:string
working_week:float
currency:string
overtime_rate_per_hour:integer
other_deal_provisions:text
box_rental_description:text
box_rental_fee_per_week:integer
box_rental_cap:integer
box_rental_period:string
equipment_rental_description:string
equipment_rental_fee_per_week:integer
equipment_rental_cap:integer
equipment_rental_period:string
vehicle_allowance_per_week:integer
fee_per_day_inc_holiday:integer
holiday_pay_per_day:integer
holiday_pay_per_week:integer
sixth_day_fee:float
seventh_day_fee:float
additional_notes:text
contractor_details_accepted:boolean

**Comment by jonscottfilm** [comment]
Hey Jack. Brace yourself...

Most required (R), i.e. essential),
some conditional & required (CR)
some calculated (C),
some to delete (D),
some optional (O).
Oh, and NEW field (N) :-)

target_email:string
user_id:references:users
project_id:references:projects
department:string (R)
job_title:string (R)
start_date:date (R)
daily_or_weekly:string (R)
working_week:float (R)
currency:string (R)
overtime_rate_per_hour:integer (D)
other_deal_provisions:text (O)
box_rental_fee_per_week:integer (R, default value is 0.00)
box_rental_description:string (CR, subject to 'more than 0.00' answer to box
_rental_fee_per_week: integer)
box_rental_cap:integer (CR)
box_rental_period:string (CR)

equipment_rental_fee_per_week:integer (R, default value is 0.00)
equipment_rental_description:string (CR, subject to 'more than 0.00' answer
to equipment_rental_fee_per_week: integer)
equipment_rental_cap:integer (CR)
equipment_rental_period:string (CR)
vehicle_allowance_per_week:integer (R, default value is 0.00)
fee_per_day_inc_holiday:integer (R)
holiday_pay_per_day:integer (C)
holiday_pay_per_week:integer (C)
sixth_day_fee:float (C)
seventh_day_fee:float (C)
additional_notes:text (O)
contractor_details_accepted:boolean

**Comment by JMurphyWeb** [comment]
#78 preventing this from please test

**Comment by JMurphyWeb** [comment]
Conditional requirements still need to be added to this feature

**Comment by jonscottfilm** [comment]
Noticed there are a lot of duplicated 'Job titles' in the offer dropdown. 

Imagine they are in the original sheet Becca made. Some actual duplicates, some slight spelling variations. 

Is it a later priority feature to make Job titles a conditional field, dependent on Department selection, thereby only presenting a shorter, relevant list of job titles?

**Comment by jackcarlisle** [comment]
@jonscottfilm yeah that's something that we need to add to the backlog. We've thought about it and it's definitely something we want to implement down the line

**Comment by jonscottfilm** [comment]
Yup, cool. 

And deal with the duplicates at that point, too?

**Comment by jonscottfilm** [comment]
While I remember this one. Not sure if this warrants a new issue creation?

I went to 'update offer' view. Didn't change anything, hit 'make offer', and it still sent update email to user. 

Any way of stopping this (albeit idiot-behaviour), to avoid confusion for the user? Even if amended fields are highlighted to the user (future fix), NO amended fields will cause confusion.

What's the easiest way to grey-out MAKE OFFER button (which should prob be UPDATE OFFER), _until_ a field has been changed from it's previous written data entry?

**Comment by jackcarlisle** [comment]
@jonscottfilm we're going to look into solving the dropdown issue sooner rather than later. We'll tackle the duplicates as well which is a smaller issue. 

We can change the MAKE OFFER text now as well

**Comment by jonscottfilm** [comment]
Morning @jackcarlisle. By 'dropdown issue', do you mean the conditional list of job titles per department?

**Just out of interest**, does that mean you will create separate tables, one for the job titles of each department? _Long-term_ I wonder if that might help the merging of legitimate new job titles accrued over the course of a project, to a master template from which new projects can run, so Karma continually evolves a master list. _Super long-term,_ these titles might vary between countries, too.

**Comment by jackcarlisle** [comment]
@jonscottfilm yes exactly, we feel like we should look into this now because it could hinder us in future if it goes ignored for too long. 

We're building it in such a way that it can be added to and manipulated quite easily

**Comment by jonscottfilm** [comment]
In 'make offer' flow, I'm thinking 'Target email' should be relabelled as 'Recipients email', to avoid idiot confusion. Agree?
Still works for if sending to an agent.

**Comment by jackcarlisle** [comment]
@jonscottfilm yeah we can change that!

**Comment by jonscottfilm** [comment]
Do you agree? Initially I quite liked target email, but I think it _might_ trip people up.

**Comment by jackcarlisle** [comment]
@jonscottfilm yeah I agree it's a more fool-proof way of displaying it

**Comment by JMurphyWeb** [comment]
There are some changes in review.

@jonscottfilm not entirely related to this issue so see https://github.com/karmaradio/karma/issues/116#issuecomment-303503695

**Comment by jonscottfilm** [comment]
Working. Closed.

**Comment by jonscottfilm** [comment]
Change "Target email" label to "Recipient email"

![image](https://cloud.githubusercontent.com/assets/28431542/26737046/6d5f9fa2-47c0-11e7-981f-31f5f76aff2f.png)
