### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#120]
Notes, not in any priority/logical order:

In conjunction with Styling + Branding #45, which takes it's inspiration from Google Material (https://material.io)

Ultimate goal of design, is clean UX, Good design means good data.

**Make page-widths consistent throughout app, eg:**
1. between Log-in and New Account (narrower), 
2. full-width Project details view, and the dashboard.

**Make fonts (colour & weight) consistent throughout app, eg:**
Field label colour
Field placeholder colour (currently differs between normal text fields, and dropdown fields)
(while we're there, dropdown field container rectangles need same rounded corners)
Colours of committed/focused/empty fields
Format in list views, labels to be normal weight, field data to be bold, and left justified to a new column if possible.

**Logo & icons**
New logo (nearly finalised, Jono has)
Project icon (to be sourced free, or designed)
Profile icon (to be sourced free, or designed)
Offers icon (to be sourced free, or designed)
Colour block banner header on all pages

**Floating field placeholder**
If achievable in the code, this could be easier on the eye: https://material.io/guidelines/components/text-fields.html#text-fields-text-field-boxes

**Misc**
Marking *required fields with asterisk or *optional? (ref: https://uxdesign.cc/design-better-forms-96fadca0f49c)

**Comment by JMurphyWeb** [comment]
@jonscottfilm when you get a minute, could you look into whether you still have outstanding design issues and close/or comment accordingly?

**Comment by jonscottfilm** [comment]
Need overall design tweak cleanup (it's not huge) before end Sp4.

**Comment by jonscottfilm** [comment]
all done, or covered in other issues.
