### ISSUE TITLE
Dashboard Offer Hook-up

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#125]
We still need to hook up our offers to the dashboard

- [x] hook up offers to the dashboard

**Comment by JMurphyWeb** [comment]
@jonscottfilm a contractor's offers should now appear in the dashboard..

**Comment by jonscottfilm** [comment]
Presuming I'm doing it correctly, I get this when I try to view one of My Offers:

![image](https://cloud.githubusercontent.com/assets/28431542/26397784/5d42bf12-406f-11e7-97e3-f0e5b2d16e8c.png)

**Comment by jonscottfilm** [comment]
Hmm, but I can access _some_ offers. This might be just confusion with multiple logins, testing offers sent to each other. I'll start afresh.

**Comment by jackcarlisle** [comment]
At the moment, you can only view offers for projects that you have created. This is something we need to iron out over this sprint!

**Comment by jonscottfilm** [comment]
Right. Albeit an unlikely scenario whereby a PM sends himself a deal offer! (as we are doing in testing)

I imagine 'My offers' will contain only offers received from _other_ projects. 
Offers related to projects which I have created, belong within the Project/offers view. https://karmaradio.herokuapp.com/projects/10/offers

**Comment by jackcarlisle** [comment]
Yes exactly, there's a piece of logic we have to change to ensure that you can see offers from other projects but only the ones given to you

**Comment by jonscottfilm** [comment]
copy.

**Comment by jonscottfilm** [comment]
So, I've tested as it is, and will close in the knowledge you will implement the logic to only show My offers (from 'not' my projects).

Closing.
