### ISSUE TITLE
Start Pack Submission

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#13]
As a contractor,
I want to be able to make my start pack information available once complete,

**Comment by JMurphyWeb** [comment]
We were thinking this would be a side effect of a contractor 'accepting' an offer. Relates to #11

**Comment by jonscottfilm** [comment]
err, true. 
now that accept/reject is at the end of the Start Pack process, I suppose 'accept' means submit, rather than 'continue to complete the start pack'.

**Comment by jonscottfilm** [comment]
Contractor startpack submission can't be viewed by _yet_ by PM. This, along with #10, is one of our moves to S3.

**Comment by JMurphyWeb** [comment]
I have removed the following line from the initial user story issue as it was confusing the focus of the issue:

> So that it can be reviewed by the project manager

This issue will really be completed when the document merge happens. I will remove the time estimate but leave this issue in the Sprint 3 milestone as it is a critical user story to hit.

**Comment by jonscottfilm** [comment]
Works.

Keeping open, and in BL because this is next phase of permitted project users viewing contractor data (not in merged contracts), and using/copying for other functions (messaging, sending other forms, phoning etc)

**Comment by jonscottfilm** [comment]
Closing. Will be covered by Export in Phase 2.
