### ISSUE TITLE
Startpack validation - Required fields for startpack

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#132]
As a contractor,
I can only accept an offer if I have filled out the required fields in my personal settings (start-pack)

We need to dynamically determine which fields are required depending on the offer that has been made. 

@jonscottfilm  we'll need some assistance here

**Comment by JMurphyWeb** [comment]
> mix phoenix.gen.html Startpack startpacks
gender:string
middle_names:string
aka:string
screen_credit_name:string
mobile_tel:string
emergency_contact_name:string
emergency_contact_relationship:string
emergency_contact_tel:string
date_of_birth:string
place_of_birth:string
country_of_legal_nationality:string
country_of_permanent_residence:string
passport_number:string
passport_expiry date:string
passport_issuing country:string
full_name_as_on_passport:string
passport_url:string
primary_address_1:string
primary_address_2:string
primary_address_city:string
primary_address_postcode:string
primary_address_country:string
primary_address_tel:string
agent?:string
agent_name:string
agent_company:string
agent_address:string
agent_tel:string
agent_email_address:string
box_rental_value:string
box_rental_url:string
equipment_rental_value:string
equipment_rental_url:string
vehicle_make:string
vehicle_model:string
vehicle_colour:string
vehicle_registration:string
vehicle_insurance_url:string
national_insurance_number:string
vat_number:string
p45_url:string
for_paye_only:string
student_loan:string
...
schedule_d_letter_url
loan_out_company_registration number
loan_out_company_address:text
loan_out_company_cert_url
method_of_payment
bank_name
bank_address:text
bank_account_users_full_name
bank_account_number
bank_sort_code
bank_iban
bank_swiftcode
agent_bank_name
agent_bank_address
agent_bank_sort_code
agent_bank_account_number
agent_bank_account_name
agent_bank_account_swift_code
agent_bank_account_iban

**Comment by JMurphyWeb** [comment]
@jonscottfilm could you go through the spread sheet and:
- remove mentioned duplicates
- remove types Numbers/Numbers only and use only Number
- make all phone numbers into type `text`
- create a new type called `string`
- type text is a `text area`, type `string` should be a 1 line input so I think some of the `text` inputs need to be changed to `string`s

![screen shot 2017-05-24 at 12 33 49](https://cloud.githubusercontent.com/assets/12638261/26401421/c4918bae-407d-11e7-810e-0d354c9138a6.png)


And please take close look at the above fields & types that we have determined in the comment above.

**Comment by JMurphyWeb** [comment]
@jonscottfilm there are the following fields with `agent` attached:

>agent_deal?:boolean
agent_name:string
agent_company:string
agent_address:string
agent_tel:string
agent_email_address:string
agent_bank_name:string
agent_bank_address:string
agent_bank_sort_code:string
agent_bank_account_number:string
agent_bank_account_name:string
agent_bank_account_swift_code:string
agent_bank_account_iban:string

Are all of the above fields required only if the contractor selects that the deal will be through an agent (represented in the `agent_deal?` field)

**Comment by jonscottfilm** [comment]
understood.

**Comment by jonscottfilm** [comment]
correct re agent.

**Comment by JMurphyWeb** [comment]
@jonscottfilm or @beccacca 

These conditions sound like a fair bit of work and are currently the only conditions we are not feeling sure about. I think priority and more explanation is needed.

![screen shot 2017-05-24 at 12 52 02](https://cloud.githubusercontent.com/assets/12638261/26401937/0f7a8f74-4080-11e7-954c-51e86741b349.png)

**Comment by jonscottfilm** [comment]
Field data types correct, per priority 1 & 2.

**Comment by JMurphyWeb** [comment]
@jonscottfilm our field data types or the ones on the spreadsheet?

I feel like these should be strings?

![screen shot 2017-05-24 at 14 04 56](https://cloud.githubusercontent.com/assets/12638261/26404476/0fd9fa4a-408a-11e7-9fc7-751e13e7924f.png)

**Comment by jonscottfilm** [comment]
I would say where we can, we should control the data entry. e.g. dropdown for gender. No?
**Comments in bold**

mix phoenix.gen.html Startpack startpacks
gender:string - **should be Dropdown: Male/Female/Other/prefer not to say**
middle_names:string
aka:string
screen_credit_name:string
mobile_tel:string **text (per your instruction above)**
emergency_contact_name:string
emergency_contact_relationship:string
emergency_contact_tel:string **text (per your instruction above)**
date_of_birth:string **I currently have dates as 'Date' in the spreadsheet. _Want me to change?_**
place_of_birth:string
country_of_legal_nationality:string
country_of_permanent_residence:string
passport_number:string
passport_expiry date:string
passport_issuing country:string
full_name_as_on_passport:string
passport_url:string
primary_address_1:string
primary_address_2:string
primary_address_city:string
primary_address_postcode:string
primary_address_country:string
primary_address_tel:string **text (if needed at all actually. Landline telephone?!)**
agent?:string **Dropdown: Yes/No**
agent_name:string
agent_company:string
agent_address:string
agent_tel:string **text**
agent_email_address:string
box_rental_value:string **number (2 decimal places, thousands comma separator)?**
box_rental_url:string
equipment_rental_value:string **number (2 decimal places, thousands comma separator)?**
equipment_rental_url:string
vehicle_make:string
vehicle_model:string
vehicle_colour:string
vehicle_registration:string
vehicle_insurance_url:string
national_insurance_number:string
vat_number:string
p45_url:string
for_paye_only:string
student_loan:string
...
schedule_d_letter_url
loan_out_company_registration number **string**
loan_out_company_address:text
loan_out_company_cert_url
method_of_payment **Delete**
bank_name **string**
bank_address:text
bank_account_users_full_name **string**
bank_account_number **string**
bank_sort_code **string**
bank_iban **string**
bank_swiftcode **string**
agent_bank_name **string**
agent_bank_address **text**
agent_bank_sort_code **string**
agent_bank_account_number **string**
agent_bank_account_name **string**
agent_bank_account_swift_code **string**
agent_bank_account_iban **string**

**Comment by jonscottfilm** [comment]
Sorry @JMurphyWeb. Both yours & on the sheet now, inc the IBAN one's I had missed :)

**Comment by JMurphyWeb** [comment]
yup you have an outdated copy.

I think almost all `text` inputs should be `string`s. Text inputs are larger and are currently used for the bank address and the loan out company address.

**Comment by jonscottfilm** [comment]
But I'm editing the Google sheet which you're looking at...?
Text for anything multi-line.
Filtered for only Priority 1 and 2, and for Onboarding.

Are you looking beyond that?

**Comment by JMurphyWeb** [comment]
No.

**Comment by jackcarlisle** [comment]
For the current implementation we are going to have the swift and IBAN fields always visible, but not required. This will be coupled with instructions on when to fill them out based on whether or not their bank is from the UK.

**Comment by JMurphyWeb** [comment]
@jonscottfilm @beccacca:

The following fields can be left out of the form for now? at least never required as the conditions can never be true (contract type = loan out or loan out general)

> Loan-Out Company Certificate of Incorporation,
Loan-Out Company Registration Number,
Loan-Out Company Address

**Comment by jonscottfilm** [comment]
Becca isn't seeing Github comments. Told her re IBAN on Slack. This is OK for now, yes.

Err, I took those fields of yours, from this Slack link #132https://engineonboard.slack.com/archives/C5A4S3FRS/p1495623084468812, to _this_ #132 issue... 
Do you need me to go over it again, now the updated list is edited in....? ;))

Re Loan-Out fields - keep in the form please, as optional, because you're right, can't be determined as 'required', or certainly not until they answer/input into 'Loan Out Company Name'........

**Comment by JMurphyWeb** [comment]
sorry multiple sources is getting confusing.. no need to do any more on this, think we are good

**Comment by jonscottfilm** [comment]
OK.

You note: IBAN is ok, and keep LoanOut fields in please.

**Comment by JMurphyWeb** [comment]
OK.

agent telephone number is conditional on deal through agent or no?

**Comment by JMurphyWeb** [comment]
btw some of the required fields on the spreadsheet are listed as `y` but they are actually conditionally required, which should be covered in a different column (i think)

**Comment by jonscottfilm** [comment]
You're right. These should be conditional, based on 'Deal direct, or through Agent?'

Agent Name
Agent Company
Agent Address
Agent Tel
Agent Email Address

**Comment by jonscottfilm** [comment]
There is a conditional column and a required column already.
Give us an example of which fields?

**Comment by JMurphyWeb** [comment]
agent tel is required = `y` i think

**Comment by jonscottfilm** [comment]
right, and should be conditional now, got it.

**Comment by jonscottfilm** [comment]
Do we presume that if a field is conditional, it's also then required? We don't want users skipping over those fields.

**Comment by JMurphyWeb** [comment]
see here for the basic requirements: https://github.com/karmaradio/karma/issues/138#issue-231074904 please make any relevant comments on that issue too. thaanks

**Comment by JMurphyWeb** [comment]
@jonscottfilm this is closeable now. Any validation issues can be discussed in specific validation issues.
