### ISSUE TITLE
Contractor must create account with correct email address

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#133]
As a contractor, I need to create my Karma account with the same email address as the one that received the original offer. 

When clicking on the 'create account' link in the email, the user's email address should be pre-filled and non editable.

@jonscottfilm bringing this thought to your attention for prioritisation, adding to the backlog for now.

**Comment by jonscottfilm** [comment]
Copy.
We will brief PM's to collect the desired address during the  deal telephone call. 
Users use different emails for different purposes and they won't necessarily be aware of the additional use of a Karma account (which they'll use forever!).

**Comment by jonscottfilm** [comment]
Ah, my apologies, this explains the different format in the 'edit offer' view, too.
(ref https://github.com/karmaradio/karma/issues/100#issuecomment-303755651)

![image](https://cloud.githubusercontent.com/assets/28431542/26414682/d582a6e4-40a7-11e7-99eb-8ddd58903596.png)

**Comment by JMurphyWeb** [comment]
@jonscottfilm can you add a priority please?

**Comment by jonscottfilm** [comment]
Offer/startpack flow will fail without this, so essential to Sp4.

**Comment by jonscottfilm** [comment]
ooh, testing now...

**Comment by jonscottfilm** [comment]
Works, but interestingly, my autocomplete tried to fill my surname with my email...

![image](https://user-images.githubusercontent.com/28431542/27904883-2067fc54-6236-11e7-81ef-fd9ab8d91520.png)

And, when I hit 'create account', it presumed that the email field is blank (albeit pre-filled), and threw an error.

**Comment by jonscottfilm** [comment]
Working! Closing.
