### ISSUE TITLE
Conditional Changeset - box_rental, equipment, agent

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#136]
We need to create a changeset for the startpack that checks if there has been a request for box rental, equipment and if the contractor uses an agent, and then make the relevant fields required (or not). 

- [x] build the conditional changeset for box rental, equipment and agent

**Comment by JMurphyWeb** [comment]
@jonscottfilm this is an old issue. Closable if startpack validation works for box_rental, equipment, agent fields

**Comment by jonscottfilm** [comment]
Working. Closing. Good job!

(think I might have discovered 2 more file upload fields: Driving Licence and Proof of Vehicle Insurance for Business Use - conditional to IF getting vehicle allowance.
@beccacca ?

**Comment by JMurphyWeb** [comment]
@jonscottfilm issue and prioritise please (remember to link to issues/comments when you do using the `#` so i don't keep asking you to... 😄
