### ISSUE TITLE
validate startpack - agent related fields

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#142]
In order to accept an offer, you we need to adapt the required fields depending on whether the deal is through the agent or not

**Comment by JMurphyWeb** [comment]
Agent required fields are:
```
    [ :agent_name,
      :agent_company,
      :agent_address,
      :agent_tel,
      :agent_email_address,
      :agent_bank_name,
      :agent_bank_address,
      :agent_bank_sort_code,
      :agent_bank_account_number,
      :agent_bank_account_name,
```

Note that IBAN and swift_code are not required.

**Comment by JMurphyWeb** [comment]
This can be tested by ticking the agent deal? checkbox and leaving one of the [required fields](https://github.com/karmaradio/karma/issues/142#issuecomment-304007358) blank in the startpack and the contractor should not be able to accept the offer.

Similarly if the agent deal is not checked, then the data should be valid even if the agent fields are not filled

**Comment by jonscottfilm** [comment]
Working.

I kinda felt the 'create/edit offer' needed the 'deal through agent' checkbox, too. Maybe we ditched that for MVP for now, due to not having option for 3rd party to complete someone's startpack?
Food for thought.

**Comment by jackcarlisle** [comment]
How would the PM know if the person they were sending the offer to dealt through an agent?

**Comment by jonscottfilm** [comment]
Through the deal phone call.

**Comment by jonscottfilm** [comment]
Working. Closing.

Created #335.
