### ISSUE TITLE
Forgotten Password

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#15]
As a contractor/project manager,
I want to be able to create a new password,
If I've forgotten my current one

**Comment by JMurphyWeb** [comment]
Add this forgot password link to login and personal settings view

**Comment by JMurphyWeb** [comment]
@jackcarlisle when you get onto this, let's have a chat about implementation of the reset password part

**Comment by jackcarlisle** [comment]
@JMurphyWeb ok sounds good

**Comment by jonscottfilm** [comment]
Hit 'send reset email' takes user to 'page not found'.
Tried with more than one login.

**Comment by jonscottfilm** [comment]
Do we want people to be unable to use a previous password in 'password reset' flow? Currently you _can._ It's easier for people, but is it additional security to have to create an entirely new password?

**Comment by jackcarlisle** [comment]
@jonscottfilm I think again this might be a stretch goal that could be added to the backlog with a lower priority. We can change the priority if this is something you would especially like, ahead of other functionality

**Comment by jonscottfilm** [comment]
Nope, back of the pile. Just thought I'd ask the question in case you'd intended for it to already be in place.
👍

**Comment by jonscottfilm** [comment]
Working.
