### ISSUE TITLE
Make the width of the app container consistent throughout the app

### ISSUE THREAD

**Issue by nogainbar** [karmaradio/karma#155]
- Decide on a max width which would suit the various views of the app
- Make sure that there is consistency throughout the app with this max width

suggestion: a happy medium between project list page and single project view page 

* will also affect width of header

**Comment by nogainbar** [comment]
Hey @jonscottfilm, 

Attached are the screen grabs of changes to width that I have made to the containers.
The main container is a bit larger and the forms container is a bit smaller that main but consistent throughout. 
Also you can see the view on mobile.
Let us know if you are happy with these? :)

<img width="1440" alt="screen shot 2017-05-30 at 14 30 05" src="https://cloud.githubusercontent.com/assets/12494147/26585899/7bb9d342-4545-11e7-8640-887dbe3a84c7.png">
![Uploading Screen Shot 2017-05-30 at 14.30.09.png…]()
![Uploading Screen Shot 2017-05-30 at 14.30.12.png…]()
![Uploading Screen Shot 2017-05-30 at 14.30.21.png…]()
![Uploading Screen Shot 2017-05-30 at 14.33.16.png…]()
![Uploading Screen Shot 2017-05-30 at 14.33.19.png…]()
![Uploading Screen Shot 2017-05-30 at 14.33.25.png…]()
![Uploading Screen Shot 2017-05-30 at 14.33.28.png…]()

**Comment by jonscottfilm** [comment]
Looks good! 
Seems like the additional screengrabs didn't load...?

**Comment by jonscottfilm** [comment]
ah, there they are!

**Comment by jonscottfilm** [comment]
👍 
(presuming the icon will be moved away from left edge in mobile :))

**Comment by nogainbar** [comment]
@jonscottfilm it will definitely will! but was thinking to do that when I was doing the header issue. I did see that its low priority.. see comments on the issue #162

**Comment by jonscottfilm** [comment]
Loving the consistent width now. Makes navigating much nicer.

Closing...
