### ISSUE TITLE
Input fields- focus state

### ISSUE THREAD

**Issue by nogainbar** [karmaradio/karma#156]
Implement a focus state for input field so that the user know which field they are filling out and navigate the form better

suggestion: karmaradio's indigo border color around the field when focused

**Comment by nogainbar** [comment]
@jonscottfilm here is the border radius focus state for input field so that the user know which field they are filling out:

<img width="1434" alt="screen shot 2017-05-31 at 15 20 33" src="https://cloud.githubusercontent.com/assets/12494147/26636500/e4dbab0a-4614-11e7-8bc5-14c12a73f0aa.png">
<img width="1440" alt="screen shot 2017-05-31 at 15 21 01" src="https://cloud.githubusercontent.com/assets/12494147/26636506/e944219a-4614-11e7-9201-4761b780dae3.png">

**Comment by jonscottfilm** [comment]
Love it!

And the 'Already have an account's reposition!

**Comment by nogainbar** [comment]
this will be overwritten if we apply the floating label system, unless we go for focus and not animated underline (material style)

**Comment by JMurphyWeb** [comment]
done, closing
