### ISSUE TITLE
Colour palette 

### ISSUE THREAD

**Issue by nogainbar** [karmaradio/karma#159]
To define the palette so that we have:

- Primary colour (Indigo, dark and light)
- Accent colour
- Error colour (a red that will go nicely with the palette)
- success colour (suggesting a greenish colour that will go nicely with the palette)
- App's black (suggesting my favourite black which is a very dark grey #333333)

@jonscottfilm I will be waiting to hear back from you with a selection, if you would like to use https://coolors.co/ and send me perhaps three combinations I am more than happy to look at those and feedback some thoughts :)

**Comment by jonscottfilm** [comment]
Hey @noga. Agree with all above.
Will get you 3 palettes over the weekend for sure.

**Comment by nogainbar** [comment]
Attached is the palette:
![karmaradio_palette](https://cloud.githubusercontent.com/assets/12494147/26543721/e62017fe-4456-11e7-8619-e90e88482a17.png)

**Comment by jonscottfilm** [comment]
Is this testable - not all in place yet, is it? Forgive me if it is!

**Comment by nogainbar** [comment]
@jonscottfilm the new colours are not applied everywhere yet but I think that we can close the issue if we fulfilled all the points mentioned above namely decision on-

- Primary colour (Indigo, dark and light)
- Accent colour
- Error colour (a red that will go nicely with the palette)
- success colour (suggesting a greenish colour that will go nicely with the palette)
- App's black (suggesting my favourite black which is a very dark grey #333333)

**Comment by jonscottfilm** [comment]
I see.

OK - my only _feeling_ right now would be the error red needs to be _just_  a tiny bit more red... :), and likewise success green. But let's live with it for a while.

Closing!
