### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#16]
As a contractor/project manager,
I want to verify my email when registering,
So that my offers are more secure

**Comment by JMurphyWeb** [comment]
@jackcarlisle I was just thinking about the verification flow. I think we need to set up a 're-send verification email' as well? if a user deletes the original email, they will not be able to create another account.

An alternative option would be to send the verification email again if they try to log in but are not yet verified. Thoughts?

**Comment by jackcarlisle** [comment]
@JMurphyWeb Yeah I think this is something that we'll have to think about. I would be more inclined to go for a 're-send verification email' flow. We can discuss.

**Comment by JMurphyWeb** [comment]
Agreed. better UX. Possible flow:

We can use the login page, if `@current_user && !@current_user.verified` , ask them to enter their email address, and present a new button 're-send verification email'

An unverified user attempts to create account again -> redirect to above login view, put flash "you need to verify your email address"
An unverified user attempts to log in -> same flow as above

**Comment by jackcarlisle** [comment]
Yeah that sounds good!

**Comment by jackcarlisle** [comment]
@jonscottfilm assigning to you for testing. Please comment below if there are any bugs with this flow and we will take a look. Otherwise if you're happy with the implementation, please close this issue.

**Comment by jonscottfilm** [comment]
Email verification notification should be broken up slightly to be more palatable:

'A verification email has been sent to jonscottfilm@gmail.com. 

You must click the link in the email before you can gain full access. 

If you need a new verification link, follow the log in flow.'

**Comment by JMurphyWeb** [comment]
@jonscottfilm when you are done testing an issue, if there is a bug, please try to remember to:
- remove your assignment
- add the bug label 

Having said that, this is more of an enhancement than a bug... 😕

**Comment by jonscottfilm** [comment]
Right, gotya.

OK, valid bug, I think.

Once email is verified, it currently navigates user to logged-in application. Nice and convenient it's true, but I wonder if they should then be prompted to log-in, with said verified email? Is that a further step of security, or just a pain in the neck?

**Comment by JMurphyWeb** [comment]
That would go against the standard for creating a new account with email verification. It is something  that can be added, but would warrant a new prioritised issue. Make sure you link to this issue if you want to create a new one.

**Comment by jonscottfilm** [comment]
Ok. Will consider if required, at a later date.

Closing issue.
