### ISSUE TITLE
Header: design

### ISSUE THREAD

**Issue by nogainbar** [karmaradio/karma#162]
Look into the design of the header

- Make header consistent and in context of the new max width of the app #155 
- Look into small redesign tweaks
- consider sticky header or not and if so where (currently I am not sure about this idea in terms of UX but we can try and see)
- make header responsive - hamburger menu

**Comment by nogainbar** [comment]
@jonscottfilm I see that this has low priority, I am wondering if it does however need to be of higher priority because -

- I would like to give time to make it work nicely with the new width of the general app
- Now that we have three menu items, we were talking about perhaps making a mobile version of it with an hamburger menu (that would fix issue #179)

**Comment by nogainbar** [comment]
@jonscottfilm or a quick fix can also be done just to make the logo fit nicely with new width :)

**Comment by jonscottfilm** [comment]
Don't worry about quick fix. 
Hamburger menu would be ideal - that would be for mobile only, right?

**Comment by nogainbar** [comment]
@jonscottfilm Yea, that would be for mobile indeed :)

would you think then that we should bring it up to a higher priority in the list?

**Comment by nogainbar** [comment]
done and merged. 
@jonscottfilm would you like to check that you like the new header? make sure you look it at responsive as well :)

**Comment by nogainbar** [comment]
@jonscottfilm i just saw that I havnt changed the app container accordingly, apologies, i will push this change now and THEN this will be ready to test :)

**Comment by jonscottfilm** [comment]
Gotya! :) Yeah, icon not loading for me.

**Comment by nogainbar** [comment]
oh really? hmm.. interesting! @jackcarlisle @JMurphyWeb suggestions on why could that be?

**Comment by jonscottfilm** [comment]
No burger menu icon, on mobile. 
Menu expands, but doesn't fully collapse:
![image](https://cloud.githubusercontent.com/assets/28431542/26753034/584a546e-4855-11e7-97cf-7fe9e05aef36.png)

**Comment by nogainbar** [comment]
@jonscottfilm could you look at it now again please (if you have time of course..)

**Comment by jonscottfilm** [comment]
Sorry, prob should've posted this #278 here.

Love the new header, and burger menu. Think I might need to give you a tweaked logo.

Think we'll know if colours are working once we have footer in place, and white project and offer tiles with the coloured outlines/shapes or icons as status indicators.

**Comment by nogainbar** [comment]
indeed! all coming at ya soon.. :)

re logo- I agree, no shadows perhaps? I think I would tend to go for the flat look overall...

**Comment by jonscottfilm** [comment]
Flat look overall might be the way to go. Perhaps very very slight bottom and right drop shadow on project/offer cards, for slight separation?

I'll send you flat logos.

**Comment by jonscottfilm** [comment]
Working, bar: 

Burger issue #278 

Startpack and Offer views are one width. Profile and Dashboard are just _slightly_ wider, causing a jump when navigating between.

**Comment by jackcarlisle** [comment]
@jonscottfilm would you prefer the Startpack and Offer views be the same width as the Profile and Dashboard?

**Comment by jonscottfilm** [comment]
https://github.com/karmaradio/karma/issues/162#issuecomment-308780035 yes please.

Mobile UX is like that, think desktop should be same. Long-term we can look at styling differentiation between project and profile, perhaps.

**Comment by JMurphyWeb** [comment]
@jonscottfilm it would be nice to close this milestone to ensure it's issues don't get forgotten, unless you would like to keep it open. Would you mind if we moved all these issues to `backlog`? if not we can keep this milestone here.
