### ISSUE TITLE
Dividers in big forms - 

### ISSUE THREAD

**Issue by nogainbar** [karmaradio/karma#163]
Start applying the 'one thing at a time' rule to the big forms by adding dividers, according to content sections making the current layout more accessible to the user.

This would precede the future work of dividing the big forms into separate pages.

@jonscottfilm did you send me the document that we talked about where I can clearly see the division of sections according to subject?

fields should go up within the 'Offer details' section.

Fee per day including holiday 
Sixth day fee multiplier 
Seventh day fee multiplier 
Additional notes

'Locations', 'Holiday rate', 'Additional notes' up the form into 'Project details' (like in the project details view)

**Comment by nogainbar** [comment]
@jonscottfilm I have added all the dividers in both forms, just to give you a sense, im adding screen grabs here but this cannot be merged until tomorrow morning. 
looks good!
:) 
<img width="1440" alt="screen shot 2017-05-31 at 21 42 47" src="https://cloud.githubusercontent.com/assets/12494147/26653152/28c8f90a-464a-11e7-928d-f11429e42f54.png">
<img width="1440" alt="screen shot 2017-05-31 at 21 42 51" src="https://cloud.githubusercontent.com/assets/12494147/26653154/28d13084-464a-11e7-8186-664fcadb2721.png">
<img width="1440" alt="screen shot 2017-05-31 at 21 42 54" src="https://cloud.githubusercontent.com/assets/12494147/26653153/28c9df78-464a-11e7-9951-1aaeae405543.png">

**Comment by nogainbar** [comment]
Also changed the positions of the fields as you requested :)

**Comment by jonscottfilm** [comment]
Looking good!

As and when we have floating labels working, we should have a good check over all font weights and colours to balance things out. Same time, also check wording of all labels, placeholders and error texts, as I see one or two are incorrect here, eg, _needing_ box/equipment is not quite right.

We're getting there!

**Comment by nogainbar** [comment]
add margin and increase font size in the divider's header (mb4 and 2rem)

**Comment by jonscottfilm** [comment]
Working! Closing!

Larger font section headings works well.
