### ISSUE TITLE
Travis CI + CodeCov + Pre-commit

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#18]
There are a couple of chores that we need to do to get the project up and running before we can get started on the user stories:

- Code coverage
- Pre-commit hook
- Continuous Integration

**Comment by JMurphyWeb** [comment]
I am adding permissions for travis now

**Comment by JMurphyWeb** [comment]
Added travis and codecov webhook

**Comment by jackcarlisle** [comment]
Closing, all implemented
