### ISSUE TITLE
Box & Equipment checkbox update 

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#182]
If PM updates offer to _remove_ Box & Equipment rentals, by un-checking checkbox..

_Can_ the contents of remaining Box & Equipment fields (fee per week, cap, period) by deleted accordingly?

**Comment by jackcarlisle** [comment]
@jonscottfilm by contents do you mean the list of information within the offer view page?

**Comment by jonscottfilm** [comment]
Just the information relating to the 'box' which has been removed. Eg box cap, box rental period.

**Comment by jonscottfilm** [comment]
Working! Yay!
