### ISSUE TITLE
Logo clipping

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#186]
New logo is being clipped slightly by square container, in _smaller (zoomed-out)_ views. 

Also - higher res version of logo will be shared on Slack.

**Comment by jackcarlisle** [comment]
@jonscottfilm can you upload a screenshot of this?

**Comment by jonscottfilm** [comment]
Very small, bottom and right hand side. Potentially could be resolved as part of #179..?

![image](https://cloud.githubusercontent.com/assets/28431542/26587065/24239394-4549-11e7-8d96-7fad42af19ec.png)
