### ISSUE TITLE
dashboard view - projects

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#19]
As a user,
I can see a summary of my projects on a dashboard.  This will act as the user's "home page".

**Comment by JMurphyWeb** [comment]
I am going to spend a pommy getting a basic dashboard together.

**Comment by JMurphyWeb** [comment]
Rather than adding a new route I have replaced the `page` files with `dashboard`

**Comment by jonscottfilm** [comment]
Before any project has ever been created, font in this dashboard view is too thin to be legible. Still needs differentiation from 'create one?' as you have it, though.

![image](https://cloud.githubusercontent.com/assets/28431542/26244227/cd5b4a90-3c86-11e7-8b60-ce41eb7e9250.png)

**Comment by jonscottfilm** [comment]
Retested. Still appears as fine font. Leave it to fix in design phase of sprints. I'll create an issue.

**Comment by JMurphyWeb** [comment]
@jonscottfilm I am removing the bug label and assigning you to this issue as there is a styling one #90 

Feel free to undo this if there is something else that we are missing.

**Comment by jonscottfilm** [comment]
Agreed. Tested, all good. Closed.
