### ISSUE TITLE
Offer response email notifications

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#191]
As a project manager,
I want to receive an email notification when a contractor has responded (accepted/rejected) to an offer,
So that I can act accordingly

links to #11

**Comment by jonscottfilm** [comment]
Not sure how I accept an offer.

Will write email template.

**Comment by jackcarlisle** [comment]
Once you have completed all of the necessary fields in your startpack that the offer requires, two buttons will appear in the offer details page, accept & reject.

**Comment by jonscottfilm** [comment]
Understood. Will test now.

**Comment by jonscottfilm** [comment]
Llinked to / duplicated in #23?
https://github.com/karmaradio/karma/issues/23#issuecomment-305862590

**Comment by jonscottfilm** [comment]
I've never received a PM email saying, contractor has accepted/rejected.

**Comment by JMurphyWeb** [comment]
@jonscottfilm now working

**Comment by jonscottfilm** [comment]
Working! Closing.
