### ISSUE TITLE
PM Upload Contracts, additional forms & other documents

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#192]
As a PM,
I can upload project specific documents
So the contractor can read them and the application can merge data with them.

**Comment by JMurphyWeb** [comment]
@jonscottfilm document types are:
Contract 2 uploads for now (there will be up to 4 types of contract in the future?)
Additional forms 1 upload for now(for now we can upload these as 1 large PDF)
Static documentation/project rules/terms etc.. 1 upload for now

**Comment by jonscottfilm** [comment]
@JMurphyWeb 

- Contract - 2 uploads for now (there will be up to 4 types of contract in the future?)
**I've known some shows to have up to 9........  Yes, 2 for now, Loan Out & Direct Hire (covers both Sched D and PAYE)**

- Additional forms - 1 upload for now(for now we can upload these as 1 large PDF)
**Hmm - how to handle forms which are based on conditional fields, eg: Box Rental, Equipment Rental, Vehicle Allowance... IF these were individual uploads, then based on those conditions, rules could determine whether they got Webmerged to PDF... We _could_ just leave the blank forms in there, it's just a bit messy, and if people filled out Box Rental forms for themselves, i.e. they weren't part of the offer, a form could get signed off**

- Static documentation/project rules/terms etc.. - 1 upload for now
**Should be fine - ooh, any luck researching being able to view pre-written PDF bookmarks in the web viewer? At least that way, the user can easily navigate through 1 big document of lots of individual documents...**

**Comment by jackcarlisle** [comment]
https://docs.google.com/spreadsheets/d/1psE1h-j75fHEtzuhlYIY2IfQyvIktKFSpIYsh8BkIs8/edit?usp=sharing

**Comment by jonscottfilm** [comment]
@jonscottfilm will add 'Daily' contracts to the spreadsheet

**Comment by jonscottfilm** [comment]
Working.
(First bit, as we know: As a PM, I can upload project specific documents)
