### ISSUE TITLE
startpack validation - vehicle allowance

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#194]
If vehicle allowance in the offer is more than 0, the startpack will have 5 additional vehicle related required fields.
```
:vehicle_make,
:vehicle_model,
:vehicle_colour,
:vehicle_registration,
:vehicle_insurance_url
```
linked to #132

**Comment by jonscottfilm** [comment]
Will this still mean that we still capture vehicle details for all vehicle-owning contractors, regardless of whether they get vehicle allowance or not?

**Comment by jackcarlisle** [comment]
They will have the option to input their vehicle details even if they don't get vehicle allowance. We could add a checkbox that's checked in the startpack saying something like "I bring my own car to set" which will mean that they have to fill out their car details before submitting their startpack.

**Comment by jonscottfilm** [comment]
OK. Yes, it can't be a required field, but we need to prompt people to input. So, I guess a checkbox... but is that the same as having optional fields for entering car details, and them skipping over it? What is the repercussion of not giving car details, being denied parking?? Unlikely, in the absence of our 'Security Pass' feature :).

So long as we can get _everyone's_ car details, right now that's the important thing.

**Comment by jonscottfilm** [comment]
working
