### ISSUE TITLE
Account creation

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#2]
As a contractor/project manager,
I want to be able to create an account,
So that I can login to the application

**Comment by JMurphyWeb** [comment]
basic tests, schema, model, controller, view and templates in place.

Next I want to build out the registration changeset so we are correctly hashing the password

**Comment by JMurphyWeb** [comment]
When testing the registration changeset, I wanted to test the validation functionality with data:

```elixir
@invalid_account_creation %{email: "testtest.com", first_name: "Joe", last_name: "Blogs", password: "12345"}
```


```elixir
  test "registration changeset with invalid password and email" do
    changeset = User.registration_changeset(%User{}, @invalid_account_creation)
    %{errors: [password, email]} = changeset

    refute changeset.valid?
  end
```

Which returns the following changeset:
```elixir
#Ecto.Changeset<action: nil,
 changes: %{email: "testtest.com", first_name: "Joe", last_name: "Blogs",
   password: "12345"},
 errors: [password: {"should be at least %{count} character(s)",
   [count: 6, validation: :length, min: 6]},
  email: {"has invalid format", [validation: :format]}], data: #Karma.User<>,
 valid?: false>
```

I wasn't sure of the best way to test that the password and email were sitting in the errors

**Comment by JMurphyWeb** [comment]
I ended up testing using Keyword.has_key?:
```elixir
    # ensure email and password have failed
    %{errors: errors} = changeset
    Keyword.has_key?(errors, :password)
    Keyword.has_key?(errors, :email)
```

**Comment by JMurphyWeb** [comment]
a nice little article on testing: https://medium.com/@diamondgfx/testing-validations-in-elixir-and-ecto-677bd8a071a1

**Comment by jackcarlisle** [comment]
Looks nice!

**Comment by JMurphyWeb** [comment]
Ended up with the following test:
```elixir
  test "changeset is invalid if email is used already" do
    changeset = User.registration_changeset(%User{}, @valid_attrs)
    # insert a user
    Karma.Repo.insert!(changeset)
    # attempt to insert a user with same email
    assert {:error, changeset} = Repo.insert(changeset)
    assert {"has already been taken", _} = changeset.errors[:email]
  end

```

**Comment by JMurphyWeb** [comment]
pr in review.

**Comment by JMurphyWeb** [comment]
worth also linking this to #3 terms and conditions issue

**Comment by jonscottfilm** [comment]
Does it feel more natural for the order of fields to be:

1. First Name
2. Last Name
3. Email (moved from first position to third)
4. Password 
(**Password help text should say**: 
'password _for_ _engine_' - idiots get confused and put their email password in. 
Also should say, 'password must contain 'minimum of 8 cbetharacters, inc. a capital, symbol and number)

Terms and conditions. Awkward line break. Any way of getting it on one line? OR line break between 'the' and 'terms'.
Can checkbox only be clickable once terms have been viewed? Or put the checkbox at bottom of terms page?
And reduce size of checkbox. Remove surrounding line.

I realise some of this might belong in new design issues.

**Comment by jonscottfilm** [comment]
Interestingly, my Chrome autofill, actually inserts my email address into the 'Last name' field anyway, not 'email' field.

![image](https://cloud.githubusercontent.com/assets/28431542/26243742/d47498ba-3c84-11e7-8ac8-9ba3d1f35387.png)

**Comment by jonscottfilm** [comment]
Terms & Conditions will be ready in 2-3 weeks. 

BTW - likely we will have 2 sets of T&C's. One for the contractor, and one for the project. (re temp sharing/storing of contractor data). Guess that means we will need a T&C agreement with checkbox as part of the 'project creation' flow. I'll create an issue.

**Comment by JMurphyWeb** [comment]
Think the autofill can be fixed by rearranging the order of the inputs. Seems like a valid bug.

**Comment by jonscottfilm** [comment]
In testing the app, using multiple log-ins, I encountered the 'you're already logged-in!' notification. 

A user _might_ have multiple log-ins to Karma (future example, an agent managing the profile of multiple clients).

The 'already logged in' should state 'logged in as j****t@gmail.com', and to 'log-out here' BUTTON, to log in as another user'...

**Comment by JMurphyWeb** [comment]
@jonscottfilm alternatively we could put the user's name in the nav (which could link to their currently private profile)

**Comment by JMurphyWeb** [comment]
I am going to fix this: https://github.com/karmaradio/karma/issues/2#issuecomment-302666074 now.

**Comment by JMurphyWeb** [comment]
<img width="291" alt="screen shot 2017-05-19 at 14 31 53" src="https://cloud.githubusercontent.com/assets/12638261/26249883/1236effc-3ca0-11e7-9f26-9150e538ec10.png">


Order has sorted out chrome autofill

**Comment by jonscottfilm** [comment]
💪

**Comment by JMurphyWeb** [comment]
<img width="286" alt="screen shot 2017-05-19 at 15 06 39" src="https://cloud.githubusercontent.com/assets/12638261/26251387/f83dd322-3ca4-11e7-8f21-89afc75371f1.png">

The following is done but needs to be merged.
- checkbox resized
- Additional info on password added (not password strength)

Regarding other changes requested in this issue, I deem them nice to haves/enhancements and therefore worthy of new (prioritised) issues 🇬🇲

**Comment by JMurphyWeb** [comment]
@jonscottfilm back over to you 😸

**Comment by jonscottfilm** [comment]
Think helper text should be below field, per design guidelines, but agreed this is something, plus the password strength hint, that we can cover in new issues in future sprints.

**Comment by jonscottfilm** [comment]
There's still some sort of shadow line above the checkbox.

Other than that, I think we can close this issue.

**Comment by jonscottfilm** [comment]
CREATE button should be greyed-out until T&C's are agreed to.
Error message 'something went wrong' should highlight field in error, in this case, unchecked T&C's box.
Ref in #85
