### ISSUE TITLE
navigation bar

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#20]
As a user,
I have a consistent navigation bar across all views when logged in.

Link to:
home (via logo)
create project
my profile
log out

**Comment by JMurphyWeb** [comment]
Initially the links won't work and no work going into styling

**Comment by jonscottfilm** [comment]
will 'create project' appear (so prominently) for all users? we were going to hide that away somehow.

**Comment by jonscottfilm** [comment]
discussed. we'll remove 'create project' from nav bar, and put within project dashboard.

**Comment by jackcarlisle** [comment]
@JMurphyWeb can this be closed?

**Comment by JMurphyWeb** [comment]
Nope its in sprint 2 (probably gonna come under the styling issue...)

**Comment by jonscottfilm** [comment]
Discussion of whether My startpack combines with My profile.

Working.
