### ISSUE TITLE
startpack validation - contract type related fields

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#201]
Startpack requires different fields to be present depending on contract type:
paye_only - contact type paye (one of 3)
NI number - contract type paye
p45 image - contract type paye
schedule d letter - contract sched d and daily_weekly = daily

linked to #132

**Comment by JMurphyWeb** [comment]
had to add radios which are a tad wonkey for now:
```
<img width="743" alt="screen shot 2017-05-30 at 16 48 02" src="https://cloud.githubusercontent.com/assets/12638261/26592171/df2551ce-4557-11e7-9975-89c5a74b4994.png">
```

**Comment by jonscottfilm** [comment]
Not 100% sure I can test this, all options appear for me all regardless of grade. 

We don't have a 'Contract Type' as an option to select when creating offer, do we? No, that's determined by the depts/job titles, and they are all set as PAYE/Sched-D by default, so the PAYE/Sched-D questions always appear for me in the Startpack...

**Comment by jonscottfilm** [comment]
Sorry. **What** are the 'essential' fields to trigger the ability to accept/reject an offer.
I'm trying each field one by one. Currently have optional fields empty (agent, loanout company)

I am unable to use any of the upload image fields, might that be the issue...?

**Comment by JMurphyWeb** [comment]
you are in the contract_type related validation issue. For the basic required fields, head over to: https://github.com/karmaradio/karma/issues/138

Yes, not being able to upload images will prevent you from having a validated startpack. Looking into it now over on issue #6

**Comment by JMurphyWeb** [comment]
@jonscottfilm think this is testable

**Comment by jonscottfilm** [comment]
PAYE-specific fields, are not required/demanding be filled:

Example: Accounts, Cashier, PAYE grade per dept/job titles list.

![image](https://cloud.githubusercontent.com/assets/28431542/26763780/6db267b8-4951-11e7-8c54-4ea99f015ca8.png)

Fields empty in startpack:
NI number - contract type paye
P45 image - contract type paye
PAYE - first/only/another job radio button

![image](https://cloud.githubusercontent.com/assets/28431542/26763783/7de53304-4951-11e7-8967-95f47ea1cdf9.png)

**Comment by jonscottfilm** [comment]
Nor working for Schedule-D grade (eg Accounts, Financial Controller)

Fields do _'appear'_ as issue describes, but I they appear for all types of contract. 
And they are not 'required'.

**Comment by JMurphyWeb** [comment]
@jonscottfilm I think I understand the bug. We will look into it.

Just a note on this issue: As an initial step, we agreed the form would not be dynamic depending on the offer (fields would show even if they weren't appropriate for that user/offer). 

It is an enhancement that can be done in future sprints depending on priority.

**Comment by jonscottfilm** [comment]
https://github.com/karmaradio/karma/issues/201#issuecomment-306244642

Copy you, re non-dynamic.
And you are looking into the bug.

**Comment by jonscottfilm** [comment]
Just a reminder - this is still an open Sp2 issue, but still unable to test.

This will need to be fixed for us to use correctly, to acquire all the correct startpack data (NI #, P45 or Sched-D letter) to merge to (_correct_) contract template, and deliver required documents to the PM.

**Comment by JMurphyWeb** [comment]
Sorry Jono I am just seeing this now. Will add to S3 milestone so we don't miss.

**Comment by JMurphyWeb** [comment]
@jonscottfilm this is in review. The work was done, just needed to be plugged together.

**Comment by jonscottfilm** [comment]
Working! Great job!
