### ISSUE TITLE
Remove underscore in Offer dashboard

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#218]
Remove small underscore/line between colon after 'Department: ' and 'Job title'.

![image](https://cloud.githubusercontent.com/assets/28431542/26598290/c869978c-456c-11e7-9ae0-2969e74bb61d.png)

**Comment by JMurphyWeb** [comment]
@jonscottfilm i believe this is now fixed?

**Comment by jonscottfilm** [comment]
yup
