### ISSUE TITLE
Reorder fields in create/edit offer view

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#219]
Move these fields: 
'Fee per day including holiday'
'Sixth day multiplier'
&
'Seventh day multiplier' 
To appear higher up the list, between 'Currency' and 'Other deal provisions.', in the order above.

**Comment by jackcarlisle** [comment]
@jonscottfilm this seems to have been done already

**Comment by jonscottfilm** [comment]
We'll create a new issue to make final re-jig to offer view.
