### ISSUE TITLE
Project/Offer View Bug

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#225]
At the moment you can only view a project that you have created yourself. This obviously needs to change.

- [x] fix project/offer view bug

**Comment by JMurphyWeb** [comment]
@jackcarlisle this can now be closed right?

**Comment by jackcarlisle** [comment]
@JMurphyWeb this hasn't been tested. Assigning to Jono

**Comment by jonscottfilm** [comment]
working
