### ISSUE TITLE
Move fields in create/edit Offer views

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#231]
Following fields should be moved towards top of form please, between Currency and Other Deal Provisions:

1. Fee per day including holiday
2. Sixth day fee multiplier 
3. Seventh day fee multiplier

**Comment by nogainbar** [comment]
I have done this and its in PR #163 :)

**Comment by jonscottfilm** [comment]
Other deal provisions should be moved to bottom of this  section, below Seventh day multiplier.

**Comment by jackcarlisle** [comment]
@jonscottfilm appears to be done already, can you confirm?

**Comment by jonscottfilm** [comment]
We'll create a new issue to make final re-jig to offer view.
