### ISSUE TITLE
Move fields in create/edit Project views

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#232]
Following fields should be moved towards top of form please, between Studio/Production Company & Company name:

1. Locations
2. Holiday rate

Additional notes kept at bottom. @nogainbar will insert spacing between last field (will be Operating base address country), and Add notes, for separation.

This is then consistent with the Project details view (apart from Add notes), and also Offer view, in terms of dividing up the forms, and resultant data.

**Comment by nogainbar** [comment]
done this, its in the PR #163. can be closed once merged. :)

**Comment by jackcarlisle** [comment]
@jonscottfilm this has been done. Can you confirm and close please if that's the case?

**Comment by jonscottfilm** [comment]
Done. Will create new issue for final re-jig.
