### ISSUE TITLE
Square corners on input fields - add border radius

### ISSUE THREAD

**Issue by nogainbar** [karmaradio/karma#236]
- Square corners on indigo project banner background and we would like to add border radius to match the rest of design.
Also, that is _slightly_ wider than the banners in the dashboard view. look into making the same width.

- Dropdown menus still with square corners

- Focus border when tabbed across the date field, also has square borders (the focus).

![pasted image at 2017_05_31 05_10 pm](https://cloud.githubusercontent.com/assets/12494147/26652293/558b4f54-4647-11e7-9e74-155d2c9de89d.png)

**Comment by nogainbar** [comment]
@jonscottfilm I have added the border radius on indigo project banner and also made the dashboard banner the same width.

I cant seem to see the dropdown have square corners? and neither the date.. maybe we can look at it together tomorrow.

:)

**Comment by jonscottfilm** [comment]
Must be a browser thing. I'll try another. Nonetheless, another little something to solve!

**Comment by nogainbar** [comment]
this should be fixed but need merging

**Comment by nogainbar** [comment]
reopening so that @jonscottfilm can check it?

**Comment by jonscottfilm** [comment]
Double yay!! 👍 👍 
Rounded corners, on desktop and mobile. 

No Lato font replaces systemui font yet, no?

![image](https://cloud.githubusercontent.com/assets/28431542/26690961/419bc81e-46f3-11e7-8b2f-ad4f9fa97458.png)

**Comment by nogainbar** [comment]
@jonscottfilm lato implementation is on another issue and is currently in a PR waiting to be merged :)

Closing as this one is done!
