### ISSUE TITLE
Footer design

### ISSUE THREAD

**Issue by nogainbar** [karmaradio/karma#243]
add a footer and decide what information @jonscottfilm would like to have there

**Comment by nogainbar** [comment]
@jonscottfilm could you send me the inverted colours logo for the header?

**Comment by nogainbar** [comment]
@jonscottfilm can you send me some examples of footers that you like?

**Comment by nogainbar** [comment]
<img width="394" alt="screen shot 2017-06-05 at 17 40 24" src="https://cloud.githubusercontent.com/assets/12494147/26793958/cbc0db02-4a17-11e7-8fe6-7ff46a685190.png">
<img width="1440" alt="screen shot 2017-06-05 at 17 15 29" src="https://cloud.githubusercontent.com/assets/12494147/26793960/cd4f08b8-4a17-11e7-8f75-7717b0a9627b.png">

**Comment by jonscottfilm** [comment]
This is the example I was referring to. There's prob too much info on here for the app, more applicable to the website, but gives you an idea. Do you think just keep the footer white bg, yeah?

[Copy of engine website mockup ICONS 2, 14 Mar 2017.pdf](https://github.com/karmaradio/karma/files/1052886/Copy.of.engine.website.mockup.ICONS.2.14.Mar.2017.pdf)

**Comment by nogainbar** [comment]
- everything left alight
- delete language
- terms
- privacy
- email address
all on while line

**Comment by jonscottfilm** [comment]
I think the footer logo and 'Karmaradio Inc' should be on same line, line 1.
And then Terms etc on line 2, please.
Logo slightly smaller. Karmaradio Title case (not CAPS)

___________________________________________________________________________

LOGO     Karmaradio Inc.
 
Terms     Privacy   support@karmaradio.com



For example, Github mobile version is just:

![image](https://user-images.githubusercontent.com/28431542/26843256-7f530dbe-4ae7-11e7-93c9-2a04a80f4c05.png)
