### ISSUE TITLE
Minor Application Fixes

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#247]
Below is a list of application bugs that I spotted while moving through the application flow:

- [x] change any mention of "Schedule d", to "Schedule D" (looks like typo of 'scheduled')
- [x] change "swift code" to "SWIFT code"
- [x] change "Vat number" to "VAT number"
- [x] "Date of Birth" should default to TODAY -16yrs, or be blank. Users easily skip, or enter right day, month, but keep 2017.
- [ ] Uncheck "Check the box if you deal with an agent" by default. Is checked on new account creation.
> quick note on this one: we won't know if the user has seen these fields if it defaults to false but if it's true, they'll have to deselect before continuing. It prevents someone who deals through an agent from missing the box, which will have knock on effects for the offer.
- [x] Change "Check the box if you deal with an agent" to "Check the box if your deal will be done through your agent".
- [ ] Uncheck "Check the box if you have a student loan which is not fully repayed" by default. Is checked on new account creation.
- [x] Change "Check the box if you have a student loan which is not fully repayed" to "Check..._repaid_"

- [x] Change "Bank account users full name" to "Full name on bank account", because it could be Mr & Mrs J Scott - not J Scott.
- [x] "Passport image" label can be hidden. 'Upload an image of your passport' will suffice. They also contain a 2nd upload link. Same change for all other file upload labels: "Box rental image", "Equipment rental image", "Vehicle insurance image", "P45 image", "Schedule d letter image", "Loan out company cert image"
- [x] Change the word "image" in upload field instructions to "file", eg: "Upload a file of your Schedule D letter"
- [x] "Passport full name" should include placeholder text of 'Your full name as it appears on your passport (inc. middle name(s))
- [x] Add separation space after any "Choose File" upload buttons, and the next fieldname, eg: "Equipment rental inventory value"
- [x] Change "Fill the following fields if you bring a vehicle to the shoot:", to "Your vehicle details for site access and parking:"
- [x] Change "Upload an image of your loan out companies certificate" to "Upload a file of your loan out company certificate" (company)
_(Jono edits above, **sorry** for jumping on, and expanding your list @jackcarlisle!)_

- [x] dashboard "create project" styling isn't correct when there aren't any projects
- [x] logout button turns purple after it's been clicked
- [x] in the startpack, the "middlenames" field should be "middlename(s)"
- [x] file upload inputs need styling
- [x] in the startpack, "agent deal?" should be changed to something more user friendly
- [x] change "Agent bank account iban" to "Agent bank account IBAN"
- [x] add text before vehicle information saying something like "Do you bring your own vehicle?"
- [x] random checkbox in the startpack doesn't have a label 
- [ ] check for changes when startpack is updated before displaying success message
- [x] the gap between "My projects" and the project tiles in dashboard is too big
- [x] date of birth needs to have more options for year (backdated by 70 years?)
- [x] add navigation back to offer once startpack has been updated (keep query param)
- [x] add error messages for the image fields in the startpack
- [x] look into styling on chrome and windows - dropdown and fonts
- [x] operating base not initially required
- [x] "+" button for create project is skewed slightly
- [ ] add footer to the application (@noga)
- [x] add pdf icon for uploaded pdfs
- [x] add functionality to delete an uploaded file
- [x] put the project info data into a table
- [x] change "Start date" in `project/:id` to "Shoot start date"
- [x] change "Studio" in `project/:id` to "Studio/Production Company"
- [x] some links change colour to red when clicked - remove this
- [x] `offer/new` error isn't styled when changeset is invalid
- [x] move "Other deal provisions" below the others in `/offers/new`
- [x] add project details to the offer view
- [x] add correct content permissions to the view offer page
- [x] break up long error messages into smaller sentences
- [x] make sure that offers are showing on the dashboard
- [x] add grey background to the application
- [x] implement the navbar with the inverted logo
- [x] Post Production dropdown bug
- [x] adds contract type to offer

**Comment by jonscottfilm** [comment]
@noga knows and will fix this issue:

'look into styling on chrome and windows - dropdown and fonts'

Most views have _some_ text using systemUI font rather than Lato, inc. the Call to action buttons.

Can't recall what fix is for radius on dropdown field borders. No br format was present in Chrome or Edge on Windows.
