### ISSUE TITLE
Login flow - bug when user zooms in

### ISSUE THREAD

**Issue by nogainbar** [karmaradio/karma#250]
ok on create account page, not working so well on other login flow screens

**Comment by nogainbar** [comment]
@jonscottfilm looking at it again now on my computer I cannot replicate this problem on the login screen, is it still doing it for you?

**Comment by jonscottfilm** [comment]
This is now fixed, for me! Yay!

**Comment by jonscottfilm** [comment]
On mobile, at least...

**Comment by jonscottfilm** [comment]
And desktop! Works for login and new account screens.

Not 'reset password' screen, yet...

![image](https://cloud.githubusercontent.com/assets/28431542/26690871/e56160a4-46f2-11e7-9e21-a793488ae220.png)

**Comment by jonscottfilm** [comment]
Height issue doesn't appear to be fixed for this 'Reset your password', screen, which I think @JMurphyWeb noted yesterday. Sorry!

![image](https://cloud.githubusercontent.com/assets/28431542/26724728/d671cd0e-4792-11e7-8cb1-8e4499bb842c.png)

**Comment by nogainbar** [comment]
issue fixed so closing

**Comment by jonscottfilm** [comment]
Presume this is not merged yet, because it's still not fixed for me.

**Comment by nogainbar** [comment]
@jonscottfilm PR is in waiting to be merged, not sure why this keeps escaping our flow! I feel like ive done that change so many times :) should be fixed now tho..

**Comment by jonscottfilm** [comment]
Def fixed. Phew! :)

![screenshot_20170603-131229](https://cloud.githubusercontent.com/assets/28431542/26753458/bcd2ccfa-485e-11e7-8c85-b2965fbcf7f8.png)
