### ISSUE TITLE
Resize upload file 'choose file' box

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#253]
Across app, but eg in edit startpack view, enlarge upload file 'choose file' box.

![image](https://cloud.githubusercontent.com/assets/28431542/26691286/82c784f8-46f4-11e7-85c3-ff88d4dd6915.png)

**Comment by jackcarlisle** [comment]
@jonscottfilm I'm working on this at the moment

**Comment by JMurphyWeb** [comment]
@jonscottfilm upload file button is now fixed.

**Comment by jonscottfilm** [comment]
Sorry, yes - this has been working for a while.

We do need to resize the PDF file icon. I'll create an issue if it doesn't already exist.
