### ISSUE TITLE
Input border

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#258]
When we click on an input, it adds a border which changes the size of the input which in turn makes it move other components around it. A quick fix would be to always have a grey border but just change the colour on focus.

- [ ] fix the input focus border

**Comment by jonscottfilm** [comment]
Ah, so it does. Same colour grey as field background. I'd say that works.

**Comment by JMurphyWeb** [comment]
@jackcarlisle this is now fixed right?

**Comment by jackcarlisle** [comment]
@JMurphyWeb i haven't touched this yet. Can look into it today

**Comment by JMurphyWeb** [comment]
ohh yeah. Maybe my eyes just got used to it.

**Comment by jonscottfilm** [comment]
looks to be working to me
