### ISSUE TITLE
File upload errors

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#259]
We need to format our changeset errors so that it displays an error when a file is needed for a startpack to be completed. 

- [x] manually add errors to changeset if certain fields are required

**Comment by JMurphyWeb** [comment]
![screen shot 2017-06-02 at 12 48 35](https://cloud.githubusercontent.com/assets/12638261/26724533/e3d83196-4791-11e7-9254-c3322b71cb4c.png)

**Comment by jonscottfilm** [comment]
Working.
