### ISSUE TITLE
Format email fields on all login screens

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#277]
Format email fields as lowercase (or field as 'email format' expecting lowers, @ and '.') on all login screens.

Errors thrown with typo non-lowercase letter in email address

User error, and in this case, mobile Chrome browser, capitalising

![screenshot_20170603-124733](https://cloud.githubusercontent.com/assets/28431542/26753307/83e1827c-485b-11e7-823c-744a4fd75150.png)

Or (ignore refilled auto-fill)

![screenshot_20170603-124911](https://cloud.githubusercontent.com/assets/28431542/26753338/0b655584-485c-11e7-90a1-0e9c7851a7c9.png)

**Comment by jackcarlisle** [comment]
@jonscottfilm do you mean that you want the letters to default to lowercase and expecting email format when a user enters their email?

**Comment by jonscottfilm** [comment]
Yes, force lowercase email format.

Currently it fails if you enter a capital. It should just not allow capitals.

Thanks.

**Comment by JMurphyWeb** [comment]
@jonscottfilm we can convert all email addresses to lowercase before storing them, then regardless of whether user types capitals or not, we will always convert to lowercase and then compare.

**Comment by jonscottfilm** [comment]
And this error message is misleading. 
![image](https://user-images.githubusercontent.com/28431542/27358075-e10db83a-560c-11e7-859c-e8276cf7dc0b.png)

Please change to this error message wording: 'Invalid email'
