### ISSUE TITLE
Email Service

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#28]
We will need to set up email notifications for multiple things within the application. We can use AWS SES with SMTP in order to achieve this. Use cases include:

- email verification upon sign up
- notification of offer
- notification of response (accept or reject) to offer 

- [x] set up email notifications

**Comment by jackcarlisle** [comment]
Notes from PR

>The main points:
Use ETS to store expiring hashed strings
Move email sending into email views
Send from domain in config/env
Shouldn't we check that user is verified inside our Auth plug?
Any reason we have a verify controller and not put that function in the user controller? I am happy to go with either, just good to understand why..

**Comment by JMurphyWeb** [comment]
@jackcarlisle can we close?

**Comment by jackcarlisle** [comment]
Yep!
