### ISSUE TITLE
Project view bug on mobile

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#282]
The layout of the project offer data is squashed on mobile. The three numbers should all be on the same line:

<img width="321" alt="screen shot 2017-06-05 at 10 45 25" src="https://cloud.githubusercontent.com/assets/12450298/26779170/3b225e80-49dc-11e7-9bf8-831b43e3e851.png">

Also the offer tiles are too small now with the new container: 

<img width="324" alt="screen shot 2017-06-05 at 10 47 15" src="https://cloud.githubusercontent.com/assets/12450298/26779201/65f407e4-49dc-11e7-9641-c3f878433bed.png">

**Comment by nogainbar** [comment]
@jackcarlisle since the layout might change, I am working on the layouts now, it would end up probably looking something like this- 
![mobile_example](https://cloud.githubusercontent.com/assets/12494147/26782598/4615a698-49ec-11e7-8c81-e81f2975f731.png)
