### ISSUE TITLE
Radio Button Bug

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#284]
The radio buttons on the startpack for PAYE contracts are not sized correctly:

<img width="322" alt="screen shot 2017-06-05 at 12 06 21" src="https://cloud.githubusercontent.com/assets/12450298/26781650/8681aeb6-49e7-11e7-8ed3-2d4b81f66c0c.png">

**Comment by jonscottfilm** [comment]
This bug is still active:

![image](https://user-images.githubusercontent.com/28431542/27592429-640052fe-5b4c-11e7-863b-abad605fe73f.png)

**Comment by JMurphyWeb** [comment]
Also this:


![screen shot 2017-06-29 at 12 33 41](https://user-images.githubusercontent.com/12638261/27685744-7f9bef1a-5cc7-11e7-970d-b2e16f29650c.png)

now this:
![screen shot 2017-06-29 at 12 33 58](https://user-images.githubusercontent.com/12638261/27685763-888439e8-5cc7-11e7-8d1c-549efe2617d7.png)

**Comment by JMurphyWeb** [comment]
![screen shot 2017-06-29 at 13 15 22](https://user-images.githubusercontent.com/12638261/27686990-08edf3a8-5ccd-11e7-8d58-119787b28682.png)

Fixed and increased size of radios for improved usability

**Comment by jonscottfilm** [comment]
Radio buttons are much better.

Checkboxes should match same size as radio buttons... (I'll add to #444) 

Part of this issue #284, Profile data should be tabbed over to a left aligned column, to separate from label:

![image](https://user-images.githubusercontent.com/28431542/27691786-06110b1a-5cdd-11e7-976c-f9810fca291d.png)

**Comment by jonscottfilm** [comment]
Sorry, bit premature to remove bug label...

![image](https://user-images.githubusercontent.com/28431542/27708835-042bf2b2-5d12-11e7-9498-17ccd7bba366.png)

**Comment by JMurphyWeb** [comment]
@jonscottfilm please prioritise

**Comment by jonscottfilm** [comment]
_Think_ this is all done.
