### ISSUE TITLE
[COMPLETED] Restrict upload types

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#287]
Limit file upload types to the following: 
 pdf, png, jpg

if a file is not uploaded in one of these, we should warn the user.

**Comment by jonscottfilm** [comment]
How will the user be notified of the restriction?
I.e., despite the helper text saying 'these filetypes only' but the user repeatedly tries to upload their Mac Pages equipment list.

**Comment by jackcarlisle** [comment]
They will be prompted and informed of the types of documents that they can upload. They'll get a message saying something like "Invalid document type, upload a .pdf" etc...

**Comment by jonscottfilm** [comment]
OK. I'm all for making them conform...... just hope they are able to! (i.e. make a PDF. _should_ do - otherwise they're not worth employing!)

**Comment by jonscottfilm** [comment]
We're vaguely concerned that idiots might not have PDF-writing capability, either on computer or in their head! Lower priority.

**Comment by JMurphyWeb** [comment]
Now done

**Comment by jonscottfilm** [comment]
Might need to revisit file-type restrictions in later sprints. Will backlog.

PDF-maker on fly would be my suggestion. So long as it offers a preview of resultant PDF, in case of cropping. Would restrict file-size & res this way, also.

**Comment by jonscottfilm** [comment]
Otherwise working for jpg, pdf, png.

**Comment by JMurphyWeb** [comment]
@jonscottfilm ok. 

In the future open a new issue and link to this one so we can keep a record of what was done in each milestone.

**Comment by jonscottfilm** [comment]
Done.
