### ISSUE TITLE
Deploy application

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#29]
Useful so that we can ask Jono to test

**Comment by JMurphyWeb** [comment]
deployed with the following url https://karmaradio.herokuapp.com/

**Comment by JMurphyWeb** [comment]
Automatic deploy on master branch is turned on

**Comment by JMurphyWeb** [comment]
Jono this can be closed if you are satisfied that the app can be viewed at https://karmaradio.herokuapp.com/

**Comment by jonscottfilm** [comment]
Closed.
