### ISSUE TITLE
[COMPLETED] Retrieve Data from Database

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#291]
We need to group together all of the data related to a `project`, `offer`, `startpack` and `user`. This information will then need to be transformed into JSON so that it can be processed by the document merging script. 

- [x] retrieve from the database and group all contract data

**Comment by JMurphyWeb** [comment]
going to start with the logic in document controller and model for now;

**Comment by JMurphyWeb** [comment]
Now done
