### ISSUE TITLE
Contractor: display merged contract

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#292]
As a contractor, 
I want to see the merged contract after accepting an offer.

The merged contract can replace the unmerged one (#10) on the offer details view.

**Comment by jonscottfilm** [comment]
We'll work on 'view in app, or in browser' (if secure) as more convenient way to see merged contract.
Bearing in mind they will see it as part of Docusign flow.

More pressing to view the contract PRIOR to merging, perhaps.

Working. Note above, and you can close.

**Comment by jackcarlisle** [comment]
@jonscottfilm ok sounds good!
