### ISSUE TITLE
PM: Add Documents to Offer View

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#293]
As a PM,
I want to be able to view the un-filled contract in the project_offers page,
So that I can act upon, or change, it

**Comment by jonscottfilm** [comment]
Not sure this is needed.

**Comment by JMurphyWeb** [comment]
@jonscottfilm I think we are with you.

**Comment by JMurphyWeb** [comment]
removing from milestone @jonscottfilm
