### ISSUE TITLE
New layout

### ISSUE THREAD

**Issue by nogainbar** [karmaradio/karma#297]
Suggested new layout: 
![example1_button2](https://cloud.githubusercontent.com/assets/12494147/26794034/10f9e9a2-4a18-11e7-98fb-a973aee6b68a.png)
![mobile_example light_button](https://cloud.githubusercontent.com/assets/12494147/26794038/14de998c-4a18-11e7-838c-517e03e4a21b.png)
![mobile_example_project_page](https://cloud.githubusercontent.com/assets/12494147/26794044/1880d014-4a18-11e7-902e-c1572691ecfb.png)

**Comment by nogainbar** [comment]
@jonscottfilm would be great to hear you thoughts about this layout :)

Relates to #153 #165 #154

**Comment by jonscottfilm** [comment]
Hey Noga. Much preferring the new layouts here, especially the now clear project and offer tiles. I'm still a bit concerned the pastel green/yellow/red are a _bit_ too weak in colour ( I could be wrong) - I feel they don't quite fit with the header and logo? Logo is looking a bit wonky edges, is that just where it's in Sketch?

Re the View Details button - I feel it should match how one navigates to get INTO the project from the dashboard view, which is just clicking the tile. Maybe view details can just be a link in the project name/codename in the 2 different views  here?

Plus '+' sign needs to be slightly smaller in relation to the circle, and the whole icon (circle & +) smaller too.  It's not a frequent action that users will do - to create a project, so it doesn't have to be too prominent a feature.

**Comment by jackcarlisle** [comment]
Just a quick note about the dashboard view below. It feels like the "My offers" section is a sub-section of the "My projects" section. These should both be at the same level to prevent correlation between them:
![mobile_example light_button](https://cloud.githubusercontent.com/assets/12494147/26794038/14de998c-4a18-11e7-838c-517e03e4a21b.png)

**Comment by nogainbar** [comment]
@jackcarlisle @jonscottfilm @JMurphyWeb here is the layout Jono and I agreed on today. I have already started implementing it and will continue throughout today and tomorrow
![layout_1 0](https://cloud.githubusercontent.com/assets/12494147/26832062/2015362c-4ac6-11e7-87d7-9fc6648954d8.png)

note: colours might change further down the line

**Comment by jonscottfilm** [comment]
Like yellow becoming light grey.... :) I will send a palette, but you could just pick a light grey, tbh. The yellow isn't working for me.

**Comment by jackcarlisle** [comment]
Looks great! One small thing, should the plus button be down level with "Projects"?
