### ISSUE TITLE
Contractor & PM 'offer view' - make more accessible

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#298]
Make offer view easier to read & review, for the contractor, to decide whether to accept job or not.
(and PM 'offer view', the same)

Suggest: 
2 columns, both left-aligned.
Labels not in bold. 
Offer data in bold.
@beccacca 
OR, offer data in slightly larger or darker font, with key fields in Bold e.g: job title, start date, rate.

Just need to be cleaner, are key data more legible/apparent.

**Comment by JMurphyWeb** [comment]
These seem like fairly small changes, just some formatting and no new layout or functionality or data.

Putting 1 hour on it @jackcarlisle

**Comment by jonscottfilm** [comment]
As & when, NOT priority:

'Labels not in bold.
Offer data in bold.'

and ref #306

**Comment by JMurphyWeb** [comment]
@jonscottfilm we can remove from this milestone if you want. Just let me know if/when you are.

**Comment by jonscottfilm** [comment]
Yes, can remove. Handle in Sprint 4.

**Comment by JMurphyWeb** [comment]
done
