### ISSUE TITLE
Terms and conditions

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#3]
As as contractor/project manager,
I have to accept terms and conditions,
So that I can gain access to the application

**Comment by JMurphyWeb** [comment]
@jackcarlisle I was wondering if we should add an `agreed_terms: Boolean` column to user table?

I will not implement for now but what are your thoughts?

**Comment by jackcarlisle** [comment]
@JMurphyWeb yeah that or `terms_accepted`?

**Comment by JMurphyWeb** [comment]
@jackcarlisle cool will do.

Task list:
- [ ] add checkbox and link to account creation view
- [ ] update existing tests
- [ ] add test for attempted account creation without ticking box
- [ ] store the terms_accepted in db as true if everything goes simmingly

**Comment by JMurphyWeb** [comment]
Had a problem when trying to default the `terms_agreed` to `false`.

In the migration we have:
```elixir
      add :terms_accepted, :boolean, default: false
```

In the model:
```elixir
  schema "users" do
    ...
    field :terms_accepted, :boolean
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :first_name, :last_name, :password])
    |> validate_required([:email, :first_name, :last_name, :password])
    ...
  end

  def registration_changeset(struct, params \\ %{}) do
    struct
    |> changeset(params)
    |> terms_accepted(params)
    ...
  end


  defp terms_accepted(changeset, params) do
    message = "You must agree to the terms and conditions"
    changeset
    |> cast(params, [:terms_accepted])
    |> validate_required([:terms_accepted])
    |> validate_inclusion(:terms_accepted, [true], message: message)
  end

```

Everything works ok, I just had an issue when trying to set the default of `terms_accepted` in the model to `false` where it would let me create a new user without checking the terms_accepted:

```elixir
  schema "users" do
    ...
    field :terms_accepted, :boolean, default: false
  end
```

I don't think there is any reason to have `default: false` inside the model, but maybe @jackcarlisle can confirm.

**Comment by JMurphyWeb** [comment]
I was unsure of the best way to validate for a value of `true` and ended up using:
```elxir
    validate_inclusion(changeset, :terms_accepted, [true], message: message)
```

**Comment by jackcarlisle** [comment]
@JMurphyWeb I think as long as it's inside the migration it should be good enough. Looks good! Will take a look at your PR now

**Comment by JMurphyWeb** [comment]
@jonscottfilm we are still awaiting the T&Cs. Will they be in plain text for us to put into a basic HTML web page?

**Comment by jonscottfilm** [comment]
We won't have these for a couple weeks at the earliest, I'm afraid.

**Comment by jonscottfilm** [comment]
But yes, plain text with section headers, to make bold in html.

**Comment by JMurphyWeb** [comment]
@jonscottfilm there is nothing at the end of the `terms and conditions` yet, but the user has to check the box in order to create an account

**Comment by jonscottfilm** [comment]
Navigation to said T&C's (once text is received), to be created.
Would _like_ for checkbox to appear once scrolled to bottom of T&C's.

For now, this works, and closes this issue.
