### ISSUE TITLE
Fix dashboard layout in mobile, when no projects present

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#305]
Overlapping text, on mobile. See screenshot.

May be fixed by new layout with grey sub-header..?

![screenshot_20170606-190857](https://user-images.githubusercontent.com/28431542/26844775-726190da-4aec-11e7-85d7-53a0dfa79d2b.png)

**Comment by nogainbar** [comment]
@jonscottfilm this should be fixed in the pull request that is in progress :)

**Comment by jonscottfilm** [comment]
Fixed. Thanks!
