### ISSUE TITLE
[COMPLETED] Download Un-merged Document from S3

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#308]
The first step that has to be done before a document can be merged is that it has to be downloaded from S3. We need to write a function that will retrieve the document and then temporarily store it in a location ready for use by our document merge function.

- [x] download document from S3
- [x] save file ready to be merged

**Comment by JMurphyWeb** [comment]
@jackcarlisle one other thing I was thinking about this yesterday: it's also worth pushing things up to heroku (staging app?) as you go to make sure behaviour is as expected on their system.

**Comment by jonscottfilm** [comment]
And if downloading to 'somewhere other than in S3', then security/encryption need to be of paramount importance...

**Comment by jackcarlisle** [comment]
@jonscottfilm yes definitely, the file storage would only be temporary. It will be deleted from the file tree once it's been merged and then uploaded again to S3

**Comment by jonscottfilm** [comment]
ok, thanks.

I don't fully understand this process, but how about encryption when **'in transit'**, i.e. when user is uploading, or downloading?

**Comment by JMurphyWeb** [comment]
now done

**Comment by jonscottfilm** [comment]
Is data transit out from, and back into, S3, albeit temporarily, a security concern?

I know the process has to happen, to merge, but how else do other services do it (encryption in transit?)

**Comment by JMurphyWeb** [comment]
@jonscottfilm this is a concern, yes.
