### ISSUE TITLE
Offer tile mobile bug

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#319]
When a job title is too long on mobile it means that it pushes content down and increases the size of the tile:

<img width="322" alt="screen shot 2017-06-07 at 15 05 27" src="https://user-images.githubusercontent.com/12450298/26882664-e5662338-4b92-11e7-883c-4a913b526e70.png">

**Comment by jonscottfilm** [comment]
Could _also_ reduce the rate '£200/day' or the '/day' bit, to allow more room...? 

Or put the /day on line 2? 

Should prob be showing weekly rate here too, but that's for another day :)

**Comment by jackcarlisle** [comment]
Moved the icon closer to the left hand side to make room
