### ISSUE TITLE
Fix - 'add project' & 'add offer' plus button/circle icon invisible on first page load

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#331]
Fix - 'add project' & 'add offer' plus button/circle icon invisible on first page load
(also - if it's an easy fix, we feel the button should go back up _on_ the line. Action to take based on the label of the line it's sat on, i.e. + 'Project')

First page load, re-load:

![image](https://user-images.githubusercontent.com/28431542/26923322-aa8656b4-4c39-11e7-9050-2ec1dd4dc962.png)

re-size, it appears:

![image](https://user-images.githubusercontent.com/28431542/26923329-af558958-4c39-11e7-8024-ac0b35a1a281.png)

Same for 'offers view':

![image](https://user-images.githubusercontent.com/28431542/26923374-cf882884-4c39-11e7-87be-6eb4a5d0ac96.png)

![image](https://user-images.githubusercontent.com/28431542/26923386-d7b700f2-4c39-11e7-8506-bf0b4401d1b9.png)

**Comment by jackcarlisle** [comment]
I can't replicate this locally but I'm finding the error on the remote application. I've made a couple of changes to the plus button so will check that it's working when the work gets merged in

**Comment by jonscottfilm** [comment]
ok, thanks

**Comment by jonscottfilm** [comment]
You had to revert to the solid '+' button, to get the error to go away?

There's something funky going on. 
Can't log out on desktop. Can on mobile. Burger menu not working on mobile.

**Comment by jackcarlisle** [comment]
I think noga might have swapped the logout button with a placeholder. Will also look into the burger menu not working on mobile. Do you mean that it doesn't expand when clicked or that the icon doesn't show up?

Could you open a couple of issue bugs for the above?

**Comment by jonscottfilm** [comment]
Burger appears, but doesn't open. I'll create issues.

**Comment by jackcarlisle** [comment]
@jonscottfilm  can this be closed now?

**Comment by jonscottfilm** [comment]
Er, yes.
