### ISSUE TITLE
Move profile data into startpack

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#342]
As a contractor,
I want to be able to see my profile data when I'm in my startpack,
So that it is kept in context

**Comment by jonscottfilm** [comment]
I think startpack should be renamed Profile, throughout app, and always referred to as such, eg: you need to update your profile to accept this offer. Then it's clean. Project. Profile. Offers.

And as such, the 3 profile fields (first name, last name, email) should appear WITHIN the big 'startpack (renamed as 'Profile') form.
