### ISSUE TITLE
Fix - burger menu on mobile doesn't expand

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#347]
Fix - burger menu on mobile doesn't expand, so can't view menu items:

Startpack
My profile
Log out

**Comment by JMurphyWeb** [comment]
@jonscottfilm that is sorted now.

**Comment by jonscottfilm** [comment]
Yes it is! Thanks.

We need to adjust height of both indigo header (now only 2 menu items (which I think should be right aligned, btw)) and grey header, which is too big. I'll issue.
