### ISSUE TITLE
Only allow one document upload for each type

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#359]
In order for the current logic to work, each project should for now only be able to upload 1 of each type of contract.

I don't think we are sacrificing any functionality by doing this, and it is something that can be reversed in the future when we reconsider how the document uploads will take place.

**Comment by JMurphyWeb** [comment]
@jonscottfilm this had to be fixed in order for our merging logic to work smoothly.

As a PM you are only able to upload 1 type of each document. (ie only one PAYE and one SCHEDULE-D)

Maybe if/when we reintroduce the other document uploads this restriction can be reviewed.

**Comment by jonscottfilm** [comment]
So long as this is based on filename (which I think @jackcarlisle said it was), eg: PAYE, and Construction PAYE named contracts, then this is fine. There will never be more than one type of a unique document.
