### ISSUE TITLE
Testing the merging of documents

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#364]
@jonscottfilm 

Merging should now be testable:
https://karmaradio.herokuapp.com/

__________________________

Things to make sure of:
- There is exactly 1 contract of each type uploaded to the project
__________________________

We have only been testing on a form with 5 fields set as fillable and it seems ok. Over to you for some bigger forms.
__________________________

After merging, you should get a success message and the document URL displayed on the screen (temporary addition for manual testing):
<img width="621" alt="screen shot 2017-06-13 at 17 25 31" src="https://user-images.githubusercontent.com/12638261/27093129-77aa1bf4-505d-11e7-8204-f2c22dbd69ca.png">

**Comment by jonscottfilm** [comment]
OMG. Will test, when I can get a second...

**Comment by JMurphyWeb** [comment]
haha thanks jono. it is still deploying so give it 10 mins please

**Comment by jonscottfilm** [comment]
And it worked, first time! Like a dream. 

_Really_ gonna test it with **lots** of fields in a full start form, but tomorrow morning now.

Well done, guys!!

**Comment by JMurphyWeb** [comment]
Great. Yeah the sooner we can test with bigger files the better. If it survives ok, it might be worth putting a unrealistically large document together, just to see where the breaking point is.

**Comment by jonscottfilm** [comment]
works!
