### ISSUE TITLE
Delete Documents

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#371]
Taken from #9 
> IF one uploads incorrect file, OR file-type, or in the wrong field (eg passport in box rental field) - we need ability to delete the wrong file. Rather than just replace.
(example, one might drunkenly upload a compromising photo of oneself, and not have another permitted file on one's iPad to replace it...........)

- [x] add functionality to delete documents as opposed to replacing

@jonscottfilm could you please prioritise this?

**Comment by jonscottfilm** [comment]
Needed before real-world use of app.
So, end Sp4...? Have labeled. Should we create Sp4 Milestone?

**Comment by JMurphyWeb** [comment]
@jonscottfilm you need to go through all issues that are not in Spr 2 & Spr 3 and reprioritise anything that needs it.

Start at Priority 2's and work down.

From that we can determine what will we will aim to put into Sprint 4.

**Comment by jonscottfilm** [comment]
Must be in Sp4 (MVP to use) if not, users will not submit startpacks.

**Comment by jonscottfilm** [comment]
The red cross icon, like on the project document view.

**Comment by jonscottfilm** [comment]
Excellent job, and so quickly, @jackcarlisle.  Thanks!

Do the red crosses look a little squished to you? And therefore, I suppose it might be the whole PDF icon, being vertically squished.

Red circle appears oval, and cross not centred:

![image](https://user-images.githubusercontent.com/28431542/27834162-b8e60bac-60cd-11e7-9b69-a3fe4dc9547a.png)

**Comment by jonscottfilm** [comment]
Also (sorry) I think we should have the 'Are you sure?' deletion warnings, like the project view.

**Comment by jackcarlisle** [comment]
@jonscottfilm due to the custom implementation of this, an `are you sure?` warning isn't possible to add in this case. It looks the same as the project document version but under the hood it's quite different

**Comment by jackcarlisle** [comment]
@jonscottfilm I can't replicate the squished button so it must be inconsistencies across browsers. It's a custom built button instead of an icon. I'll see if I can fix it

**Comment by jonscottfilm** [comment]
Understood re https://github.com/karmaradio/karma/issues/371#issuecomment-312899010. Is what it is, 

Users should just upload the correct document. Only danger, considering our earlier conversation about versions, is users deleting things that then get deleted for the project too.

Low priority, but could the squished red crosses be the ratio of the PDF icon?

Same issue in Internet Explorer:
![image](https://user-images.githubusercontent.com/28431542/27837559-dc0ae5e4-60dc-11e7-9d5b-972acb4487dd.png)


Good in Project view in IE:
![image](https://user-images.githubusercontent.com/28431542/27837512-9af07740-60dc-11e7-8b1c-c5c3ecede415.png)

**Comment by jonscottfilm** [comment]
Functionailty works. Good job @jackcarlisle .

Longterm, def need to discuss how we avoid deletion of documents by contractor doesn't delete for a project... New issue!
