### ISSUE TITLE
Format Data for Merge

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#379]
We need to format the data that is being merged into the contract. The following adjustments need to be made:

- [x] monetary amounts need a currency symbol in front of them
- [x] dates need to be formatted to `dd-mm-yyyy`
- [x] numbers need to be rounded to two decimal places where appropriate
- [x] numbers in the thousands need comma separators

**Comment by JMurphyWeb** [comment]
@jonscottfilm contracts should now have formatted fields.

**Comment by jonscottfilm** [comment]
Works for contract merge, yes - well done!

![image](https://user-images.githubusercontent.com/28431542/27252804-14c90e1e-535f-11e7-844a-4731a0eed6f8.png)

Have you just made that work for the merge, for now?
Where does that happen? Reason I ask is I normally need to input that formatting in the mergefields in the original Word document.

I guess the best solution is Karma handles it. Whatever data is put in, Karma handles, presents and passes-on, the correctly formatted data.

i.e. I take it we've not implemented these changes in all project/offer views?
Will need this in Sp4. (think it's on @JMurphyWeb's list)

![image](https://user-images.githubusercontent.com/28431542/27252760-2dde683c-535e-11e7-81c7-ec0ca496c70f.png)

**Comment by jonscottfilm** [comment]
But working for merge, so you can close once you've clocked this comment https://github.com/karmaradio/karma/issues/379#issuecomment-309211793

**Comment by jackcarlisle** [comment]
@jonscottfilm We're formatting the data just before we send it to our merge function. We can re-use this functionality for the project and offer views

**Comment by jonscottfilm** [comment]
Understood.

**Comment by JMurphyWeb** [comment]
@jonscottfilm just remember to issue this request if you haven't already?
