### ISSUE TITLE
Student Loan button should be changed to 'yes/no' selection, unchecked by default.

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#385]
Student Loan button in startpack should be unchecked by default. Currently it is.

Make 'yes/no' selection (dropdown, radios, checks?)

Make REQUIRED field (if not already) will ensure that is answered.

Correct typos: 'You **are** repaying **your**....'
'You am repaying my Loan direct to the Student Loan Co.'

![image](https://user-images.githubusercontent.com/28431542/27253132-a49c9d74-5366-11e7-9139-05646721badf.png)

**Comment by JMurphyWeb** [comment]
@jonscottfilm please prioritised

**Comment by jonscottfilm** [comment]
meh
