### ISSUE TITLE
docusign pricing

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#386]
Look into way of reducing docusign pricing

**Comment by JMurphyWeb** [comment]
100 documents per month ~ £400 envelopes / month paid monthly

**Comment by JMurphyWeb** [comment]
I want to check if we can package more than one document into an envelope and therefore reduce the number of envelopes per project

**Comment by JMurphyWeb** [comment]
not looking possible to combine multiple documents per envelope

**Comment by jonscottfilm** [comment]
Closing. Link to #429 

12month Docusign deal now done.
