### ISSUE TITLE
Signing: PM can attach signees to each document they upload

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#387]
As a PM, 
I can add and remove `signees` to each document, 
so that the document can be sent around the correct approval chain.

DB Table:
A signee_order table should have the following columns: 
signee_id
document_id
index

User flow:
Signees can be created on a project (#393), then the PM can add the projects signees to each document individually. 

If the PM needs to edit the approval chain on a document:
In order for us to easily build ordered approval chain, the PM can only change a saved list of signees attached to a document by removing them all and starting the process again.

**Comment by jonscottfilm** [comment]
Sorry - where & how do I test this? Am I being stoopid - is it not part of the 'Add a document to a project' view?

**Comment by jackcarlisle** [comment]
@jonscottfilm sorry! I forgot to add the button to link it up. Will let you know when it's ready

**Comment by jonscottfilm** [comment]
Understood!

**Comment by JMurphyWeb** [comment]
@jonscottfilm ready

**Comment by jonscottfilm** [comment]
Works. Comments are:

1. Presume the number order is the signing order?
2. When no signees yet added, wording should read: 'Add signees to this document, in the order of approval'
3. You can add the same person (email address) as a document signee, more than once. Might not be a problem, _potentially_ a benefit, but we feel it should come with a warning: 'you have added joebloggs@email.com already. Are you sure?' (also ref #https://github.com/karmaradio/karma/issues/393#issuecomment-310520434)

**Comment by jonscottfilm** [comment]
doh

**Comment by jonscottfilm** [comment]
and, ah: #404

**Comment by JMurphyWeb** [comment]
@jonscottfilm will fix wording, but duplicate signees per document feels like something we should put out there and get feedback on.

**Comment by jonscottfilm** [comment]
Agreed.
Will test.

**Comment by jonscottfilm** [comment]
Working nicely.
