### ISSUE TITLE
Signing: Contract can be signed by user and approval chain

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#388]
#380 

do the migration and attached tasks: https://github.com/karmaradio/karma/issues/389 before this user story

As a contractor,
I can sign my contract after I accept it,

User flow:
Save the merged contract, display to contractor, and show them a `sign` button. Clicking the button launches the flow. Add a note to the user that the signing is in progress and they will receive an email from Docusign when it is comlete.

**Comment by JMurphyWeb** [comment]
This issue does not include estimates for implementing the docusign flow.

**Comment by JMurphyWeb** [comment]
hoping this is now testable

**Comment by jonscottfilm** [comment]
working!
