### ISSUE TITLE
Re-send Verification Email

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#40]
As a contractor/project manager,
I would like the ability to re-send a verification email,
So that I can still verify my account even if I delete the original email

**Comment by jackcarlisle** [comment]
@jonscottfilm assigning to you for testing. Please comment below if there are any bugs with this flow and we will take a look. Otherwise if you're happy with the implementation, please close this issue.

**Comment by jonscottfilm** [comment]
Working. Closing.
