### ISSUE TITLE
Merge multi documents 

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#401]
Accepting an offer should merge all necessary documents, not only the contract.

Document logic:
@jonscottfilm could you please add the document logic to this issue (how does the app know which documents need to be merged in a given offer)

Putting a day on this a bit prematurely given we don't know the number of documents and the logic that is needed.

This issue covers the merging only

**Comment by jonscottfilm** [comment]
Logic per our project document sub-sections:

**Deals** - contract, and offer specific riders, eg: box rental form, equipment rental form, vehicle allowance form, all if applicable to the deal.

**Forms** - ALL forms get sent. Eg, sign the company Health & Safety Policy, .

**Info** - send all, force contractor to view, or at least acknowledge they've viewed. Bullying and Harassment Procedure/helpline, Studio parking/security info, etc.

**Comment by jonscottfilm** [comment]
Hi. I'm unable to add any document type other than a 'Deal', so am unable to test merging multiple documents. Only offers PAYE & Schedule-D.

**Comment by JMurphyWeb** [comment]
ok that should be added now

**Comment by jonscottfilm** [comment]
Fixed, although it looks like a different colour banner, and slightly different size gap from the 'Upload a project document' box. Maybe clear-up in Sp4+?

**Comment by JMurphyWeb** [comment]
![screen shot 2017-06-26 at 12 56 20](https://user-images.githubusercontent.com/12638261/27538222-e148b884-5a6e-11e7-8cd0-580bdd0aaed9.png)

**Comment by JMurphyWeb** [comment]
fixed

**Comment by jonscottfilm** [comment]
working
