### ISSUE TITLE
Signing: Multiple documents per offer

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#403]
As a contractor,
I can sign all necessary documents, not only the contract

Merging covered in #401

**Comment by JMurphyWeb** [comment]
We can now sign all relevant documents

**Comment by jonscottfilm** [comment]
Yes working, but... we need to make this ONE envelope for signing. Next challenge.

As expected, _too_ confusing for users to receive multiple emails and envelopes to sign. Needs to be 1 email, one envelope, multiple documents.

Costly the current way, too! :)

**Comment by JMurphyWeb** [comment]
@jonscottfilm multiple documents in one envelope is not related to this issue. please close if you are happy with the result of multiple merges.
