### ISSUE TITLE
PM can view contractors supporting documents

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#405]
As a PM, 
if a contractor accepts their contract then I can view their supporting documents in the offer view.

Startpack info (excluding documents) covered in #17

**Comment by jonscottfilm** [comment]
We feel this is our new priority order for rest of this week:

- View supporting documents #405
- Contract Logic #409 
- One combined Docusign envelope #429

**Comment by jackcarlisle** [comment]
List of possible supporting documents to be shown:

- Passport image
- Box rental inventory list
- Equipment rental inventory list
- Vehicle insurance
- P45
- Schedule D letter
- Loan out company certificate

**Comment by jonscottfilm** [comment]
Get in! Working!

(thoughts (for new/existing issues, @JMurphyWeb): 

- _view_ in new tab (in Sp4+) option. 
- 'download all' button, option?)

**Comment by JMurphyWeb** [comment]
sound good @jonscottfilm 

Please issue  them up independently and prioritise
