### ISSUE TITLE
Add 2 more file upload fields: Driving Licence and Proof of Vehicle Insurance for Business Use.

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#406]
Add 2 file upload fields: Driving Licence and Proof of Vehicle Insurance for Business Use.

Conditional based on IF getting vehicle allowance.

**Comment by jonscottfilm** [comment]
There's a duplication of vehicle insurance field now:

![image](https://user-images.githubusercontent.com/28431542/27803246-78a130b0-6020-11e7-8caf-f41ce34f0129.png)

And we can remove the unnecessary labels, please:

Vehicle insurance image
Vehicle business use insurance image
Vehicle license image
(along with the others listed in #444)

And most importantly, Licence is spelt wrong... :) C not S. Ta.

**Comment by jackcarlisle** [comment]
@jonscottfilm the second insurance field is the proof of vehicle insurance for business use that is in the title of this issue. It isn't named quite correctly in the view but are you saying that this should be removed?

**Comment by jonscottfilm** [comment]
Hey @jackcarlisle . I see, umm, it's one and the same document, but I see your point.

I think maybe we just label it, something like:  

**'Upload a file of your vehicle insurance (for business use if you receive vehicle allowance)'**

Long-term, this can be a conditionally-appearing field.
(cc @beccacca )

**Comment by jonscottfilm** [comment]
Per this morning's Hangout, the 1 label can be: 

**Upload a file of proof of vehicle insurance for business use**

(i.e. - you can lose the brackets)

@jackcarlisle - I see you've just merged the view uploaded files in the Startpack view - which looks great!

**Comment by jonscottfilm** [comment]
Working, bar this relabel: https://github.com/karmaradio/karma/issues/406#issuecomment-312874055
Thanks.

**Comment by jonscottfilm** [comment]
Done. Closing!
