### ISSUE TITLE
multiple merge logic

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#409]
When a contractor accepts an offer the correct documents should appear:

- [x] Only one contract - not all
- [x] Only merge and display the necessary forms
- [x] Loan out company
- [x] Don't attempt to merge and display all info documents

**Comment by JMurphyWeb** [comment]
@jonscottfilm can  you assist in laying out the logic here?

Contract (Deal) logic:
      "DIRECT HIRE",
      "PAYE",
      "SCHEDULE-D",
      "LOAN OUT",
      "CONSTRUCTION DIRECT HIRE",
      "CONSTRUCTION PAYE",
      "CONSTRUCTION SCHEDULE-D",
      "CONSTRUCTION LOAN OUT",


Form logic:
      "BOX RENTAL FORM" - if box rental allowance is checked in offer
      "EQUIPMENT RENTAL FORM", - if equipment rental allowance is checked in offer
      "VEHICLE ALLOWANCE FORM", - if vehicle allowance is more than 0 in offer

**Comment by JMurphyWeb** [comment]
Work has been started on the first two checkboxes

**Comment by jonscottfilm** [comment]
Contracts can only ever be: 

PAYE
SCHEDULE-D
**or**
LOAN OUT

And PAYE and Schedule-D are _usually_ put onto the same Contract template, known as 'DIRECT HIRE'.

You did used to have Loan Out as an uploadable project document type, but think it got removed when you were testing merging. As did all the forms and info options.

Re: 'Don't attempt to merge and display all info documents'
When will all info documents be displayed to the contractor?

**Comment by JMurphyWeb** [comment]
When they press accept. We will merge all relevant documents (contract + conditional forms) and display them along with the info documents.

Info's don't need to be signed do they?

**Comment by JMurphyWeb** [comment]
@jonscottfilm sorry just to confirm contract logic:

We use the offer to determine the default contract type:
PAYE -> determined by offer (job title + dept)
SHEDULE-D -> determined by offer (job title + dept)

Which can then be overridden with a loan out contract:
LOAN OUT -> overrides the original contract type when .... ? (what conditions need to be met here)

**Comment by JMurphyWeb** [comment]
@jackcarlisle i added the loan-out contract logic to a new issue: #412

**Comment by jonscottfilm** [comment]
Tested. Something odd occurring here, which you may already know about.

![image](https://user-images.githubusercontent.com/28431542/27488732-0232330e-5830-11e7-9e96-c1f3a05faaa0.png)

Still allowed me to download, and initiate DS process, but:

![image](https://user-images.githubusercontent.com/28431542/27488792-3485c1e0-5830-11e7-9c83-e80d9448f7a6.png)

**Comment by JMurphyWeb** [comment]
@jonscottfilm that could be due to old data confusing matters? looks strange and we haven't experienced it before. might have to erase all offers and all merged documents if that is ok?

**Comment by jonscottfilm** [comment]
Gotya. Will try.

**Comment by JMurphyWeb** [comment]
@jonscottfilm I was suggesting that we clear the db.. Is that ok?

**Comment by jonscottfilm** [comment]
Thought you might have meant that. Yes, go for it.

**Comment by JMurphyWeb** [comment]
hoping this isn't necessary but will probably do it this week at somepoint anyway

**Comment by jonscottfilm** [comment]
Had this issue tonight. Could be due to OLD PAYE document.

![image](https://user-images.githubusercontent.com/28431542/27557077-2183224a-5ab0-11e7-959c-c7ad6c31a914.png)

Since had success using a different project and documents.

**Comment by jackcarlisle** [comment]
@jonscottfilm What was the issue here? Were you expecting a different contract type to be there?

**Comment by jonscottfilm** [comment]
The bug was that I'd hit Accept, it threw an error message, but still showed the merged document, AND Accept/Reject buttons still.

**Comment by JMurphyWeb** [comment]
ok. I'm going to clear the production db. Is it ok to attempt to replicate this issue after that. if it happens again, let us know how to replicate (we may need the form that you are using).

**Comment by JMurphyWeb** [comment]
OK production DB has been reset.

**Comment by jonscottfilm** [comment]
Multiple merge logic working (for PAYE, not LOAN OUT) #412 

![image](https://user-images.githubusercontent.com/28431542/27595534-d9066c3e-5b54-11e7-8a17-f9e14c3e5cdd.png)

**Comment by JMurphyWeb** [comment]
@jonscottfilm this should be testable now.

**Comment by jonscottfilm** [comment]
working!
