### ISSUE TITLE
Loan out contract type

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#412]
If a contractor uses a loan out company, 
The application should set their contract_type to `loan out company`,
So that when we merge their documents, the correct contract is selected for merging.

Tasks:
- [x] Add loan out company to the dropdown of document names when adding documents to project
- [x] Add loan out company checkbox/radio to startpack and `use_loan_out_company?` to startpack table
- [x] If checkbox is checked, ensure the 3 related fields are required before allowing accept
- [x] When responding to an offer, if `use_loan_out_company?` is true, update the offer to represent the new contract type
- [x] The offer will still say `contract type: PAYE`. We can add some logic to the view to overwrite this if`use_loan_out_company?` is true

**Comment by jonscottfilm** [comment]
First test. _Think_ I got all elements in place. Loan Out template in project. Filled all 3 Loan Out fields.

Result: 
(only box rental (correctly), but no Loan Out Contract. Tried loggin-in/out too. Nada)

![image](https://user-images.githubusercontent.com/28431542/27593683-acc27cda-5b4f-11e7-9285-9f84996044ce.png)

**Comment by jonscottfilm** [comment]
Also, the NDA (form) wasn't presented in the offer view at all.

Both docs (Loan Out template & NDA), have approval chains attached to them.

**Comment by JMurphyWeb** [comment]
@jonscottfilm the loan out logic is now in and testable

**Comment by JMurphyWeb** [comment]
@jackcarlisle not sure about the NDA stuff? https://github.com/karmaradio/karma/issues/412#issuecomment-311385395

**Comment by jonscottfilm** [comment]
Will test loanout.

**Comment by jonscottfilm** [comment]
Working! & additional form (NDA)
