### ISSUE TITLE
Embedded Signees in document

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#413]
Add embedded signees to the document so signees cannot sign in the wrong place.

Awaiting document and prioritisation from @jonscottfilm 

Difficult to time estimate for now.

**Comment by jonscottfilm** [comment]
I'll send you a file with embedded signature tags.

I've realised that my experience in doing embedded sigs is in Word, make font size 1, and white (or same colour as background). So, I'm not 100% if it works the same way in PDF.

**Comment by JMurphyWeb** [comment]
I'll quickly test this with the document that you sent over.

**Comment by JMurphyWeb** [comment]
I got the following error: flatten\nWarning: 
`input PDF is not an acroform, so its fields were not filled.\n\n`

**Comment by JMurphyWeb** [comment]
Seems like the tool we use can only merge 'acroform' types as opposed to 'XFA forms'... There may be a way around this but for now I will leave this here.

Possible solution: https://stackoverflow.com/questions/17226484/pdftk-and-xfdf-file-not-filling-in-form

**Comment by JMurphyWeb** [comment]
@jonscottfilm this is looking like more work than we hoped.. Moving back into Sprint 4 additions for you to prioritise (wasn't in original scope)

**Comment by JMurphyWeb** [comment]
@jonscottfilm it would be great to test this if possible.

**Comment by jonscottfilm** [comment]
Sorry, what am I testing, and how?

**Comment by JMurphyWeb** [comment]
@jonscottfilm embedded signature fields.

`signee_1`, `-2`, etc should be enough to trigger it.

**Comment by jonscottfilm** [comment]
Working! Closing!
