### ISSUE TITLE
Custom name for document uploads

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#414]
Documents attached to a project may need custom names as they don't fit into one of the options.

If these documents are 'info' only, then this should be less work.  Probably will require a `custom_name` field adding to the DB and some additional work on the UI.

@jonscottfilm please edit/add priority as you wish. Adding to backlog milestone

**Comment by jonscottfilm** [comment]
MVP workaround will be to add ALL possible _generic_ document-type names I can think of, which should then suit most purposes?

**Comment by JMurphyWeb** [comment]
or supply an 'other' and ask them to merge documents together?

**Comment by jonscottfilm** [comment]
Needs the option for multiple 'other' options.
Some shows might have 1 or 2 info docs, some might have 12.

**Comment by jonscottfilm** [comment]
linked to #436

**Comment by jonscottfilm** [comment]
done! _(I think. Pretty sure)_
