### ISSUE TITLE
add signees to project formatting bug

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#417]
<img width="1181" alt="screen shot 2017-06-23 at 12 07 37" src="https://user-images.githubusercontent.com/12638261/27479639-a47809be-580c-11e7-9d9d-289d3c1dae84.png">

Looks weird

**Comment by jonscottfilm** [comment]
linked to:
https://github.com/karmaradio/karma/issues/393#issuecomment-310059099
and
https://github.com/karmaradio/karma/issues/393#issuecomment-310520434

**Comment by JMurphyWeb** [comment]
<img width="788" alt="screen shot 2017-06-23 at 14 56 30" src="https://user-images.githubusercontent.com/12638261/27485351-4fb9893a-5824-11e7-8dfa-ea23f17f17d7.png">

**Comment by jonscottfilm** [comment]
I know you're gonna tell me to make a new issue, but... 

This is the wrong wording. 'Add signees to this document, in the order of approval'.
![image](https://user-images.githubusercontent.com/28431542/27559843-ed1d8dc4-5ab9-11e7-8b0b-f5db032b26bd.png)

It belongs in this view:
![image](https://user-images.githubusercontent.com/28431542/27559877-06eea0b2-5aba-11e7-926a-5cf9c11c03a7.png)

**Comment by JMurphyWeb** [comment]
updated and changed the incorrect one to 'add signees to this project'

**Comment by jonscottfilm** [comment]
Fixed. Thanks.
