### ISSUE TITLE
View new offer bug

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#423]
Bug when viewing a new offer as reported by @jonscottfilm

**Comment by JMurphyWeb** [comment]
just came from treating info documents the same way that we treat deal and form documents..

**Comment by JMurphyWeb** [comment]
@jonscottfilm why is this no longer in please test?

**Comment by jonscottfilm** [comment]
Just wanted to make it go away, so I closed it!

No, seriously - I don't know what the 'view new offer bug' is, which I supposedly reported...

**Comment by JMurphyWeb** [comment]
Clicking on an offer crashed the app a few days ago. you reported it in slack.

**Comment by jackcarlisle** [comment]
@jonscottfilm let us know after testing

**Comment by JMurphyWeb** [comment]
if you can click on an offer, this is fixed...

**Comment by jonscottfilm** [comment]
Ok. Fixed.
