### ISSUE TITLE
Docusign timeout bug

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#425]
![screen shot 2017-06-26 at 11 27 50](https://user-images.githubusercontent.com/12638261/27536610-dfd56db4-5a67-11e7-9e53-39130f3bca85.png)

There is an intermittent timeout which results in the above error being displayed. However the Docusign flow does get initiated so timeout seems to be on our side.

`{:error, %HTTPoison.Error{id: nil, reason: :timeout}}`

At the moment we should be allowing 20 seconds before timing out: 
`HTTPoison.post(url, body, headers(), timeout: 20000)`

**Comment by JMurphyWeb** [comment]
difficult to test but it appears we should be using ` HTTPoison.post(url, body, headers(), recv_timeout: 10000) ` for configuring response timeouts (from the docs https://github.com/edgurgel/httpoison)

**Comment by JMurphyWeb** [comment]
After testing on a poor internet connection the new options seems to have fixed it.

**Comment by jonscottfilm** [comment]
Not sure how to test this, but we've not seen it yet!

**Comment by JMurphyWeb** [comment]
yeah it is closable really 😄
