### ISSUE TITLE
Multiple documents sent via 1 combined docusign envelope

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#429]
For cleanest UX, multiple documents should be sent in one combined docusign envelope.

**Comment by JMurphyWeb** [comment]
@jonscottfilm as a starting point, would it make sense to package up the documents which have an identical approval chains into one envelope?

**Comment by JMurphyWeb** [comment]
Try turning on 'Document Visibility' on the DS account so that we can `excludeDocuments: ["1", "3"]` on our recipients.

**Comment by JMurphyWeb** [comment]
After setting Document Visibility to "signer must sign to view document" we get the following error:

`\"message\": \"Freeform signing is not allowed for your account because it conflicts with other settings, please place signing tabs for each signer.\"`

After looking into adding signing tabs for each signer, it seems that this is easily done when using the docusign website, but when using the api, we need to specify the location of each signature:

```
    "recipients": {
        "signers": [{
            "email": "john@email.com",
            "name": "John Doe",
            "recipientId": "1",
            "tabs": {
                "signHereTabs": [{
                    "xPosition": "100",
                    "yPosition": "100",
                    "documentId": "1",
                    "pageNumber": "1"
                }],
                "initialHereTabs": [{
                    "xPosition": "200",
                    "yPosition": "100",
                    "documentId": "1",
                    "pageNumber": "1"
                }]
            }
        }]
    }
```

**Comment by JMurphyWeb** [comment]
@jonscottfilm from what i can see, we cannot 'exclude' signees from an approval chain unless we have signee tabs embedded.

Obviously it would be ideal that we would get both these things in, but I am not sure how we are going to be able to do that.

**Comment by jonscottfilm** [comment]
Right. Embedded is the way. Hmm

**Comment by JMurphyWeb** [comment]
I made some progress with multiple docs. Successfully added 2 docs per envelope. 
- [ ] but approval chain logic seemed to be off, 
- [ ] tests all still need fixing, request times out  
- [ ] displays an error, but the flow does actually get initiated

**Comment by JMurphyWeb** [comment]
body:
```elixir
%{compositeTemplates: [%{document: %{documentBase64: "merged.encoded_file",
       documentId: 25, name: "jackum-mur-PAYE-1.pdf",
       transformPdfFields: "true"},
     inlineTemplates: [%{recipients: %{signers: [%{email: "jmurphy.web+c@gmail.com",
             name: "jackum mur", recipientId: 1, routingOrder: 1,
             tabs: %{signHereTabs: [%{documentId: 25,
                  tabLabel: "signature_1\\*"}]}},
           %{email: "jmurphy.web+first@gmail.com", name: "first signee",
             recipientId: 13, routingOrder: 2,
             tabs: %{signHereTabs: [%{documentId: 25,
                  tabLabel: "signature_2\\*"}]}},
           %{email: "jmurphy.web+second@gmail.com", name: "second signee",
             recipientId: 14, routingOrder: 3,
             tabs: %{signHereTabs: [%{documentId: 25,
                  tabLabel: "signature_3\\*"}]}},
           %{email: "jmurphy.web+third@gmail.com", name: "third signee",
             recipientId: 15, routingOrder: 4,
             tabs: %{signHereTabs: [%{documentId: 25,
                  tabLabel: "signature_4\\*"}]}}]}, sequence: "1"}]},
   %{document: %{documentBase64: "merged.encoded_file", documentId: 26,
       name: "jackum-mur-FORM 1-1.pdf", transformPdfFields: "true"},
     inlineTemplates: [%{recipients: %{signers: [%{email: "jmurphy.web+c@gmail.com",
             name: "jackum mur", recipientId: 1, routingOrder: 1,
             tabs: %{signHereTabs: [%{documentId: 26,
                  tabLabel: "signature_1\\*"}]}},
           %{email: "jmurphy.web+second@gmail.com", name: "second signee",
             recipientId: 14, routingOrder: 2,
             tabs: %{signHereTabs: [%{documentId: 26,
                  tabLabel: "signature_2\\*"}]}}]}, sequence: "2"}]}],
  emailBlurb: "Please sign the document using link provided.",
  emailSubject: "Karma document sign", status: "sent"}
```

**Comment by JMurphyWeb** [comment]
approval chain logic seems to be fixed.

**Comment by JMurphyWeb** [comment]
Looking into the timeout now. I am testing it on my home internet connection and 30seconds isn't long enough. 40 seconds is.

With such a long wait, it would be best if we can have a front end loading page for these specific actions that take a long time to run.

**Comment by JMurphyWeb** [comment]
tests fixed

**Comment by JMurphyWeb** [comment]
@jonscottfilm beware this signing feature takes its time. (around 40 seconds on my connection)

See #462

**Comment by jonscottfilm** [comment]
Understood. https://github.com/karmaradio/karma/issues/429#issuecomment-312919817
Loading screen good idea., or at least a warning notice.

**Comment by JMurphyWeb** [comment]
@jonscottfilm please prioritise #426 

Also please log how long it takes between pressing the 'Sign Documents' button and getting a response.

**Comment by jonscottfilm** [comment]
https://github.com/karmaradio/karma/issues/429#issuecomment-313036964 will log and then prioritise #462.

**Comment by jonscottfilm** [comment]
About 10 secs for 2 documents https://github.com/karmaradio/karma/issues/429#issuecomment-313036964

**Comment by jonscottfilm** [comment]
So multi-docs in 1 envelope worked, but embedded sigs didn't. I wonder if that's because not all docs in my example, had embedded sig tags, so DS forced the 'place your own signature' option. However, the doc with embedded sig tag, _still didn't_ work.

Also - this is merging all docs into ONE document, rather than separate documents in 1 envelope...

**Comment by jonscottfilm** [comment]
https://github.com/karmaradio/karma/issues/429#issuecomment-313050609 They _appear_ as merged, but they download as separate files, with filenames! Result!

Need to discuss the tweaking of Docusign subject/body/filename wording. #434

**Comment by JMurphyWeb** [comment]
@jonscottfilm so did this pass tests? is it closable or any work to be done on it?

**Comment by jonscottfilm** [comment]
Just double-checking with a 3rd document - Contract, **Box Rental** and NDA. 
Sure I've seen it handle 3 before, in which case after a quick retest, I will then close this.

**Comment by jonscottfilm** [comment]
Adding Box Rental to the merge of multi-docs, doesn't seem to work for me.

![image](https://user-images.githubusercontent.com/28431542/27912022-3da199ca-6253-11e7-880e-f7cba6c613c7.png)

![image](https://user-images.githubusercontent.com/28431542/27912035-488db1e8-6253-11e7-9857-03a61c24d454.png)

Box Rental form, with approval chain, def in project.

**Comment by jonscottfilm** [comment]
Any thoughts on this @JMurphyWeb ?

**Comment by JMurphyWeb** [comment]
was it permitted in the offer?

**Comment by jonscottfilm** [comment]
yes, per bottom of 2nd screengrab

**Comment by jonscottfilm** [comment]
Working for Start Form, Contracts (certainly PAYE, Sched-D and Loanout (yet to test rest)), BUT, it doesn't seem to be adding Box Rental or Equipment Rental to the multiple-documents to be merged.

Box and Equipment part of this deal:

![image](https://user-images.githubusercontent.com/28431542/27995623-af51f272-64c9-11e7-958c-6a16b79a1e0a.png)

![image](https://user-images.githubusercontent.com/28431542/27995621-a8a575f2-64c9-11e7-9a6e-f60a2ae8cbc1.png)

But only receive Start Form, Contract, NDA:

![image](https://user-images.githubusercontent.com/28431542/27995659-344b8290-64ca-11e7-8683-a384adce31aa.png)
