### ISSUE TITLE
Overlapping file-upload filename bug in Startpack view

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#432]
Overlapping filename file-upload bug in startpack view.

![image](https://user-images.githubusercontent.com/28431542/27592055-6a4ac474-5b4b-11e7-91fa-e809ef0edefa.png)

**Comment by jackcarlisle** [comment]
@jonscottfilm I've just fixed this, will be testable after next PR merge

**Comment by jonscottfilm** [comment]
Marv. Thanks!

**Comment by jonscottfilm** [comment]
working
