### ISSUE TITLE
Docusign email content

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#434]
DS email content, please amend to:

**Subject:**
Project_codename - for signature: User_first_name User_last_name, Offer_job_title (Offer_department)

**Body:**
Dear User_first_name User_last_name,

Please click 'review document' above, to Docusign: 

(insert filename in format): **'User_first_name User_last_name, Offer_job_title (Offer_department) - Offer_daily_or_weekly, Offer_contract_type, start: offer_start_date'**

**Comment by jonscottfilm** [comment]
I've re-prioritised this, to squeeze in before you finish today, @JMurphyWeb :)

Discuss on Hangout.

**Comment by JMurphyWeb** [comment]
<img width="576" alt="screen shot 2017-07-06 at 14 39 10" src="https://user-images.githubusercontent.com/12638261/27913745-fa62122e-6258-11e7-99a0-0e7f642fb3fc.png">


<img width="617" alt="screen shot 2017-07-06 at 14 38 52" src="https://user-images.githubusercontent.com/12638261/27913726-f048b536-6258-11e7-8eb6-1f38ae060e25.png">

**Comment by jonscottfilm** [comment]
Understood. after the colon, would be the merged filename:

'User_first_name User_last_name, Offer_job_title (Offer_department) - Offer_daily_or_weekly, Offer_contract_type, start: offer_start_date'

I've noticed, 'for signature' is not ideal, because it's the same email subject as when the fully executed document comes back to you.... _not_ for signature, but already signed... hmm

**Comment by jonscottfilm** [comment]
How about?

Subject:
Project_codename - agreement: User_first_name User_last_name, Offer_job_title (Offer_department)

**Comment by JMurphyWeb** [comment]
filename:

<img width="488" alt="screen shot 2017-07-06 at 14 49 21" src="https://user-images.githubusercontent.com/12638261/27914213-5ffd8cc0-625a-11e7-8dd9-a5e3f9b384d7.png">

**Comment by jonscottfilm** [comment]
cool. can we force title case of name, or maybe ALL CAPS is easier?
and date format '20 Jun, 2017' ?

**Comment by JMurphyWeb** [comment]
done all except date

**Comment by jonscottfilm** [comment]
This needs amending. 

Because of the combined envelope of multiple documents, the files all get named the same, (bar the original document name) - which is not desired.

**Filenames**
Longterm, we'd like a custom filename for each file, based on that file.

MVP solution is, name all files in the format:
'USER_FIRST_NAME USER_LAST_NAME, Offer_job_title (Offer_department) - document name'
eg: 'JONATHAN SCOTT, Production Coordinator, (Production) - Loan Out'

![image](https://user-images.githubusercontent.com/28431542/27997247-5a719fdc-64ec-11e7-90b0-586c86489ff6.png)


**Email blurb**
Filenames aren't being listed in the body. Is that easy to fix? 
If not, let's just keep it simple:

'Dear User_first_name User_last_name,

Please follow the instructions above, to review your documents.

Thank you.

The Production Office'
