### ISSUE TITLE
Fix offer recipient email error

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#437]
Idiots (like me) can enter AND send (or _thinks_ it has) an incomplete email address in the 'new offer recipient email' field.

eg:
![image](https://user-images.githubusercontent.com/28431542/27609528-0365244c-5b83-11e7-9e71-96b7191d13af.png)

![image](https://user-images.githubusercontent.com/28431542/27609542-109812dc-5b83-11e7-9b86-3ab15fd7c5a6.png)

**Comment by jackcarlisle** [comment]
lowercase all email addresses -> links to #444

**Comment by jonscottfilm** [comment]
Working!
