### ISSUE TITLE
investigate programatically adding signHere tabs via Docusign API

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#440]
When we send our merged forms to Docusign, we want them to have `signHere` tabs in the relevant places.

Following [this guide](https://www.docusign.com/developer-center/explore/features/stick-etabs) we have been trying to follow method 3, which states:  

>  There are two different types of transformations you can perform - 1) you can transform pdf form fields into DocuSign tabs and 2) you can transfer the values contained in PDF fields into DocuSign tabs

from this we have been going down the option 2) route.

We have added fields in the document with the name `signature_1` and with a pre-filled value of `signature_1` (have attempted making that value read-only and not read-only). Have also set the `transformPdfFields: "true"` as per instructions.

Here is the body of the post request being made:

```js

{
  emailBlurb: "Please sign the document using link provided.",
  emailSubject: "Karma document sign",
  documents: [
    {
      documentBase64: "encoded",
      documentId: 1,
      name: "jackum-mur-PAYE-1.pdf",
      transformPdfFields: "true"
     }
  ],
  recipients: {
    signers: [
      {
        email: "jmurphy.web+c@gmail.com",
        name: "jackum mur",
        recipientId: 1,
        routingOrder: 1,
        tabs: {
          signHereTabs: [
            {
              documentId: "1",
              pageNumber: "1",
              tabLabel: "signature_1"
            }
          ]
        }
      },
      {
        email: "jmurphy.web+first@gmail.com", 
        name: "first signee",
        recipientId: 2,
        routingOrder: 2,
        tabs: {
          signHereTabs: [
            {
              documentId: "1", 
              pageNumber: "1",
              tabLabel: "signature_2"
            }
          ]
        }
      },
      {
        email: "jmurphy.web+second@gmail.com", 
        name: "second signee",
        recipientId: 3, 
        routingOrder: 3,
        tabs: {
          signHereTabs: [
            {
              documentId: "1", 
              pageNumber: "1",
              tabLabel: "signature_3"
            }
          ]
        }
      },
  status: "sent"
}

```

This sends the document around the chain, but the first signee's signHere tab is at the top left of the contract, not where the `signature_1` field is.

**Comment by JMurphyWeb** [comment]
Question also asked on [SO](https://stackoverflow.com/questions/44827271/docusign-api-signhere-tabs-not-converting-form-fields-into-tabs)

**Comment by JMurphyWeb** [comment]
Response from Docusign:
```
{body: "{\r\n  \"envelopeId\": \"98fb1999-8xxxx38ad\",\r\n  \"uri\": \"/envelopes/98fb199xxxxd\",\r\n  \"statusDateTime\": \"2017-06-29T15:49:47.7900000Z\",\r\n  \"status\": \"sent\"\r\n}",
  headers: [{"Cache-Control", "no-cache"}, {"Content-Length", "195"},
   {"Content-Type", "application/json; charset=utf-8"},
   {"X-RateLimit-Reset", "1498752000"}, {"X-RateLimit-Limit", "1000"},
   {"X-RateLimit-Remaining", "997"},
   {"X-DocuSign-TraceToken", "e82xxx6f8de"},
   {"Date", "Thu, 29 Jun 2017 15:49:48 GMT"},
   {"Strict-Transport-Security", "max-age=31536000; includeSubDomains"}],
  status_code: 201}
```

**Comment by jonscottfilm** [comment]
**Response from DS support:**

{
  emailBlurb: "Please sign the document using link provided.",
  emailSubject: "Karma document sign",
  status: "created",
  compositeTemplates: [
    {
      inlineTemplates: [
        {
          sequence: "1",
          recipients: {
            signers: [
              {
                email: "jmurphy.web+c@gmail.com",
                name: "jackum mur",
                recipientId: "1",
                routingOrder: "1",
                tabs: {
                  signHereTabs: [
                    {
                      tabLabel: "signature_1\\*"
                    }
                  ],
                  textTabs: [
                    {
                      tabLabel: "signature_1\\*"
                    }
                  ]
                }
              },
              {
                email: "jmurphy.web+first@gmail.com", 
                name: "first signee",
                recipientId: "2",
                routingOrder: "2",
                tabs: {
                  signHereTabs: [
                    {
                      tabLabel: "signature_2\\*"
                    }
                  ],
                  textTabs: [
                    {
                      tabLabel: "signature_2\\*"
                    }
                  ]
                }
              },
              {
                email: "jmurphy.web+second@gmail.com", 
                name: "second signee",
                recipientId: "3", 
                routingOrder: "3",
                defaultRecipient: "true",
                tabs: {
                  signHereTabs: [
                    {
                      tabLabel: "signature_3\\*"
                    }
                  ],
                  textTabs: [
                    {
                      tabLabel: "signature_3\\*"
                    }
                  ]
                }
              }
            ]
          }
        }
      ],
      document: {
        documentBase64: "{{pdfFormBytes}}",
        documentId: "1",
        name: "jackum-mur-PAYE-1.pdf",
        transformPdfFields: "true"
      }
    }
  ]
}

**Comment by jonscottfilm** [comment]
[p60-form.pdf](https://github.com/karmaradio/karma/files/1112852/p60-form.pdf)

[p60-form.txt](https://github.com/karmaradio/karma/files/1112856/p60-form.txt)

**Comment by codingdawg** [comment]
Did the response from DocuSign support resolve your issue?

**Comment by JMurphyWeb** [comment]
I have just had it work for the first time 🎉 

<img width="1123" alt="screen shot 2017-07-01 at 08 14 30" src="https://user-images.githubusercontent.com/12638261/27760016-c7673e02-5e35-11e7-8f10-144b62271cb2.png">

(updateing SO question now @codingdawg thanks

**Comment by JMurphyWeb** [comment]
```elixir
%{compositeTemplates: [
  %{document: 
     %{documentBase64: "encoded", 
       documentId: 1,
       name: "jackum-mur-PAYE-1.pdf", transformPdfFields: "true"},
       inlineTemplates: [
         %{recipients: 
            %{signers: [
              %{email: "jmurphy.web+c@gmail.com",
                name: "jackum mur", recipientId: 1, routingOrder: 1,
                tabs: 
                  %{signHereTabs: [%{documentId: "1", pageNumber: "1", tabLabel: "signature_1\\*"}],
                      textTabs: [%{tabLabel: "signature_1\\*"}]}},
             %{email: "jmurphy.web+first@gmail.com", 
                 name: "first signee",
                 recipientId: 2, routingOrder: 2,
                 tabs: 
                   %{signHereTabs: [%{documentId: "1", pageNumber: "1", tabLabel: "signature_2\\*"}],
                       textTabs: [%{tabLabel: "signature_2\\*"}]}},
}]}, 
  sequence: "1"}]}],
  emailBlurb: "Please sign the document using link provided.",
  emailSubject: "Karma document sign", 
  status: "sent"}
```

**Comment by JMurphyWeb** [comment]
I want to quickly run through the flow without using the text tabs to determine what they do.

Also need to do some research on the pageNumber as we will not always know the page number of each signature.

**Comment by jonscottfilm** [comment]
Hmm. Page number would present a problem. _Surely_ can't be prerequisite.

**Comment by JMurphyWeb** [comment]
Recipient Id

> Unique for the recipient. It is used by the tab element to indicate which recipient is to sign the Document.

Poses a bit of an issue because our signee ids will overlap with user ids. If the `recipientId` is used only in the context of an envelope, we can create increment signee_id's and always set the contractor with `recipientId` of 1

**Comment by JMurphyWeb** [comment]
For now just going to take the signee id and plus 1 to it to create the `recipientId`. Contractors will always have `recipientId` of 1.

**Comment by jonscottfilm** [comment]
Not unless they are Loan Out, in which case the Lender usually signs first...

**Comment by jonscottfilm** [comment]
And an Agent would sign/give approval first, before the crew member knows it's good to sign.

**Comment by JMurphyWeb** [comment]
that's fine - we can increase the id's by 5 so we have room to insert other signees.

**Comment by JMurphyWeb** [comment]
Closing as investigation is complete 😄
