### ISSUE TITLE
General presentation fixes

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#444]
#**Priority # - Description -         View**

- [ ]    1  -  Formatting numbers (1000 comma separators and 2 decimal places)  -  Offers (project and contractor) **Can't see 2 decimal places yet. Feel needs space between currency symbol and first number**
- [x]    1.1  -  Regrouping/ordering of offer fields  -  Offers (project and contractor)
- [x]    1.2  -  Label: Shoot Start Date should be Start Date  -  Offer details within offer views (project and contractor)
- [x]    1.3  -  Password format hint in placeholder:  '#characters, capital, symbol etc'  -  Login
See you've done for create account, bu feel it should be present for login password field, also.
**Edit password placeholder text, as it's cropped on mobile. See screengrab below. New: 'Minimum 8 characters, inc: 1 capital, 1 digit + 1 special'**

- [x]    1.4  -  Help email link in footer  -  System wide
**Talked about, and sent you the formstack form link, but don't see Help in the footer. Help | Terms | Privacy | info@teamengine.co.uk**
- [x]    1.5  -  Student Loan question, correct: You am (are) repaying my (your) Loan direct to the Student Loan Co.  -  Startpack
- [x]    1.6  -  Contractor offer tile, change email address to Project codename  -  Dashboard (contractor)
- [x]    1.6.1  -  Contractor offer tile: **Fix: offer rate is only showing 1 decimal point**
**IF easy, be great to add offer update date in small text, grey like job title, beneath offer rate: 'Updated at: 5/7/2017'**
- [x]    1.7  -  Add checkbox to 'Your vehicle details for site access and parking:', checked by default  -  Startpack
**Check 'Do you have a vehicle?' box by default please**
- [x]    1.8  -  'Offer for jono@me.com' label, move to top of view (like Project offer view)  -  Offer (contractor)
- [x]    1.9  -  Remove unnecessary labels: 'Vehicle insurance image'  -  Startpack
- [x]    1.91  -  Remove unnecessary labels: 'P45 image'  -  Startpack
- [x]    1.92  -  Remove unnecessary labels: 'Loan out company cert image'  -  Startpack
- [x]    1.93  -  Revise label: 'Upload an image of your passport' to 'Upload a file of your passport'

- [x]    2  -  Reorder document sub-sections: Contracts (renamed from Deals), Forms, Information  -  Brilliant. Much better. We therefore need to update the labels in the project document dropdown to match: still has Deals > Forms > Info. **SHOULD BE: 'Contracts > Forms > Information' to match above**
- [x]    2.1  -  Breadcrumbs, consistent in all views  -  System wide
**Brilliant! Tiny tweak, 2 views have misaligned breadcrumbs, need shifting tight to left. See below.**
- [x]    2.2  -  Fullname as part of offer  -  Offer views
- [x]    2.3  -  General clean up of placeholders  -  PM offer
**edit Box & Equipment Rental Period: remove 'from hard start date only', replace with '5-day deal'**
**Re-label fields: Box rental period to Box rental terms, and Equipment rental period to Equipment rental terms**
- [x]    2.4  -  Force email format in all email fields (lowercase@me.domain)  -  System wide
**Not working. In create offer view. Also in Create account view, accepted incomplete email address: 'wolfie@gmai.'. Also, red error message in create account password, still says '6 characters' not the new conditions**
- [x]    2.41  -  **Edit label in project & offer (ALL) views: 'Duration', change to 'Shoot duration'** see grab below
- [x]    2.42  -  **Project creation view, placeholder text: 'Project type' replace with 'select...' (all lowercase 'select...' to match others)**
- [x]    2.42  -  **Project creation view, Holiday rate field, replace placeholder 'Select rate'  with 'select...'** 
- [x]    2.44  -  **Startpack view, gender field, replace 'Select one' placeholder with: 'select...'**
- [x]    2.41  -  **Change ALL tile border colour to grey**
- [x]    2.41  -  **Change all instances of 'Signee' or 'Signees' to 'Approver' or 'Approvers'**
- [x]    2.42  -  **In 'Add Signees to document' view, change wording of instruction when there is no signee to: 'Add approver/recipient to this document in order of receipt' (see grab below)**
- [ ]    2.45  -  Rewrite error message: '!Can't Be Blank', to 'Response required'  -  System wide
- [ ]    2.5  -  Telephone fields formatted to accept numbers only  -  System wide
- [x]    2.6  -  Error colour red border around applicable error fields  -  System wide
- [ ]    2.7  -  Make all PDF icons small (like in Startpack view)  -  Project details
- [ ]    2.8  -  Re-add auto-complete functionality in browsers  -  System wide

- [ ]    3  -  Logo clipping on login/create account/forgot password screen.  -  Login
**@jonscottfilm thinks this is the original file, created by Illustrator. _HAS_ sent NEW file**
- [x]    3  -  Fonts all to be Lato  -  System wide (link: https://github.com/karmaradio/karma/issues/383#issue-236656898)
- [ ]    3  -  Move profile info into startpack main body, and rename ALL as 'Profile'  -  Startpack

- [ ]    3  -  Loanout address field: expand to 5 address fields (like primary address)  -  Startpack
- [x]    3  -  Congratulations! Messages only show on first view  -  System wide
- [x]    3  -  NOT NEEDED: Move 'Accepted file types: pdf' warning to below 'Choose file' buttons  -  System wide
- [x]    3  -  Same-width page/boxes  -  System wide
**Example: Dashboard is wider than Startpack page width**

- [ ]    3  -  Contractor offer tile, add 'Updated at: datetime'  -  Dashboard (contractor) (issue repeated at 1.61)
- [ ]    3  -  Reduce size of grey sub-header  -  System wide
- [ ]    3  -  Recolour header  -  System wide
- [ ]    3  -  Replace logo with new colour  -  System wide

**Comment by jonscottfilm** [comment]
1 - formatting of numbers.
Don't think this is done, right?

![image](https://user-images.githubusercontent.com/28431542/27898184-9d4fe656-621c-11e7-9c44-07a97e5cbbd3.png)

**Comment by jackcarlisle** [comment]
@jonscottfilm sorry I'm checking them off while going through the bullet points. I'll assign to you when ready for testing

**Comment by jonscottfilm** [comment]
ah, copy you. sorry, thanks!
(cc: @beccacca )

**Comment by jonscottfilm** [comment]
2 instances of misaligned breadcrumbs:

1
![image](https://user-images.githubusercontent.com/28431542/27931330-be3c73f0-6291-11e7-8976-86a2483cbf47.png)

2
![image](https://user-images.githubusercontent.com/28431542/27931377-f5e1e240-6291-11e7-88ac-042b19f5abdf.png)

**Comment by jonscottfilm** [comment]
Edit password placeholder text to avoid clipping on mobile:

'Minimum 8 characters, inc: 1 capital, 1 digit + 1 special'

![screenshot 9 jul 2017 8_32_23 am](https://user-images.githubusercontent.com/28431542/27992022-6efd0600-6481-11e7-99ce-bfd3e3857259.png)

**Comment by jonscottfilm** [comment]
Change label (all views): 'Duration' to 'Shoot duration'

![image](https://user-images.githubusercontent.com/28431542/27992197-d5c48436-6485-11e7-8a76-4d5589c0347d.png)

**Comment by jonscottfilm** [comment]
Change ALL border colour of TILES to grey:

![image](https://user-images.githubusercontent.com/28431542/27992306-411a24c2-6489-11e7-8d89-202676b561ae.png)

**Comment by jonscottfilm** [comment]
Edit instruction to add signees (now Approvers) to:

'Add approver/recipient to this document in order of receipt'

![image](https://user-images.githubusercontent.com/28431542/27992551-fd6c9402-648e-11e7-8616-b3c94cb04b1a.png)

**Comment by jonscottfilm** [comment]
I will prioritise any remaining items in this Gen Pres Fixes. Some more important than others.

This is _really_ small, and can be put in backlog. They call me 'hawkeye' :)
Per 2.46 above, recolour login link on Create Account screen from blue to light indigo:

![image](https://user-images.githubusercontent.com/28431542/28033631-bf0a990c-65a6-11e7-86d3-5f5f516719b0.png)

**Comment by jonscottfilm** [comment]
I've moved the remaining essential to the top. Others to bottom. I'll move those to own Backlog general fixes at some point.
