### ISSUE TITLE
Add cc recipients (i.e. non-signing) as project signees 

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#448]
Add cc recipients (i.e. non-signing) as project signees. 

Needs to be marked as such eg:

**Current 'add signees' box**
Name FREE TEXT
Email FREE TEXT
Role FREE TEXT

***ADD dropdown of 'Approver type':** (might need to relabel 'signees' as 'Approvers')
1. Approver (signee) (always)
2. Receive fully executed copy (always)
_(potential 3rd option)_
3. Approver (conditional - for example, IF deal done throught agent is checked, agent is to approve that their client (the contractor) is good to sign) _this could just be that they are added as a signer

**Comment by JMurphyWeb** [comment]
@jonscottfilm if we add the approvers such as the agent before the signees, then they will be allocated a signing tab. 

Some MVP-like options:
1. It may be possible to cc the agent when email is first sent? but that wouldn't prevent the contractor receiving the document at the same time.

2. We could add a conditional button next to the 'Sign Documents' button saying 'Send Documents to Agent'. The contractor could then agree with the agent that the contracts are good to go in private, and press the Sign Documents button when they hear back.

3. Alternatively we could just send the docusign email to the agent and not the contractor?


Longer term, we can adapt the flow so that the agent can log into the application and verify the contracts before the approval chain gets kicked off.

**Comment by JMurphyWeb** [comment]
For now I won't be adding 
> 3. Approver (conditional - for example, IF deal done throught agent is checked, agent is to approve that their client (the contractor) is good to sign) _this could just be that they are added as a signer

**Comment by JMurphyWeb** [comment]
Task list:
- [ ] Add dropdown to add signee list
- [ ] Migrate DB to store new info (update schema)
- [ ] Ensure not all approvers become signees
- [ ] Add non signing approvers to the recipients in docusign
- [ ] Test
- [ ] Fix failing tests

**Comment by JMurphyWeb** [comment]
<img width="733" alt="screen shot 2017-07-05 at 09 28 08" src="https://user-images.githubusercontent.com/12638261/27855968-54c9d832-6164-11e7-90ee-e0dc3e892fbf.png">


I will add the `(Recipient)` or `(Signee)` label to this dropdown to make it easier for PM to distinguish

**Comment by jonscottfilm** [comment]
re: https://github.com/karmaradio/karma/issues/448#issuecomment-313022361

Non-signing approvers can be added with the correct DS tag: 

initial (could work for Agent)
cc (receive copy anywhere in the chain)

https://github.com/karmaradio/karma/issues/448#issuecomment-313037415 Looks like a good implementation. 

DS offers for signers to receive documents at the same time, i.e. 'don't sign in order'
Therefore Agent could receive it also as recipient 1 (same time as crew member)

Think cleanest method is IF 'Deal via agent' is checked, make Agent #1 signer.

**Comment by JMurphyWeb** [comment]
@jonscottfilm I am not sure, but this agent business feels like a separate issue. It doesn't affect the flow of a PM adding signees / recipients to documents.

**Comment by JMurphyWeb** [comment]
@jonscottfilm possibly intermediaries can solve our agent deal issue: https://docs.docusign.com/esign/restapi/Envelopes/EnvelopeRecipients/#certifiedDeliveries

And using certified deliveries for the `Recipients` that we have just added:
https://docs.docusign.com/esign/restapi/Envelopes/EnvelopeRecipients/#certified-deliveries-recipient

**Comment by JMurphyWeb** [comment]
Current body:
```elixir
%{document: %{documentBase64: "merged.encoded_file", documentId: 43,
    name: "jackum-mur-PAYE-1.pdf", transformPdfFields: "true"},
  inlineTemplates: [%{recipients: %{certifiedDeliveries: [%{email: "jmurphy@hotmail.com",
          name: "Jack Murphy", recipientId: 22}],
       signers: [%{email: "jmurphy.web+c@gmail.com", name: "jackum mur",
          recipientId: 1, routingOrder: 1,
          tabs: %{signHereTabs: [%{documentId: 43,
               tabLabel: "signature_1\\*"}]}},
        %{email: "jmurphy.web+signee@gmail.com", name: "Jack Murphy",
          recipientId: 21, routingOrder: 2,
          tabs: %{signHereTabs: [%{documentId: 43,
               tabLabel: "signature_2\\*"}]}}]}, sequence: "1"}]}
```

**Comment by jonscottfilm** [comment]
unrelated, but are you using signature_2 there, not signee_2, etc?

**Comment by jonscottfilm** [comment]
did you see this https://github.com/karmaradio/karma/issues/448#issuecomment-313090383? @JMurphyWeb

**Comment by jonscottfilm** [comment]
I _think_ this is working, but hard to tell when you receive ALL docs yourself, as signees and receipients of some chains and not others.... Will test properly later.

**Comment by JMurphyWeb** [comment]
good luck 🌮

**Comment by jonscottfilm** [comment]
Working. Closing
