### ISSUE TITLE
Student Loan radio button bug

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#450]
Uncheck 'check the box if you pay a student loan...' radio button, hides ALL remaining fields on startpack view, not just the student loan-related fields:

![screenshot_20170701-172251](https://user-images.githubusercontent.com/28431542/27763798-899b7f6e-5e82-11e7-887d-f40b69e4251a.png)

**Comment by JMurphyWeb** [comment]
@jonscottfilm I don't understand exactly what you want.

**Comment by jonscottfilm** [comment]
It's hiding TOO much. In the screengrab, you can see that with the box unchecked, all the other fields on the page, i.e. Loan Out Company and Bank Details, are not showing, when they should. You can see the footer.

**Comment by jonscottfilm** [comment]
Last look, this bug was still active.

**Comment by jackcarlisle** [comment]
@jonscottfilm can you post a screenshot please?

**Comment by jonscottfilm** [comment]
Before:
('Check the box if you have a student loan which is not fully repaid' - is checked)

![image](https://user-images.githubusercontent.com/28431542/27831497-e041bc42-60c2-11e7-9b45-77dc5e081aab.png)

After:
('Check the box if you have a student loan which is not fully repaid' - is unchecked)

![image](https://user-images.githubusercontent.com/28431542/27831511-ec663ee4-60c2-11e7-9f03-fa08dc00b964.png)

**Comment by jackcarlisle** [comment]
@jonscottfilm thank you! We'll make sure we get to this soon

**Comment by JMurphyWeb** [comment]
@jonscottfilm this is in review along with the "you am repaying my" copy fix from #444

**Comment by jonscottfilm** [comment]
Yay! Fixed, working, closing!

Longterm - these questions, particularly PAYE & Student Loan need a some separation / header lines to ease UX. I'll add to backlog.
