### ISSUE TITLE
order of updated offer view

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#451]
From Becca, this is the new structure of the offer view:
```
Line number on current view	Offer Details
1	Recipient email:
	
2	Department
3	Job Title
	
4	Contract Type:
	
5	Shoot Start Date:
	
6	Daily or weekly:
7	Working week:
8	Additional Notes:
	
	Fees
	
9	Fee per day inc holiday
12	Fee per day exc Holiday
15	Holiday pay per day
	
13	Fee per week inc holiday
14	Fee per week exc holiday
16	Holiday pay per week
	
10	6th Day fee multiplier
17	6th day fee inc holiday
18	6th day fee exc holiday
	
11	7th day fee mulitplier
19	7th day fee inc holiday 
20	7th day fee exc holiday 
	
	Allowances
	
21	Other deal provisions

22	Box rental description
23	Box rental fee per week
24	Box rental Cap
25	Box Rental Period
	
26	Equipment rental description
27	Equipment rental fee per week
28	Equipment rental cap
29	Equipment rental period
	
30	Vehicle Allowance
```

**Comment by JMurphyWeb** [comment]
I am putting priority 2 but we should follow the priority of the actual issue that this is is raised in.

**Comment by jonscottfilm** [comment]
Unnecessary gap between 9 & 12.
21 to be on a line of it's own.
22-24 (box rental) should be grouped. 
Likewise 26-29.
Inconsistent colons. Colons on all labels. Not on sub-headers, eg: 'Allowances'. Looks like that's how it is now:

![image](https://user-images.githubusercontent.com/28431542/27785169-a5a4cca8-5fd4-11e7-9cec-fbbcadb8778c.png)

**Comment by jackcarlisle** [comment]
@JMurphyWeb where does currency fit in with the new layout?

**Comment by JMurphyWeb** [comment]
I just copied Beccas fields in from slack, can you refer back to that and update if i missed something?

**Comment by jonscottfilm** [comment]
What goes in the 'Contractor Details accepted'?

Accepted:	
Updated at:	27/6/2017
Active:	true
**Contractor details accepted:**

**Comment by jonscottfilm** [comment]
Def feel Recipient's Fullname should be inserted as soon as known:

**Offer for:** {user_first_name} {user_last_name} (replacing email address, or at least being inserted before it when known) eg: {user_first_name} {user_last_name} ({user_email})

**Recipient fullname:** {user_first_name} {user_last_name}
**Receipient email:** {user_email}

(cc @beccacca)

**Comment by jackcarlisle** [comment]
@jonscottfilm contractor details accepted should be removed. And yes we can update the view with the full name of the recipient. I'll do that now

**Comment by jonscottfilm** [comment]
Tweak to grouping of 'offer details' please:

Recipient fullname: 
Recipient email:

Department:
Job Title:

Start Date: (**note - NOT Shoot Start Date**)
Contract Type:
Daily or weekly:
Working week:

Additional notes:

**Comment by jonscottfilm** [comment]
Fields from 'Contract type' to 'Working Week' should be grouped, per https://github.com/karmaradio/karma/issues/451#issuecomment-312634775

**Comment by jonscottfilm** [comment]
Great re recipient name & email.

Is the page title **'Offer for {user_firstname} {user_lastname} ({user_email})'** being put in the grey sub-header, work in progress? 

(it's been removed from it's old position)

**Comment by jonscottfilm** [comment]
Needs this rejig, before closing:
https://github.com/karmaradio/karma/issues/451#issuecomment-312634775
Thanks.

**Comment by jonscottfilm** [comment]
Reorder working. 

Reformat exists in #444. (financial numbers as 2 decimal places, and comma thousand separators. Decimal places NOT to affect whole numbers like '5 days', for example.)
