### ISSUE TITLE
Format of merged number (with currency) field bug

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#457]
Format of merged number (with currency) field, doesn't show correctly on the PDF.

PDF template has no prior-set format. (thought that was the initial reason for error)

This example has Euros in the offer. When the field is edited, in the merged PDF, the Euro then remains. Initial view is a dot in stead of Euro symbol.

![image](https://user-images.githubusercontent.com/28431542/27801248-e5354524-6014-11e7-9839-1b46e7de8010.png)

GBP offers, seem to merge ok, although this is a flattened PDF, not editable fields. Will test same, at some point.

![image](https://user-images.githubusercontent.com/28431542/27801415-d303b4d4-6015-11e7-836b-597c698a3f61.png)

**Comment by jonscottfilm** [comment]
I've given it a Priority 4, because most deals in test projects will be in GBP £.

Not sure what you are passing to the merge doc, but if it is number and the currency, the simple fix might be to not pass the currency, and we just insert the currency of a deal, into ONE box on the contract.

If it's easy to fix, and it's just the format of Karma vs PDF field-format, we should fix it that way.

**Comment by JMurphyWeb** [comment]
this seemed to be fixed for me for euros?

**Comment by jonscottfilm** [comment]
Oh really. I'll test, along with all the other tests, shortly!! Sorry.

**Comment by jonscottfilm** [comment]
done
