### ISSUE TITLE
Re-Style

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#46]
Now that we've received the styling and branding for the application, we can begin to implement it for the current views that we have: 

Styles: #45 

### Re-style existing views to fit with the new styling specs
- [x] Log in 
- [x] Dashboard (offer)
- [x] Dashboard (project)
- [x] Register

**Comment by JMurphyWeb** [comment]
closing as we have implemented a basic style.

Scheduling meeting with designer this week for more advanced design.
