### ISSUE TITLE
loading screen

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#462]
For some actions (signing, merging), there is a long delay. It would be nice to show a loading screen to the user so they don't know that this is normal.

issue became apparent in #429 

@jonscottfilm please prioritise

**Comment by JMurphyWeb** [comment]
<img width="498" alt="screen shot 2017-07-06 at 12 09 49" src="https://user-images.githubusercontent.com/12638261/27908507-13a3b6a8-6244-11e7-821f-e3f708a515f5.png">

MVP solution 🎉

**Comment by jonscottfilm** [comment]
Nice. Think should amend to:

'This process may take up to 30 seconds - please don't navigate away'

**Comment by JMurphyWeb** [comment]
<img width="512" alt="screen shot 2017-07-06 at 12 35 33" src="https://user-images.githubusercontent.com/12638261/27909239-a6b815f8-6247-11e7-94b7-cc3a62510fab.png">

**Comment by jonscottfilm** [comment]
working, closing.
