### ISSUE TITLE
supporting documents always shows pdf icon

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#463]
Even if contractor has uploaded a .png file, it shows the pdf icon at the top of the page.

<img width="1046" alt="screen shot 2017-07-05 at 07 33 33" src="https://user-images.githubusercontent.com/12638261/27851822-6daf1f34-6154-11e7-9172-dd43a6f33a80.png">

**Comment by JMurphyWeb** [comment]
@jonscottfilm priorities please 🙇

**Comment by jonscottfilm** [comment]
easy solution - on icon, replace wording 'PDF', with 'File'.

**Comment by jonscottfilm** [comment]
Sorry, but: 'file' seems a but big, and is it Lato?

**Comment by jackcarlisle** [comment]
@jonscottfilm will change the size and the font now

**Comment by jonscottfilm** [comment]
Sorry! You know I obsess about fonts! :)

**Comment by jonscottfilm** [comment]
Fixed. Closing.
