### ISSUE TITLE
New offer job title bug

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#466]
Had two experiences now when certain job titles won't complete the creation of an offer:

Example: Locations . Locations Assistant.
Make offer, returns error, and clears the job title field.
Experienced same with Transport dept. Can't recall job title.

![image](https://user-images.githubusercontent.com/28431542/27856730-dcf39138-6166-11e7-87f9-74a9227bf154.png)

**Comment by jonscottfilm** [comment]
Production > Production Assistant, fails.

I'm editing an existing offer, which has failed a few times. Will see if happens to NEW offer.

**Comment by jonscottfilm** [comment]
New offer accepts the grade choice, but fails, and no error message on field it has issue with:

![image](https://user-images.githubusercontent.com/28431542/27857135-72c5afd8-6168-11e7-9fde-9e54c38560d1.png)

**Comment by jonscottfilm** [comment]
It might have been a project specific error. 'Star Warts'.

Just succeeded in Coronation Street project:
![image](https://user-images.githubusercontent.com/28431542/27857564-139e247a-616a-11e7-91b8-b814b6e882e5.png)

NOW, I can test embed sigs and multi-doc/1 envelope, @JMurphyWeb :)

**Comment by JMurphyWeb** [comment]
@jonscottfilm please close if this is no longer an issue.

Always add priority and milestone or it will get lost 😟

**Comment by jonscottfilm** [comment]
Fixed. Closing.
