### ISSUE TITLE
Agent deals - documents should be sent via agent

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#470]
If Startpack has agent deal `true`, the agent should also receive the merged documents.

@jonscottfilm can you reiterate your desired (MVP version) implementation?

Are these conditional recipients restricted to agent deals or are there other circumstances that can trigger them?

issue brought up in #465

**Comment by jonscottfilm** [comment]
I'm 99% certain this is restricted to agent deals.

MVP desired solution is Agent receives prior to contractor, for approval of some sort, preferably INITIALS, but signing, alongside agent details area as there is no box for agent signature on the documents.

Only _similar_ scenario I can think of is the sending to the Loan Out Company 'Lender' ideally _prior_ to the contractor. However, MVP (& maybe longterm) Lender can receive **for signature** at same time as contractor, or straight after...

**Comment by JMurphyWeb** [comment]
@jonscottfilm it gets difficult as soon as you require them to have embedded signature or initials fields.

Please add priority.

**Comment by jonscottfilm** [comment]
You mean, conditional embedded signees is difficult?

Could we permanently add agent signee as signee_ID2, then project-added signees from ID3, so ID2 is triggered of condition of 'deal via agent' is matched?

**Comment by JMurphyWeb** [comment]
we could do something like this. Does the agent need to sign it, are initials not enough? Could we just always add initials_agent to the documents?

**Comment by jonscottfilm** [comment]
That's my suggestion. Just some sort of mark of the agents approval, for the contractor to then go on and sign. Agents initials would be sufficient, if not ideal!

**Comment by JMurphyWeb** [comment]
ok ill look into it

**Comment by JMurphyWeb** [comment]
New body:
```elixir
%{compositeTemplates: [%{document: %{documentBase64: "merged.encoded_file",
       documentId: 44, name: "jackum-mur-PAYE-1.pdf",
       transformPdfFields: "true"},
     inlineTemplates: [%{recipients: %{certifiedDeliveries: [%{email: "murphy@hotmail.com",
             name: "Jack Murphy", recipientId: 23}],
          signers: [%{email: "aa", name: "aa", recipientId: 1, routingOrder: 1,
             tabs: %{initialHereTabs: [%{documentId: 44,
                  tabLabel: "agentDocusignInitialHere\\*"}]}},
           %{email: "jmurphy.web+c@gmail.com", name: "jackum mur",
             recipientId: 2, routingOrder: 2,
             tabs: %{signHereTabs: [%{documentId: 44,
                  tabLabel: "signature_1\\*"}]}},
           %{email: "jmurphy.web+signee@gmail.com", name: "Jack Murphy",
             recipientId: 22, routingOrder: 3,
             tabs: %{signHereTabs: [%{documentId: 44,
                  tabLabel: "signature_2\\*"}]}}]}, sequence: "1"}]}],
  emailBlurb: "Please sign the document using link provided.",
  emailSubject: "Karma document sign", status: "sent"}
```

**Comment by JMurphyWeb** [comment]
May need to remove the `DocusignInitialHere` from the initial label

**Comment by JMurphyWeb** [comment]
Agent initials worked ok. The contractor didn't receive the follow up email, after checking the docusign routing, it looks like the `Recipient`  (non signing) has to view the document before it continues around the the chain. Which is not desired behaviour.

**Comment by JMurphyWeb** [comment]
The contractor didn't receive the follow up email, after checking the docusign routing, it looks like the `Recipient`  (non signing) has to view the document before it continues around the the chain. Which is not desired behaviour.

<img width="1061" alt="screen shot 2017-07-06 at 10 30 39" src="https://user-images.githubusercontent.com/12638261/27905025-920309bc-6236-11e7-9adf-a5ad052a8fcc.png">

**Comment by jonscottfilm** [comment]
there were 3 test initials fields, did the far left one not work at all?

**Comment by jonscottfilm** [comment]
about middle of the page, actually

**Comment by JMurphyWeb** [comment]
no only the two that i screen shotted

**Comment by jonscottfilm** [comment]
BAM - get in, @JMurphyWeb! Closing.
