### ISSUE TITLE
Recipient receives document at the beginning and holds up chain

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#476]
The recipient ( or `certifiedDelivery`) receives the document first, but should be last.

Also seems to hold up the chain if they don't view the document which is troublesome. 

Bug from #448 

Issue comment: https://github.com/karmaradio/karma/issues/470#issuecomment-313346703

**Comment by JMurphyWeb** [comment]
I have made the recipients `carbonCopies`: https://docs.docusign.com/esign/restapi/Envelopes/EnvelopeRecipients/#carbon-copies-recipient

Forced their routing order to be:
length of chain + 2 + their index relative to other recipients.

So they should always come last.

**Comment by jonscottfilm** [comment]
Nice!

**Comment by jonscottfilm** [comment]
Working. Closing.
