### ISSUE TITLE
Edit a project

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#5]
As a project manager, I can edit one of my existing projects

**Comment by jonscottfilm** [comment]
Nav to edit project needs creating.

**Comment by jonscottfilm** [comment]
At some point, ideally as we go, we'll need to fix data-validation format, i.e. sentence case for addresses, eg:

![image](https://cloud.githubusercontent.com/assets/28431542/26257497/c3f9cdd2-3cb8-11e7-9ee7-e24744cbc4a3.png)

**Comment by jonscottfilm** [comment]
Like the section separation for Project details. Good to do for My Profile too. #6

**Comment by JMurphyWeb** [comment]
@jonscottfilm although its not that clear, there is an 'edit' link at the bottom of the project details view.

Regarding this:
>  sentence case for addresses

We can create an issue that can hold this requirement as it is probably an app-wide concern

**Comment by jonscottfilm** [comment]
Agreed, correct casing is app-wide concern.

**Comment by jonscottfilm** [comment]
Just in case you see a different view. This is my Project details (I think, although I recall I vertical one...) view:

![image](https://cloud.githubusercontent.com/assets/28431542/26304844/c60ef632-3ee4-11e7-8c66-b497acae3a81.png)

**Comment by jackcarlisle** [comment]
@jonscottfilm yes this is different. This is  a list of all projects you have created. We will be getting rid of this view and replacing it with the vertical details one. You will be able to see the list of projects you have created on the dashboard at root path `/`

**Comment by jonscottfilm** [comment]
Ahh, gotya. And found it. Thx

![image](https://cloud.githubusercontent.com/assets/28431542/26305215/51224c00-3ee6-11e7-9062-8659c8e272d6.png)

**Comment by jonscottfilm** [comment]
Edit project works. Should 'CREATE' button, be changed to 'UPDATE'?

*Occurred to me: having sent out offers, what effect does editing a project have on those pre-existing offers with regards to the new project information...?

**Comment by jackcarlisle** [comment]
@jonscottfilm in the process of fixing the button text now

**Comment by jonscottfilm** [comment]
OK, marvellous. 
And I guess **_if_** anyone already has a merged, executed contract, (unlikely for global details to change this far into the project), then those few individuals can be dealt with separately.

**Comment by jonscottfilm** [comment]
Other then fixing the navigation to it, 'edit project' is good. Closing.
