### ISSUE TITLE
Go LIVE

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#506]
## LAUNCH CHECKLIST
There are a number of things that we need to do before we can launch:

- [x] ensure all emails are formatted and consistent *(in progress)*
- [x] swap over to the correct domain that will be used **(does for example: web.teamengine.co.uk, work?, and do we own it?!)** **JONO**
- [x] replace all instances of Karma with real name
- [x] sign up for heroku membership to prevent application from sleeping **JONO**
- [x] add Privacy terms copy
- [x] ensure all links are correct **(should terms & privacy links in emails take users to the terms & privacy pages on the engine website, not the app?)**

**Comment by JMurphyWeb** [comment]
Old guide getting heroku app working with network solutions:
https://stackoverflow.com/questions/15982861/at-a-loss-for-configuring-network-solutions-and-heroku

**Comment by JMurphyWeb** [comment]
Have followed these steps:
https://stackoverflow.com/a/30005195/5131514

**Comment by JMurphyWeb** [comment]
SO question asked:
https://stackoverflow.com/questions/45105466/custom-domain-name-with-heroku-and-network-solutions
