### ISSUE TITLE
Update profile bug

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#526]
Updating first name or last name errors:

<img width="1151" alt="screen shot 2017-07-13 at 11 12 27" src="https://user-images.githubusercontent.com/12638261/28161659-3f10fc88-67bc-11e7-821a-29fa45ea8932.png">

- [x] Update is not possible.
- [x] Errors are not shown.
- [x] Breadcrumbs
- [x] Title in correct place

@jonscottfilm I will fix the logic, but what about the layout of this page with the error message? is this normal?

**Comment by jonscottfilm** [comment]
no, that error message should be in the ususal flash location at top of grey subheader

And issues is listed to move page title and add proper breadcrumbs

**Comment by JMurphyWeb** [comment]
<img width="824" alt="screen shot 2017-07-13 at 12 58 01" src="https://user-images.githubusercontent.com/12638261/28165255-f3b559a0-67ca-11e7-9d7c-78238811b56d.png">

**Comment by jonscottfilm** [comment]
Working. Bam. Closing.

**Comment by jonscottfilm** [comment]
Although - error message is not in usual flash location in subheader.
