### ISSUE TITLE
Startpack: Vehicle allowance checkbox should not prevent partial submission of startpack

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#528]
Even if the vehicle checkbox is checked, the user should be able to submit a partially submitted startpack

Offer can only be accepted if they have filled in the required vehicle related fields

The 2 vehicle related images are NOT required if no vehicle allowance given.

**Comment by JMurphyWeb** [comment]
<img width="1200" alt="screen shot 2017-07-13 at 14 04 30" src="https://user-images.githubusercontent.com/12638261/28167659-3c6a7dfc-67d4-11e7-8628-c125b23a5a6e.png">

Screenshot indicates the startpack error when user has ticked the vehicle checkbox, but hasn't filled all the text fields.

The image/file upload fields are not required here as vehicle allowance is set to 0.

**Comment by jonscottfilm** [comment]
Working..., EXCEPT now with Vehicle unchecked, and/or no allowance, Vehicle Allowance document (if present) ALWAYS merges.

**Comment by beccacca** [comment]
#524

**Comment by JMurphyWeb** [comment]
@jonscottfilm I seem to remember fixing this..
