### ISSUE TITLE
Project Offer View

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#54]
Due to the fact that a project contains a large amount of information we need to create a new view that can hold and handle all offers that relate to that project. The view will contain meta information about the project as well as offer status (much like the project tile on the dashboard).

- [ ] create project offer view `/project/:id/offers`

**Comment by jonscottfilm** [comment]
Can't test, or at least see offers in the view, due to #78 bug.

**Comment by jonscottfilm** [comment]
Forgive me if I'm posting in the wrong place (PM's offer view vs. Contractors offers dashboard view), but nonetheless an issue...

I just tested sending an offer to a user (engineplans@gmail/.com) who has no projects. i.e. as a PM would be doing.
(thus far I've only sent offers to one of my logins whereby projects already exist)

The offer doesn't appear:

![image](https://cloud.githubusercontent.com/assets/28431542/26306371/06646414-3eeb-11e7-9e8a-0a11596889be.png)

![image](https://cloud.githubusercontent.com/assets/28431542/26306376/0b47fcde-3eeb-11e7-9aa5-3d4d281618d1.png)

**Comment by jackcarlisle** [comment]
@jonscottfilm we haven't hooked up the offers on the dashboard yet. It will exist in the database but we haven't yet added the offer tiles here. Fixing today!

**Comment by jonscottfilm** [comment]
gotya. thanks.

Presume this issue #55 actually refers to this view:
![image](https://cloud.githubusercontent.com/assets/28431542/26307395/2b33e3e0-3eec-11e7-918b-ad7ed143f6ed.png)

**Comment by jackcarlisle** [comment]
@jonscottfilm yes that's correct. I've opened a separate issue to deal with the offers on the dashboard -> #96

**Comment by jonscottfilm** [comment]
Working! Closing.
