### ISSUE TITLE
Add 'End date:' field to all offer views

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#567]
Add 'End date:' field to all offer views. (Urgently required for BBC job)

Optional, i.e. not required. Some projects will use it, some won't.

This first test project show an offer start date, and end date. If the person is going to work beyond that date, they issue an extension letter. Seems daft, but hey. 

For this show, they will issue the extension letter outside of the app, but this functionality should play a part in our Phase 2 conversations about 'Contractor gives notice, Project gives notice, Project extends end date...' 

Locate the field between Start date and Contract type:

![image](https://user-images.githubusercontent.com/28431542/29635317-9ee43564-8844-11e7-9c40-01f09a599a53.png)

and between Start date and Daily or weekly in the offer edit view:

![image](https://user-images.githubusercontent.com/28431542/29635391-d1db759a-8844-11e7-95ac-2764f9be0af9.png)

**Comment by JMurphyWeb** [comment]
<img width="238" alt="screen shot 2017-08-27 at 11 00 30" src="https://user-images.githubusercontent.com/12638261/29748426-fe028260-8b16-11e7-9daa-5c1339aaa6d3.png">

Still need to check functionality & add/fix tests

**Comment by JMurphyWeb** [comment]
<img width="296" alt="screen shot 2017-08-27 at 11 12 51" src="https://user-images.githubusercontent.com/12638261/29748521-b056f22e-8b18-11e7-8a09-0efaf34a52e5.png">

**Comment by JMurphyWeb** [comment]
Started adding validation but not finished. In `add-validation-to-offer-end-date` branch, PR: https://github.com/karmaradio/karma/pull/597

**Comment by jonscottfilm** [comment]
Formatting being fixed. Closing.
