### ISSUE TITLE
Fix button borders

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#578]
Fix button borders

eg, in Create Account & Log-in views, when CREATE button & LOG-IN buttons are selected, the border increases jiggling the layout slightly to one's eye (do you remember like we had in the main forms). 

I think the fix was to give it an existing border, same colour as button background, same width as 'select border', so when selected, there is no apparent difference. (like email and password buttons in same view). 

Might need to reduce the overall size of the button to compensate the fact that it will have a permanent border. Change 'select border' colour, try our light grey (E9EAEB), if not, use same dark colour as other fields in the same view.

Seems to apply to all buttons throughout app, e.g: ADD APPROVER, UPLOAD (document):

![image](https://user-images.githubusercontent.com/28431542/29636737-b54bf0a8-8849-11e7-92c2-c338f8d6e109.png)

Suggest light grey (E9EAEB), so it works for all colour of buttons, as I see file uploads are darker indigo, and currently with NO 'select border colour':

![image](https://user-images.githubusercontent.com/28431542/29636770-d6e2b01c-8849-11e7-9827-7b9face1f575.png)

**Comment by jonscottfilm** [comment]
Was _about_ to close but realised that it would be helpful if we have a noticeable different coloured border on ALL buttons when button is selected, perhaps the light grey mentioned above, so a user knows they have selected the button. 

Just like the grey field boxes have an indigo border when selected.

e.g., tabbing through fields of the startpack, a light border on the file upload button would indicate to me I can hit space to press the button.

Current: (* note, checkbox could do with a 'selected' indigo border too) 

![image](https://user-images.githubusercontent.com/28431542/30814041-f182bce2-a206-11e7-8bf1-95c6bd75d98f.png)

**Comment by jackcarlisle** [comment]
@jonscottfilm I changed it to light indigo because it wasn't showing up properly on the grey background of the app
