### ISSUE TITLE
PM can view an offer they have made

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#59]
A PM can view an offer which will summarise the key information of that offer

**Comment by JMurphyWeb** [comment]
linked to #12

**Comment by JMurphyWeb** [comment]
![screen shot 2017-05-17 at 18 26 32](https://cloud.githubusercontent.com/assets/12638261/26167364/6cffd606-3b2e-11e7-8379-18f69ca9ecf4.png)

**Comment by jonscottfilm** [comment]
Likewise, can't fully test until #78 is fixed. Thanks.

**Comment by jonscottfilm** [comment]
What's the url for this 'PM view offer' view please?

![image](https://cloud.githubusercontent.com/assets/28431542/26307449/88c7a488-3eec-11e7-9378-cb3d3c3ac8ac.png)

**Comment by jonscottfilm** [comment]
Sorry! Sussed it, /offer _id.

projects/5/offers/1

**Comment by jonscottfilm** [comment]
Works. Closing.
