### ISSUE TITLE
Show added approval chain

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#594]
In edit project view, show approval chain below each uploaded project document, to make it easy to see what has been set up and what hasn't.

*Reword button label: 
'ADD APPROVERS' when you have not yet set up a chain
'EDIT APPROVERS' to edit an existing chain

**Comment by jonscottfilm** [comment]
What do we think of this? Or in light grey like our new 2 button colours?

![image](https://user-images.githubusercontent.com/28431542/31656427-70d304c0-b323-11e7-9aab-56d066958660.png)

**Comment by jackcarlisle** [comment]
<img width="955" alt="screen shot 2017-10-18 at 11 33 15" src="https://user-images.githubusercontent.com/12450298/31714035-2acf11f0-b3f8-11e7-95a7-9e491ca5a296.png">
