### ISSUE TITLE
Edit Startpack

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#6]
As a contractor/project manager,
I want to be able to edit my profile (start pack) information,
So that I can update it as and when it is required

**Comment by jonscottfilm** [comment]
Yes - I can update my startpack. That works. Lot's of comments I'm afraid, but tell me to poke it...

Long term - I think the startpack should incorporate info from Profile and Offer. Without it, it seems random to be asked for your Middlenames. And for example, Date of Birth follows Emergency Contact information, so could be Date of Birth of _that_ person...

Gender field to be dropdown: Male/Female/Other/Prefer not to say (clean data in)

Error '! Can't be blank' should go once field is filled.

Fieldname Class - what is that?

Upload fields are inactive to me

Upload fields will need appropriate labels/helper text, i.e. 'Upload your passport'. 'Upload your box or equipment inventory list with insurance values'

Primary address 2 should not be 'required' i.e optional

'Box rental value' _should_ be 'Box rental _inventory_ value' to avoid confusion of it being the total earned by box rental.

Student loan checkboxes need all the dialogue explaining the question.

Likewise explanation text for: 'For PAYE only' - I think is the 'First / Only job of the year'

**Comment by JMurphyWeb** [comment]
for paye only has changed into a radio so that one should be more clear.
`Class`is now `Also known as`

Box rental label updated

primary address 2 no longer required

Student loan logic not done yet.

**Comment by JMurphyWeb** [comment]
We will look into files upload issues and student loan student loan logic.

**Comment by jonscottfilm** [comment]
Yes, I meant immediately after field is filled. Future enhancement, ok. I will raise issue.
https://github.com/karmaradio/karma/issues/6#issuecomment-304938653

Thanks re box rental. 
'Equipment rental _inventory_ value' needs amending in same way.

**Comment by JMurphyWeb** [comment]
@jonscottfilm 

> Upload fields are inactive to me

What do you mean by this? I just checked on Heroku and I am able to upload files

**Comment by jonscottfilm** [comment]
I think this is the issue stopping me from proceeding (https://github.com/karmaradio/karma/issues/201#issuecomment-305152076):

Unclickable text/button, eg: Passport image:

![image](https://cloud.githubusercontent.com/assets/28431542/26628287/6335f11a-45f5-11e7-984d-086e329a1282.png)

**Comment by JMurphyWeb** [comment]
![screen shot 2017-05-31 at 11 35 56](https://cloud.githubusercontent.com/assets/12638261/26628274/578091c2-45f5-11e7-8381-2c3e0884015d.png)


box & equipment helper text added & passport helper text added

**Comment by JMurphyWeb** [comment]
@jonscottfilm thanks I have found the issue and fixing now. Screenshot was very useful for me to debug.

**Comment by JMurphyWeb** [comment]
All fixed and temporarily testable on heroku (maybe give it a few minutes to deploy).

The only outstanding comment is the student loan logic. Working on that now.

**Comment by jonscottfilm** [comment]
testing now

![image](https://cloud.githubusercontent.com/assets/28431542/26629432/48cd4a76-45fa-11e7-9503-e0bf0138fe88.png)

**Comment by JMurphyWeb** [comment]
Student loan logic:

> "1. I have a Student Loan which is not fully repaid If Yes to statement 1 go to 2.
2. I am repaying my Loan direct to the Student Loan Co.
If Yes to statement 2 go to 5 else go to 3.
3. I have a Plan 1 Student Loan
- You lived in Scotland or Northern Ireland when you started your course
- You lived in England or Wales and started course before 1 Sept 2012.
4. I have a Plan 2 Student Loan
- You lived in England or Wales and started course on or
after 1 Sept. 2012.
5. I finished my studies before the last 6 April"

**Comment by jonscottfilm** [comment]
Yay!

![image](https://cloud.githubusercontent.com/assets/28431542/26630371/48c6d714-45fe-11e7-9b8c-1c531640dfe9.png)

**Comment by JMurphyWeb** [comment]
Student loan logic in.

**Comment by JMurphyWeb** [comment]
this should be testable now, although I think the form needs some styling.

**Comment by jonscottfilm** [comment]
Other than styling, re-labelling and typos, (noted in #247) this is working.
