### ISSUE TITLE
Date drop-downs reset to today when editing

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#600]
A date saves fine. When editing an item that contains a date input, it resets to today's date, it should preserve the value that is stored in the DB.

**Comment by JMurphyWeb** [comment]
- [ ] No date has a default.  (remove with_default?)
- [ ] No need for DOB (remove `dob`)
- [ ] Next aim is to get dates preserved from DB into edit view.
- [ ] Add `day / month / year` prompts to all date fields where there is no date value.

**Comment by JMurphyWeb** [comment]
removed dob from all files

**Comment by JMurphyWeb** [comment]
After a quick local test looks good.

**Comment by jonscottfilm** [comment]
marvellous
