### ISSUE TITLE
PM can edit a pending offer

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#65]
A PM can edit a pending offer, but can't edit an accepted/rejected offer

**Comment by JMurphyWeb** [comment]
bug #78 is probably preventing this from moving into please test

**Comment by jonscottfilm** [comment]
This veers into the world of contractor flow, but it would be good for the updated offer view to **highlight** the amended field... Or at least mention it at top of the offer view?

**Comment by jonscottfilm** [comment]
Edit and Back text links need separating throughout app.

Edit offer works. Closing.

**Comment by jonscottfilm** [comment]
However - I tried to reject a previously accepted offer, I got correct error message 'you can only edit pending offers'. Offer tile stayed green.

When I navigated away, and back to dashboard, that offer was red, like it was rejected.
_(potential complication being I am PM sending offers to myself?)_

![image](https://cloud.githubusercontent.com/assets/28431542/26734187/178255e4-47b5-11e7-8500-52d5e30389d4.png)

**Comment by jackcarlisle** [comment]
This is odd, you shouldn't be able to reject an offer once you've accepted it. And you also shouldn't be able to edit an offer that's either been accepted or rejected. Can you outline the exact flow of the error so that I can re-produce it?

**Comment by jonscottfilm** [comment]
Thought you might ask that. Hard to say now. I will try to recreate. It's a possibility that I've got confused between 2 different projects. :) I'll let you know.

**Comment by JMurphyWeb** [comment]
@jonscottfilm just wanted to remind you. This feels like it would be a multiple test accounts issue but please do verify 👍

**Comment by jonscottfilm** [comment]
Working
