### ISSUE TITLE
Make offer should send email invite to contractor

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#72]
If a PM makes an offer to a contractor, the contractor should receive an offer email.

The contents of the email should be determined by whether the contractor is already a registered user.

**Comment by jonscottfilm** [comment]
Can't test due to #78.

**Comment by JMurphyWeb** [comment]
@jonscottfilm this should be testable now 🎉

**Comment by jonscottfilm** [comment]
All good. (format of email notifications for later sprint). 
Closing.
