### ISSUE TITLE
take SES out of sandbox

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#75]
We want to send emails to many different accounts

**Comment by jackcarlisle** [comment]
![screen shot 2017-05-19 at 10 54 24](https://cloud.githubusercontent.com/assets/12450298/26242815/a7b0ba3c-3c81-11e7-9ab4-36ccce0d72a1.png)

**Comment by jackcarlisle** [comment]
## 🎉 Email received from AWS saying that our case has been approved! 

We're no longer in the sandbox which means:

- sending quota = 50,000/day
- maximum send rate = 14/second
- no longer need to verify email addresses

**Comment by JMurphyWeb** [comment]
now done
