### ISSUE TITLE
Rounded corners for drop-down fields

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#76]
Static field containers are formatted with rounded corners - this is preferred. 
Drop-down fields appear to have square corners. 
All fields should have uniform style, with rounded corners.

**Comment by jackcarlisle** [comment]
Hi @jonscottfilm , could you upload a screenshot of an exact case where this is happening please?

**Comment by jonscottfilm** [comment]
See 'Type' & 'Budget' having square corners, vs. 'Name' being rounded.

![image](https://cloud.githubusercontent.com/assets/28431542/26244377/4a177f0e-3c87-11e7-9a64-4d02bead1a36.png)

**Comment by jonscottfilm** [comment]
Low priority, but..

Might this be a browser issue? This form looked fine in Noga's machine earlier...

![image](https://cloud.githubusercontent.com/assets/28431542/26452404/c4706c1e-4157-11e7-9eed-ee720870c50a.png)
