### ISSUE TITLE
Project Terms & Conditions

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#77]
As a project manager,
I will need to agree to additional Terms & Conditions with Karma at the point I create a new project, 
in order to utilise information which invited contractors agree to share with my project.

**Comment by JMurphyWeb** [comment]
@jonscottfilm great. Please add the following labels:
- user story
- priority of your choice (this doesn't warranty a priority 1)

**Comment by jonscottfilm** [comment]
Current T&C's cover all this.
