### ISSUE TITLE
new offer: working-week dropdown is invalid

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#78]
![screen shot 2017-05-19 at 11 25 55](https://cloud.githubusercontent.com/assets/12638261/26244037/0a62fd1c-3c86-11e7-8c7e-a95548a19f8f.png)

It seems that any offer will fail validation at the working week dropdown

**Comment by jackcarlisle** [comment]
This is because it's being sent through as a string (not sure why). We'll need to change it to a float before we create a changeset with it

**Comment by JMurphyWeb** [comment]
@jackcarlisle we should be able to do that when we build the drop down.

**Comment by jackcarlisle** [comment]
@JMurphyWeb Yeah need to look into why it's sending the string representation of the float instead. Can't see any issues in the existing dropdown: 

```elixir
  <%= component "dropdown.html",
  form: f,
  atom: :working_week,
  options: ["5 days": 5.0, "5.5 days": 5.5, "6 days": 6.0],
  prompt: "Select an option..."
  %>
```

**Comment by JMurphyWeb** [comment]
@jonscottfilm if you can make an offer with working week dropdown set, then this issue is closeable

**Comment by jonscottfilm** [comment]
@JMurphyWeb would if I could. What is the url please, as navigation from Project dashboard is giving Internal Server Error.

**Comment by JMurphyWeb** [comment]
Sorry we merged some new code in yesterday so need to update some settings, will do today and let you know. 

URL is /projects/project_id/offers/new

**Comment by JMurphyWeb** [comment]
That should be done now @jonscottfilm

**Comment by jonscottfilm** [comment]
Closed
