### ISSUE TITLE
update pending offer sends new email to contractor

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#79]
If a pending offer is updated, a new email should be sent to the contractor.

**Comment by JMurphyWeb** [comment]
@jonscottfilm how does that implementation sound

**Comment by JMurphyWeb** [comment]
Generic email sent asking user to log in to view the updated offer.

**Comment by jonscottfilm** [comment]
Works.

Should the blue flash read: 'Offer updated successfully, **and re-emailed to recipient**' ?

To match flow of 'create offer', and for UX to know it has been sent?

**Comment by JMurphyWeb** [comment]
Yeh i think that sounds good. leave this issue open, we'll update the message.

**Comment by JMurphyWeb** [comment]
@jonscottfilm this is now done

**Comment by jonscottfilm** [comment]
Great! Closed.
