### ISSUE TITLE
Create new offer

### ISSUE THREAD

**Issue by JMurphyWeb** [karmaradio/karma#8]
As a project manager, I can create an 'offer' to invite a contractor to join the project.

**Comment by jonscottfilm** [comment]
Does this list not belong in 'project creation'?

Locations will be postal addresses of locations selected for shooting. These are unlikely to be know or fixed at the offer stage.

Project Manager will decide Department at the offer stage, and _should_ decide job title... 

Only files PM will upload will be the custom forms which each studio will provide for each project. Forms like Company Policies: Health & Safety, Security etc. Stuff each user should view, prior to signing _some_ of them, via Webmerge & Docusign.

**Comment by jonscottfilm** [comment]
I suppose these fields do play as part of the offer, as well as project creation.

**Comment by JMurphyWeb** [comment]
Apologies, they are now being moved into #4 along with any comments you made here.

**Comment by JMurphyWeb** [comment]
Closing this issue as it is a duplicate of #12
