### ISSUE TITLE
Password strength hint

### ISSUE THREAD

**Issue by jonscottfilm** [karmaradio/karma#83]
Whenever a user has to input password, whether at log-in or account creation, helper text should hint at password strength, as a reminder of what to include, or what _is_ already included in the password for the Karma service. We all have so many passwords to remember.

**Comment by jonscottfilm** [comment]
Could just be a placeholder, like you currently have saying, 'Must contain at least 6 characters'?

**Comment by jackcarlisle** [comment]
@jonscottfilm so are you happy with the placeholder implementation for now? Or should we add a time estimate for implementing the password strength indicator?

**Comment by jonscottfilm** [comment]
Placeholder works, but let's have it state exact requirements: 1 cap, 1 symbol, min 6 characters etc.

**Comment by jackcarlisle** [comment]
https://stackoverflow.com/questions/36966980/find-if-codepoint-is-upper-case-in-elixir

**Comment by JMurphyWeb** [comment]
@jonscottfilm you can move issues like this out of the milestone but leave open if you would still like it in the backlog.

**Comment by jonscottfilm** [comment]
Ok
