### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by jackcarlisle** [karmaradio/karma#94]
We need to tighten up the navigation of the application. At the moment we have a couple of links that lead to pages that we aren't going to use in the final version so we should get rid of those.

- [x] fix the navigation of the application

**Comment by JMurphyWeb** [comment]
@jonscottfilm can you verify that the navigation is now more smooth with no unexpected behaviour?

**Comment by jonscottfilm** [comment]
Nav all seems to work as expected. Nice.

It's easier to spot the design inconsistencies (which I know we have a plan for). Should I create issues for design things I notice? 
eg: page-width consistency, between Log-in and New Account, or full-width Project details view, and the dashboard.

**Comment by jonscottfilm** [comment]
Nav working. Closing.

**Comment by jackcarlisle** [comment]
@jonscottfilm yes please create a design issue and then add all of your observations to the same issue so that they are contained.

**Comment by jonscottfilm** [comment]
gotya

**Comment by jonscottfilm** [comment]
Sorry - think this should nav to projects view, not main dash:

https://karmaradio.herokuapp.com/projects/7/edit

![image](https://cloud.githubusercontent.com/assets/28431542/26318787/399307d6-3f14-11e7-9dc9-3e06aadf5249.png)

**Maybe leave for user testing.**

**Comment by JMurphyWeb** [comment]
@jackcarlisle not sure what to do with this issue now its merged

**Comment by jackcarlisle** [comment]
@JMurphyWeb it's now ready to be tested. Handing over to @jonscottfilm

**Comment by jonscottfilm** [comment]
Works. Closed.
